### ISSUE TITLE
ERROR: Cert does not exist!

### ISSUE THREAD

**Issue by izznogooood** [linuxserver/docker-letsencrypt#100]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
**Ubuntu 16.04.**
**stdout**:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
2048 bit DH parameters present
SUBDOMAINS entered, processing
Sub-domains processed are:  -d www.spanglish.no -d nextcloud.spanglish.no
E-mail address entered: ama@getmail.no
Different sub/domains entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created
Generating new certificate
IMPORTANT NOTES:
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container
```

**stderr**:

```
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: argument --cert-path: No such file or directory
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
```

**Init**:

**[Unit]
Description=A Letsencrypt nginx container, brought to you by LinuxServer.io.
Documentation=https://hub.docker.com/r/linuxserver/letsencrypt/
After=network.target docker.socket
Requires=docker.socket

[Service]
RestartSec=10
Restart=on-failure

Environment="NAME=letsencrypt"
Environment="IMG=linuxserver/letsencrypt"

# Pull new image for updates
ExecStartPre=-/usr/bin/docker pull $IMG

# Clean-up bad state if still hanging around
ExecStartPre=-/usr/bin/docker rm -f $NAME

# Main process
ExecStart=/usr/bin/docker run \
  --name $NAME \
  --cap-add=NET_ADMIN \
  --name=letsencrypt \
  -v /opt/docker/letsencrypt:/config \
  -e PGID=1000 -e PUID=1000  \
  -e EMAIL=my@email.com \
  -e URL=mydomain.com \
  -e SUBDOMAINS=www,nextcloud \
  -p 80:80 -p 443:443 \
  -e TZ=Europe/Oslo \
  $IMG

# Stop Service
ExecStop=/usr/bin/docker stop $NAME

# Large image causes a timeout because of the time it takes
# to download and extract / run.

# TimeoutStartSec=infinity

#Prevent systemd from killing the service
KillMode=none

[Install]
WantedBy=multi-user.target**

I can not for the life of me figure this out. I have double checked the dns records with nginx servers and they are all fine. There should be no issues.

**Comment by sparklyballs** [comment]
letsencrypt discovered a vulnerability with using TLS validation on port 443

https://github.com/linuxserver/docker-letsencrypt#setting-up-the-application

if your ISP does not allow port forwarding on port 80 then there isn't much we can do to help until our dns validation branch has undergone testing

**Comment by izznogooood** [comment]
There you go... Thanks.

**Comment by Askill** [comment]
Problem still exists:
ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container

Port 80 is being forwarded and mapped

**Comment by j0nnymoe** [comment]
@Askill useful information there that you've provided on a ticket that's been closed for 18 months.

**Comment by Askill** [comment]
@j0nnymoe I gues that means it should be reopened then...

**Comment by j0nnymoe** [comment]
No because this issue was due to letsencrypt dropping support for TLS validation (if you had read the issue). You should be using http or DNS validation.

**Comment by j0nnymoe** [comment]
@Askill if you believe there is an issue with our container. Please open a new ticket and provide us with as much information you can.
