### ISSUE TITLE
Update certbot to Fix Let's Encrypt Issue 5405

### ISSUE THREAD

**Issue by Lockszmith** [linuxserver/docker-letsencrypt#101]
Per the information in [Let's Encrypt Issue #5405](https://github.com/certbot/certbot/issues/5405#issuecomment-358524100) **certbot** needs to be updated because renewal and generation of certificates isn't currently working:

**Comment by aptalca** [comment]
That info is irrelevant because this image does not use the nginx or apache plugins with certbot.

No need to update certbot. You just need to validate through http. Instructions are in the readme: https://github.com/linuxserver/docker-letsencrypt/blob/master/README.md

**Comment by Lockszmith** [comment]
Thanks @aptalca  for the quick response.

Everything in the system was working up to today, the params I've been using are:
```      URL: "example.com"
      SUBDOMAINS: "sub-a,sub-b,sub-c"
      EMAIL: "admin@example.com"
      ONLY_SUBDOMAINS: "true"
```

The error in '/var/log/letsencrypt/letsencrypt.log' is the following one:
The only change I made today is to change `SUBDOMAINS` to add an additional item:
```
    SUBDOMAINS: "sub-a,sub-b,sub-c,sub-d"```
2018-01-25 23:37:54,166:CRITICAL:certbot.auth_handler:Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
2018-01-25 23:37:54,166:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 786, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 85, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 68, in get_authorizations
    self._choose_challenges(domains)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 103, in _choose_challenges
    self.authzr[dom].body.combinations)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 374, in gen_challenge_path
    return _find_smart_path(challbs, preferences, combinations)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 411, in _find_smart_path
    _report_no_chall_path()
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 442, in _report_no_chall_path
    raise errors.AuthorizationError(msg)
AuthorizationError: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
```

To be sure I'm not messing up with my configuration, I reset the storage, and used all vanilla nginx configuration, still getting the same issue.

**Comment by aptalca** [comment]
You need to set the `HTTPVAL` variable to `true` for http (port 80) validation. It's in the readme

**Comment by KillSwitchIO** [comment]
I two am having this issue even with the HTTPVAL set to true. I believe the certbot must be updated to v 0.20.0

**Comment by Lockszmith** [comment]
@KillSwitchIO, @aptalca suggestion to set HTTPVAL to true resolved the issue.
The certbot should be updated, but this should not delay you from resolving the issue.

**Comment by aptalca** [comment]
@KillSwitchIO did you update your image?

**Comment by KillSwitchIO** [comment]
So I did add the httpval and I had the same issue. I looked in the in it 50 file and found the scripts in the docker. For http it was calling out a verification method of http. According to the certbot man file https://certbot.eff.org/docs/using.html it should be http-01. So I modified the script saved and reloaded and was able to successfully get a certificate. This is an actual bug with the docker image. While the certbot version is v0.19.0 and is ok, the challenge type is incorrect.

**Comment by KillSwitchIO** [comment]
So I did add the httpval and I had the same issue. I looked in the in the init 50 file and found the scripts in the docker. For http it was calling out a verification method of http. According to the certbot man file https://certbot.eff.org/docs/using.html it should be http-01. So I modified the script saved and reloaded and was able to successfully get a certificate. This is an actual bug with the docker image. While the certbot version is v0.19.0 and is ok, the challenge type is incorrect. (Corrections: Sorry dupe I'm in Mobile and can't edit)

**Comment by aptalca** [comment]
https://certbot.eff.org/docs/using.html#standalone

`http` and `http-01` are currently the same thing. `http-01` refers to version 1 of the http method. `http` refers to the latest version of the http method, which currently is 1.

There is nothing wrong with the image and it works for everyone else. Perhaps you added `httpval`? Without logs or your docker run/create command, I can't tell what you did wrong.

You need to add `-e HTTPVAL="true"`. It's in the readme
