### ISSUE TITLE
Error when generating the certs (50-config: line 149)

### ISSUE THREAD

**Issue by jodumont** [linuxserver/docker-letsencrypt#103]
Hi LinuxServer and cie;
I read these [three issues](https://github.com/linuxserver/docker-letsencrypt/issues?utf8=%E2%9C%93&q=50-config) and try to dig a little bit about my mistake but I can't figure it, so I come here to ask you some light ;)

**my .env file**
```
DATA=/docker/letsencrypt/data
EMAIL=letsencrypt@chez.moi
HTTPVAL=true
ONLY_SUBDOMAINS=true
SUBDOMAINS=home
TZ=Europe/Zurich
URL=chez.moi
```

If I understood well, **--cap-add** is just used by **fail2ban**  
so I omit it because docker run with **--userns-remap=tape:duck**  
_just to mention, I have around 12 of your images running with this config_  
so I confident it's a local misunderstood with this one.

```
IMAGE=linuxserver/letsencrypt
PROJECT=${PWD##*/}
source .env

docker run -d \
--env-file .env \
--name $PROJECT \
--restart always \
-p 80:80/tcp \
-p 443:443/tcp \
-v $DATA/config:/config \
$IMAGE
```

So the error is : /var/run/s6/etc/cont-init.d/**[50-config](https://github.com/linuxserver/docker-letsencrypt/blob/master/root/etc/cont-init.d/50-config): line 149**  
which is try to make the fullchain  
but when I look inside my /docker/letsencrypt/data/etc/letsencrypt/**live/home.chez.moi** don't exist.

Now my port 80 and 443 are truly redirected from my router to my server/docker and if I just turn on a nginx the web page respond at home.chez.moi

this is my : **/var/log/letsencrypt/letsencrypt.log**
```
2018-01-27 17:11:28,340:DEBUG:certbot.main:certbot version: 0.19.0
2018-01-27 17:11:28,340:DEBUG:certbot.main:Arguments: ['--non-interactive', '--renew-by-default', '--standalone', '--preferred-challenges', 'http', '--rsa-key-size', '4096', '-m', 'letsencrypt@chez.moi', '--agree-tos', '-d', 'home.chez.moi']
2018-01-27 17:11:28,340:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-01-27 17:11:28,353:DEBUG:certbot.log:Root logging level set at 20
2018-01-27 17:11:28,353:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-01-27 17:11:28,354:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2018-01-27 17:11:28,387:DEBUG:certbot.plugins.selection:Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x6a1d088e2550>
Prep: True
2018-01-27 17:11:28,387:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x6a1d088e2550> and installer None
2018-01-27 17:11:28,387:INFO:certbot.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2018-01-27 17:11:29,048:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2018-01-27 17:11:29,049:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
```

So I don't know why it can't make it and I need you help on it :)

**Comment by aptalca** [comment]
--cap-add is for iptables, which fail2ban requires. Either that or --privileged but it shouldn't prevent validation.

I don't see any errors there. Please post your docker log for the container

**Comment by jodumont** [comment]
voilà

##  Stdout logs  

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 10-adduser: executing... 
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \ 
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donations/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    911
> User gid:    911
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 20-config: executing... 
> [cont-init.d] 20-config: exited 0.
> [cont-init.d] 30-keygen: executing... 
> using keys found in /config/keys
> [cont-init.d] 30-keygen: exited 0.
> [cont-init.d] 50-config: executing... 
> 4096 bit DH parameters present
> SUBDOMAINS entered, processing
> Only subdomains, no URL in cert
> Sub-domains processed are:  -d home.chez.moi
> E-mail address entered: letsencrypt@chez.moi
> Different sub/domains entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created
> Generating new certificate
> ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container

## Stderr logs  

> usermod: no changes
> usage: 
>   certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
> 
> Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
> it will attempt to use a webserver both for obtaining and installing the
> certificate. 
> certbot: error: argument --cert-path: No such file or directory
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> Plugins selected: Authenticator standalone, Installer None
> /var/run/s6/etc/cont-init.d/50-config: line 149:   282 Segmentation fault      certbot certonly --non-interactive --renew-by-default --standalone --preferred-challenges $PREFCHAL --rsa-key-size 4096 $EMAILPARAM --agree-tos $URLS

**Comment by aptalca** [comment]
Only thing I can think of is certbot is trying to get root access (perhaps to bind port 80) and is failing due to your userns-remap setting. Try without it

**Comment by jodumont** [comment]
ill try and tell you
of course I didnt think about it because linuxserver/docker-nginx work in the same condition and bind :80 and :443 without issue, but as you said no certbot in the equation ;)

**Comment by jodumont** [comment]
so I'll close this issue not because it's working

but because when I use : `linuxserver/nginx` in a userspace
and I add certbot _(with `apk add certbot` like you do)_

I'm able to generate a certificate with : `certbot certonly --webroot -w /config/www -d home.chez.moi`
so the issue **is not uerns-remap**.

If I had to guest I'll point to the `--standalone` **vs** `--webroot` option

**Comment by aptalca** [comment]
--webroot does not put up its own webserver, but uses the existing nginx one. So the issue could still be certbot/python not being able to bind to port 80 with userns-remap
