### ISSUE TITLE
Individual certificates for different domains/subdomains

### ISSUE THREAD

**Issue by realies** [linuxserver/docker-letsencrypt#117]
Currently it seems all domain certificates live within a single file. It would be great if there's an option to separate certificate files and not share a single certificate with all domains/subdomains.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-letsencrypt/pull/115

**Comment by gitsf** [comment]
I too would like separate certificates for domains. My current setup uses a letsencrypt docker and a seperate HaProxy docker. I tell the letsencrypt docker to create certificates and it stores each in it's own folder. then I just have to mount this folder in haproxy and configure it to use these domains.
I am testing this image out right now. But to make it work all my domains would be listed under the same certificate. Currently I have multiple domains example.com example1.com 
Then under these I have different subdomains. I dont want a user/visitor to example1.com to inspect the certificate and then see a list of like 30 different domains/subdomains that are for various uses not related the example1.com

**Comment by adam1010** [comment]
I switched to CaddyServer2 and it works great -- you can setup multiple domains with reverse proxy and Caddy automatically obtains separate certificates for each domain and keeps them up to date.
