### ISSUE TITLE
Running the container as root

### ISSUE THREAD

**Issue by viruz82** [linuxserver/docker-letsencrypt#119]
Hi,

running the container as root runs in to the following error:
```
[15-Mar-2018 18:51:15] ERROR: [pool www] please specify user and group other than root
[15-Mar-2018 18:51:15] ERROR: FPM initialization failed
```

The following parameter would fix it:
```
# php-fpm --help
...
 -R, --allow-to-run-as-root
               Allow pool to run as root (disabled by default)
```

Could you implement this?

Cheers

**Comment by aptalca** [comment]
Don't run our containers as root. We do not recommend or support it.

**Comment by romfrolov** [comment]
If anyone encounter the same problem, just set the following environment variables:

```
PUID=1000
PGID=1000
```

---

You can see the full configuration in my [gist](https://gist.github.com/romfrolov/dda160d0c32184056235102f6621411c).

**Comment by CHBMB** [comment]
@romfrolov But..... it already says that in the [README](https://github.com/linuxserver/docker-letsencrypt#parameters) and `PUID` & `GUID` are dependent on your host setup, so it's not a good idea to tell everyone to use the same thing, again, this is covered in the [README](https://github.com/linuxserver/docker-letsencrypt#user--group-identifiers) telling people how to find their necessary `PUID` and `PGID`

**Comment by aptalca** [comment]
@romfrolov plus, your config is not quite correct, it is set to host networking so your port mapping is ignored.

Let's not steer the users in the wrong direction.

**Comment by CHBMB** [comment]
Oh man, I didn't even look at the config..... :man_facepalming:

**Comment by PolGuixe** [comment]
Docker noob here. @CHBMB @aptalca Could you recommend a good resource on how to configure the docker user properly? 

Currently setting 
```
PUID=1000
PGID=1000
```
To avoid the error message.

Cheers,

**Comment by j0nnymoe** [comment]
@PolGuixe https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/
