### ISSUE TITLE
Add an environment variable for DNS propagation time

### ISSUE THREAD

**Issue by michaelkoetter** [linuxserver/docker-letsencrypt#125]
The default propagation times in certbot are rather short, for example 10 seconds for dns-cloudflare.
This is not enough, because the Cloudflare TTL seems to be 5 minutes [1] - so the validation almost certainly fails after 10 seconds, because LE won't find the TXT record.

This can be fixed by using the commandline options ````--dns-<plugin>-propagation-seconds <seconds>```` and specifying a longer time (should be the TTL or a bit longer just to be sure)
The propagation time depends on the DNS provider of course, I just happen to use Cloudflare which seems to work after 5 minutes.

Currently, my workaround is to add something like this in /config/etc/letsencrypt/cli.ini before the container is created:
````
dns-<plugin>-propagation-seconds 300
````

... but of course it would be much nicer to have a simple environment variable to configure this :)

[1] https://support.cloudflare.com/hc/en-us/articles/200169036-How-long-does-it-take-for-a-DNS-change-I-made-to-push-out-

**Comment by aptalca** [comment]
TTL doesn't mean your changes will go live after 5 minutes. It means that dns servers should not cache the result for more than 5 minutes (the name is counter intuitive). 

The changes on cloudflare are propagated almost immediately, definitely within seconds. You can check that on dnschecker.org

Now, if you do dns verification via letsencrypt, and then change your cloudflare settings and try to reverify within 5 minutes, the result they get the second time may be the cached result from the first verification. Then you can potentially run into an issue.

But for a fresh verification, 10 seconds is plenty of time for propagation. 

In fact, the default propagation wait time for each plugin is different. 10 sec for cloudflare and 30 seconds for others who are slower to send those propagation requests. 

I've used cloudflare verification many times because that was the service I used for testing dns verification. It never failed me, not once.

**Comment by aptalca** [comment]
What's the error? If you post a log, I'll take a look.

Make sure you're using the global api key and not the zone id

You can also open the cloudflare page during validation and keep refreshing to see if the txt entry is being created

**Comment by michaelkoetter** [comment]
I don't have access to the logs right now, but can provide them tomorrow. Although it seems unlikely that it's an issue with the container.
certbot logged something like "No TXT records found" which probably means LE couldn't look it up on their servers.
I checked on my Cloudfront Dashboard and also the audit log, and the record was definitely there. The same config works if I let certbot wait for 10 minutes, as described above - so it looks like something is preventing the update from being propagated quickly to whatever DNS infrastructure LE is using.

**Comment by greg-cook** [comment]
I am also experiencing this error. I am requesting a wildcard certificate and it always fails with the default propagation of 10 seconds.

Example of a failed verification (anonymized):
```sh
Variables set:
PUID=1000
PGID=1000
TZ=Australia/Sydney
URL=example.com
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
DHLEVEL=2048
VALIDATION=dns
DNSPLUGIN=cloudflare
EMAIL=me@example.com
STAGING=true

NOTICE: Staging is active
2048 bit DH parameters present
SUBDOMAINS entered, processing
Wildcard cert for example.com will be requested
E-mail address entered: me@example.com
dns validation via cloudflare plugin is selected
Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-cloudflare, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.com
dns-01 challenge for example.com
Waiting 10 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. example.com (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect TXT record "dPyaoCVrymf1-79dhqYPYLPP3W6b-NKRsM_jcAEgTig" found at _acme-challenge.example.com, example.com (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect TXT record "dPyaoCVrymf1-79dhqYPYLPP3W6b-NKRsM_jcAEgTig" found at _acme-challenge.example.com
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: example.com
   Type:   unauthorized
   Detail: Incorrect TXT record
   "dPyaoCVrymf1-79dhqYPYLPP3W6b-NKRsM_jcAEgTig" found at
   _acme-challenge.example.com

   Domain: example.com
   Type:   unauthorized
   Detail: Incorrect TXT record
   "dPyaoCVrymf1-79dhqYPYLPP3W6b-NKRsM_jcAEgTig" found at
   _acme-challenge.example.com

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

And the successful verification done straight after using `dns-cloudflare-propagation-seconds 30` as suggested by @michaelkoetter above (anonymized):
```sh
Variables set:
PUID=1000
PGID=1000
TZ=Australia/Sydney
URL=example.com
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
DHLEVEL=2048
VALIDATION=dns
DNSPLUGIN=cloudflare
EMAIL=me@example.com
STAGING=true

NOTICE: Staging is active
2048 bit DH parameters present
SUBDOMAINS entered, processing
Wildcard cert for example.com will be requested
E-mail address entered: me@example.com
dns validation via cloudflare plugin is selected
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-cloudflare, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.com
dns-01 challenge for example.com
Waiting 30 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/example.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/example.com/privkey.pem
   Your cert will expire on 2019-02-26. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```
