### ISSUE TITLE
dns-conf format for digital ocean

### ISSUE THREAD

**Issue by ktravelet** [linuxserver/docker-letsencrypt#136]
Whats the format of the dns-conf file for digital ocean?

**Comment by aptalca** [comment]
?? It's pretty self explanatory. Just plug in your token

https://github.com/linuxserver/docker-letsencrypt/blob/master/root/defaults/dns-conf/digitalocean.ini

**Comment by ktravelet** [comment]
There we go!  Would be nice if that was in the docs anywhere.

**Comment by aptalca** [comment]
Read the readme

That file is in your config folder and the readme tells you where to find it
