### ISSUE TITLE
DNS Validation Question

### ISSUE THREAD

**Issue by jwillmer** [linuxserver/docker-letsencrypt#139]
Why do I need to set "dns only" instead of "dns + proxy" in cloudflare if I like to use dns validation? I tried it with "dns + proxy" and it worked as well.

My problem is that I don't have IPv4 (only IPv6) and therefore need cloudflare to tunnel IPv4 clients. But this is only possible if I set the domain to "dns + proxy" otherwise cloudfare does nothing and IPv4 clients can't reach me.

**Comment by aptalca** [comment]
It will work if set correctly. The issues arise when cloudflare also tries to use its own ssl certs while proxying. I haven't played around with it too much so feel free to share your experience here
