### ISSUE TITLE
Wildcard cert validates and downloads correctly, but error is thrown that cert does not exist.

### ISSUE THREAD

**Issue by pmgarman** [linuxserver/docker-letsencrypt#144]
unraid 6.5.3

config: I'm not using nginx here, just mapping the certs dir into another container. using dns validation here via cloudflare.

settings:
![](http://c.pmgr.mn/MsdalO+)

Looks like maybe during wildcard cert download/setup it's not able to validate the cert exists after download? I'm successfully using the cert it downloads here in another container without issue. I'm not sure what the cloudflare ini file has to do with a cert downloading. Overall this final error here really seems broken.

```IMPORTANT NOTES:
- Congratulations! Your certificate and chain have been saved at:
/etc/letsencrypt/live/garman.io-0002/fullchain.pem
Your key file has been saved at:
/etc/letsencrypt/live/garman.io-0002/privkey.pem
Your cert will expire on 2018-09-24. To obtain a new or tweaked
version of this certificate in the future, simply run certbot

again. To non-interactively renew *all* of your certificates, run
"certbot renew"
- If you like Certbot, please consider supporting our work by:

Donating to ISRG / Let's Encrypt: https://letsencrypt.org/donate
Donating to EFF: https://eff.org/donate-le

ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

**Comment by aptalca** [comment]
You can't do only subdomains and wildcard. Set that to true
