### ISSUE TITLE
Wildcard cert for extra domains

### ISSUE THREAD

**Issue by YodaDaCoda** [linuxserver/docker-letsencrypt#153]
When using `-e SUBDOMAINS=wildcard` and `-e EXTRA_DOMAINS=extradomain.com`, I only get a top-level cert for extradomain.com, it'd be nice if I could get a wildcard for the extra domain too.

**Comment by aptalca** [comment]
Try `-e EXTRA_DOMAINS=extradomain.com,*.extradomain.com` along with the wildcard option. 

It may work

**Comment by homerr** [comment]
Did the above suggestion work @YodaDaCoda

**Comment by YodaDaCoda** [comment]
Apologies for the delay in replying. Yes, the above works great. Thanks for the help.
