### ISSUE TITLE
REQ: Adding geoip2

### ISSUE THREAD

**Issue by gilbN** [linuxserver/docker-letsencrypt#176]
Hi! 

With the geoip legacy database "soon" being deprecated (Jan 2019, and it looks like the last updated version is the March update?) https://dev.maxmind.com/geoip/legacy/geolite/ 
Would it be possible to add the geoip2 https://github.com/leev/ngx_http_geoip2_module ? 

I see there is an alpine package for the C library that is needed for the mmdb files (https://pkgs.alpinelinux.org/package/edge/main/x86/libmaxminddb) (https://github.com/maxmind/libmaxminddb/)

**Comment by aptalca** [comment]
Unfortunately, none of those that you linked to would work for us at the moment.

There is currently no nginx module in the alpine repo that uses geoip2, and the database package you linked to is only used by a sip server application.

I suspect the nginx module packages in the alpine repo will be updated to support geoip2 before the legacy is deprecated. One of those packages was just updated yesterday so they are still being maintained.

**Comment by rix1337** [comment]
Just a heads up @aptalca GeoIP 1 has now been removed and is not available from maxmind anymore.

A switch would be highly appreciated, as soon as it gets available

**Comment by gilbN** [comment]
It's still available on http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz

But https://dev.maxmind.com/geoip/legacy/geolite/ redirects to geolite2

Hopefully the alpine repo will be updated soon.

**Comment by slimshizn** [comment]
Just noticed the 404 error I was getting with this with your script @gilbN . Hope to see it updated soon. Disabling the script for now!

**Comment by aptalca** [comment]
FYI, here's the bug report / feature request @gilbN submitted upstream: https://bugs.alpinelinux.org/issues/9988

**Comment by xthursdayx** [comment]
Based on the response to the above-linked bug report by @gilbN it doesn't seem like the Alpine Linux repo will be updated anytime soon (because of existing dependencies). Their recommendation is to install the libmaxminddb and/or libmaxminddb-dev packages. 

@aptalca I see that above you say that this package is only for sip server application. If there is no way to directly install the libmaxminddb and libmaxminddb-dev packages to either this container and/or the base linuxserver/alpine:3.9 base image would it be possible to install them as a tarball from here: https://github.com/maxmind/libmaxminddb? **Sorry if this is n00b question, I'm still learning how docker containers work internally**

**Comment by gilbN** [comment]
@xthursdayx aptalca has made a PR to add the geoip2 :) 
https://github.com/alpinelinux/aports/pull/6762

**Comment by aptalca** [comment]
If you want something done, do it yourself ;)

Although, they haven't even acknowledged the PR and I see plenty of simple app version update PRs sitting in the queue for days or weeks. . . a bit worrysome

**Comment by aptalca** [comment]
Also, when it is merged, it will appear in the edge repo, then it needs to be backported to 3.9 via yet another PR

**Comment by gilbN** [comment]
Also, For anyone wanting an interim solution while we wait, Cloudflare has geo-blocking and its really simple to setup ;)

**Comment by xthursdayx** [comment]
> Also, For anyone wanting an interim solution while we wait, Cloudflare has geo-blocking and its really simple to setup ;)

I'm actually trying to use GeoIP2 to geographically visualize visits to my website in Grafana's Worldmap-panel rather than geo-block IPs, so I guess I'll keep my eye out for this PR! Thanks to both of you (@aptalca and @gilbN ) for your work on this!
