### ISSUE TITLE
Nextcloud 502 Bad Gateway when setting up proxy 

### ISSUE THREAD

**Issue by virgil-av** [linuxserver/docker-letsencrypt#200]
"Debian GNU/Linux 9 (stretch)
OpenMediaVault 4.1.11

For privacy I will change my subdomain on duckdns to 'removed' consider it as a valid subdomain name

`[
    {
        "Id": "6000a728817a85fa40de2bae699f679ec71378c1e0896f5c43fb8a0a2fbd3803",
        "Created": "2018-09-23T15:07:47.949665418Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 12656,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-09-23T15:07:48.503103014Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:1c8b88e2be5ebfe0d8bb31ffc0aa61a717830fa3e67ed273fb84a9a2a99468cf",
        "ResolvConfPath": "/var/lib/docker/containers/6000a728817a85fa40de2bae699f679ec71378c1e0896f5c43fb8a0a2fbd3803/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/6000a728817a85fa40de2bae699f679ec71378c1e0896f5c43fb8a0a2fbd3803/hostname",
        "HostsPath": "/var/lib/docker/containers/6000a728817a85fa40de2bae699f679ec71378c1e0896f5c43fb8a0a2fbd3803/hosts",
        "LogPath": "/var/lib/docker/containers/6000a728817a85fa40de2bae699f679ec71378c1e0896f5c43fb8a0a2fbd3803/6000a728817a85fa40de2bae699f679ec71378c1e0896f5c43fb8a0a2fbd3803-json.log",
        "Name": "/Letsencrypt",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/AppData/Letsencrypt:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "450"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "90"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "NET_ADMIN"
            ],
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/asound",
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/743591e6513bb1b50ee159db13d1c188345f2f6c7267276b5b377e61b67c9f73-init/diff:/var/lib/docker/overlay2/e206b96bf486e9c95039c3406b5f573bca7914be73d914125018934a0c0510d8/diff:/var/lib/docker/overlay2/8549ea458e166a86bcb2c9a5ad35cace9d3f134fcd33f4b37156a751a053c547/diff:/var/lib/docker/overlay2/34b3c92ca92054dfb36a4a0bd471ebb4bc7f4be7426bfa2c019a999c6e4e6b02/diff:/var/lib/docker/overlay2/26d901213f25939f7422c1aa44ce98978faf8535ad3bf0fd29cbb9ed9546214c/diff:/var/lib/docker/overlay2/1cadaa38f6c47e85193ccb414b168414eb997347592dc8a81a8489a9a0a00dbc/diff:/var/lib/docker/overlay2/a7f5f856b20f6c633a01f8bca6b13bc8bf7154b45303a18a6760d3b44f011c09/diff:/var/lib/docker/overlay2/1644d9bd980493985320bc946594b004324f8b662c48ebe8dabf9173f1cae4ce/diff",
                "MergedDir": "/var/lib/docker/overlay2/743591e6513bb1b50ee159db13d1c188345f2f6c7267276b5b377e61b67c9f73/merged",
                "UpperDir": "/var/lib/docker/overlay2/743591e6513bb1b50ee159db13d1c188345f2f6c7267276b5b377e61b67c9f73/diff",
                "WorkDir": "/var/lib/docker/overlay2/743591e6513bb1b50ee159db13d1c188345f2f6c7267276b5b377e61b67c9f73/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/AppData/Letsencrypt",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "6000a728817a",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "HOME=/root",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DHLEVEL=2048",
                "SUBDOMAINS=removed",
                "URL=duckdns.org",
                "PGID=100",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=2",
                "PS1=root@Vigserver:/$ ",
                "TERM=xterm",
                "PUID=998",
                "ONLY_SUBDOMAINS=true",
                "TZ=Europe/Bucharest",
                "AWS_CONFIG_FILE=/config/dns-conf/route53.ini",
                "EMAIL=myemail@gmail.com",
                "VALIDATION=http"
            ],
            "Cmd": null,
            "Image": "linuxserver/letsencrypt:latest",
            "Volumes": {
                "/config": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "Linuxserver.io version:- 173 Build-date:- September-21-2018-22:11:51-UTC",
                "maintainer": "aptalca",
                "omv_docker_extra_args": "--cap-add=NET_ADMIN --network my-net"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "c674edadb51bcacc252ba0e51316eca6a8942c124d168d154d1ed51cdae1d05e",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "450"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "90"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/c674edadb51b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "cdcfeb7a1a42236be0762a8dedbf9167fcb04e5d37203c534b2b4e999e26aecf",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "09aeca5c1334123085bd8851775ee67210a81ccdbec8a7613301e75cc39c62a7",
                    "EndpointID": "cdcfeb7a1a42236be0762a8dedbf9167fcb04e5d37203c534b2b4e999e26aecf",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:03",
                    "DriverOpts": null
                },
                "my-net": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": [
                        "6000a728817a"
                    ],
                    "NetworkID": "8155fd91054584af6fb3a0b796f7362ef745055cce14f5012e5a28b80d55ed82",
                    "EndpointID": "99d580a2c5f08dd82942fbcced23c291c135c5e01780ace3a52c9cabadccc455",
                    "Gateway": "172.20.0.1",
                    "IPAddress": "172.20.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:14:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]`

`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    998
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=998
PGID=100
TZ=Europe/Bucharest
URL=duckdns.org
SUBDOMAINS=removed
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=true
DHLEVEL=2048
VALIDATION=hhtp
DNSPLUGIN=
EMAIL=myemail@gmail.com
STAGING=

2048 bit DH parameters present
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are:  -d removed.duckdns.org
E-mail address entered: myemail@gmail.com
http validation is selected
Certificate exists; parameters unchanged; attempting renewal
<------------------------------------------------->

<------------------------------------------------->
cronjob running on Sun Sep 23 18:07:49 EEST 2018
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/removed.duckdns.org.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/removed.duckdns.org/fullchain.pem expires on 2018-12-22 (skipped)
No renewals were attempted.
No hooks were run.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[cont-init.d] 50-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
`

Proxy config: 
`
# make sure that your dns has a cname set for nextcloud
# assuming this container is called "letsencrypt", edit your nextcloud container's config
# located at /config/www/nextcloud/config/config.php and add the following lines before the ");":
#  'trusted_proxies' => ['letsencrypt'],
#  'overwrite.cli.url' => 'https://nextcloud.your-domain.com/',
#  'overwritehost' => 'nextcloud.your-domain.com',
#  'overwriteprotocol' => 'https',
#
# Also don't forget to add your domain name to the trusted domains array. It should look somewhat like this:
#  array (
#    0 => '192.168.0.1:444', # This line may look different on your setup, don't modify it.
#    1 => 'nextcloud.your-domain.com',
#  ),

server {
    listen 443 ssl;

    server_name removed.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_nextcloud nextcloud;
        proxy_max_temp_file_size 2048m;
        proxy_pass https://$upstream_nextcloud:443;
    }
}
`

Nextcloudconfig

`
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'instanceid' => 'ocz06uudg28k',
  'passwordsalt' => 'PcPlHabeNoGtbU6f/k4dmrWDqDOiHk',
  'secret' => '9E3JUDCsGCkC+qlL+WInFaZHYATjQjT+bCoAfxjpiIXsiqOz',
  'trusted_domains' =>
  array (
    0 => 'myddns.ddns.net',
    1 => 'removed.duckdns.org',
),
  'overwrite.cli.url' => 'https://removed.duckdns.org',
  'overwritehost' => 'removed.duckdns.org',
  'overwriteprotocol' => 'https',
  'dbtype' => 'mysql',
  'version' => '14.0.0.19',
  'dbname' => 'nextcloud',
  'dbhost' => 'myddns.ddns.net:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'admin',
  'dbpassword' => 'Pass123',
  'installed' => true,
);

`

Something happened in the past few days, as I have configured this on the same server 6 days ago and everything worked fine,  2 days ago I reinstalled the machine and did all the setup again but now doing the exact same thing as before, I hit a brick wall with 502 bad gateway, the moment I save the conf file and restart letsencrypt container it dies, if I stop the container it goes to nextcloud with unsafe https  but it works the moment I enable letsencrypt it hits 502 bad gateway, if I remove the conf file restart it goes to the default  letsencrypt html page.

I did this setup over a dozen times thinking I have missed something, I am starting to doubt that is my setup.

**Comment by aptalca** [comment]
post your docker create/run (or compose yml) for both letsencrypt and nextcloud

When you stop letsencrypt and go to your domain, if you get nextcloud with broken ssl, that means your port forwarding is wrong. port 443 should not be forwarded to the nextcloud container, it should be forwarded to letsencrypt

Also you didn't add letsencrypt as a trusted proxy, which may be the reason for the 502

I suggest you start over and follow the directions closely

**Comment by homerr** [comment]
Closed pending further information.
