### ISSUE TITLE
Multi-architecture

### ISSUE THREAD

**Issue by hijxf** [linuxserver/docker-letsencrypt#206]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I didn't know where to post this, but maybe all the main repos (without architecture prefix) for the Docker images should build out multi-architectures. This would keep all the repos, but possibly make it easier just to reference one type of project on the website and list what it supports. Maybe this was considered before creating the project, but it could be beneficial for people looking through the website.

Thanks,
hijxf

https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/

**Comment by nemchik** [comment]
I believe that's already in the works (although I don't have all the info from the LSIO side). They did just release https://hub.docker.com/r/linuxserver/bazarr/ which is a single repo, multi-arch image using tags. I'm sure other LSIO images will be moved to this method in the future and this specific repo would benefit from that greatly with how often PRs come in 😆 .

**Comment by aptalca** [comment]
Yup, new build system is currently under testing and optimization. All images will move over to new builder and multi arch

**Comment by aptalca** [comment]
In the meantime, this page lists what's available on which platform: https://www.linuxserver.io/our-images

**Comment by hijxf** [comment]
Thanks everyone.
