### ISSUE TITLE
fail2ban logrotate

### ISSUE THREAD

**Issue by LBegnaud** [linuxserver/docker-letsencrypt#208]
Seems like logrotate delaycompress works, but our logs are always in `log/fail2ban/fail2ban.log.1`

i dug around and found that logrotate settings have a postrotate command of

`/usr/bin/fail2ban-client set logtarget /config/log/fail2ban/fail2ban.log`

but that doesn't appear to actually work until also issuing 

`/usr/bin/fail2ban-client flushlogs`

I'm working on monitoring Bans across multiple containers and just need the logs to be in a consistent place.  I didn't include other environment information as I didn't think it's relevant, but I can if you would like

**Comment by aptalca** [comment]
Hmm, it used to work fine before. Thanks for the heads up. We'll fix it in the next build.
