### ISSUE TITLE
Bazarr reverse proxy won't work

### ISSUE THREAD

**Issue by choldi** [linuxserver/docker-letsencrypt#212]
I've configured reverse proxy folder from various services (radarr, sonarr, jackett and bazarr)
radarr, sonarr and jackett work but bazarr don't.

I've changed the URL in bazarr to /bazarr/ (I've tried with /bazarr also) and renamed bazarr.subfolder.conf.sample to bazarr.subfolder.conf

I've restarted bazarr

I get 404 error:

Error: 404 Not Found
Sorry, the requested URL 'https://host/bazarr' caused an error:

Not found: '/bazarr'

OS: debian strech 9.5
Docker version 18.06.1-ce, build e68fc7a
Bazarr v0.6.6

**Comment by aptalca** [comment]
Did you restart letsencrypt?

**Comment by choldi** [comment]
Yes, lot of times

**Comment by aptalca** [comment]
@nemchik can you look into this?

**Comment by nemchik** [comment]
Use this proxy config
https://github.com/linuxserver/docker-letsencrypt/blob/rp/root/defaults/proxy-confs/bazarr.subfolder.conf.sample

In Bazarr settings be sure to use `/bazarr/` for the base url (the trailing slash is important)

**Comment by choldi** [comment]
@nemchik Perfect. Worked like a charm.

**Comment by nemchik** [comment]
I suppose I should PR an adjustment to that config just for the comment on line 1
