### ISSUE TITLE
service replica and certificates

### ISSUE THREAD

**Issue by casper5822** [linuxserver/docker-letsencrypt#214]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Hello,
i have a question about docker service replica for this image:
If i want to have for example 4 nginx replicas: what happens with certbot and certificate?

Does certbot create and change everytime a new certificate ?

How it will be works in this scenario?

**Comment by aptalca** [comment]
I have zero experience with docker swarm and I don't really know how or if the persistent data is synced between nodes. But if it is synced, then the certs will also be synced and as long as there is a valid cert in the `/config` folder, certbot will not attempt to regenerate certs.

If not automatically synced, then each node will maintain their own certs and will renew within 60 days prior to expiration. With multiple active certs for a domain, you'll have to abide by letsencrypt's limits and may get throttled if there are too many requests in a certain period of time.

Keep in mind that you'll also have to automate the port forwarding to make sure the users reach the right node at ports 80 and/or 443

**Comment by casper5822** [comment]
I think that if you have some replica of nginx or you do stop and start, every time certbot will be executed.  I think it also means you will have a lot of certbot running and check the renew time.

**Comment by aptalca** [comment]
certbot does a `renew` during container start and once every night. `renew` means it checks the expiration date of the existing local cert, compares it to the current date and time and if it's not expiring within the next 30 days, it prints a message saying no renew necessary.
