### ISSUE TITLE
new release (181) is broken

### ISSUE THREAD

**Issue by juan11perez** [linuxserver/docker-letsencrypt#230]
watchtower upgraded and the container immediately broke. See container log 
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -,
[cont-init.d] 50-config: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
nginx: [emerg] module "/var/lib/nginx/modules/ndk_http_module.so" version 1014001 instead of 1014000 in /etc/nginx/modules/devel_kit.conf:1,
[services.d] done.,
Server ready,
nginx: [emerg] module "/var/lib/nginx/modules/ndk_http_module.so" version 1014001 instead of 1014000 in /etc/nginx/modules/devel_kit.conf:1,
```
Running Ubuntu 18.04

reversed to version 180 and it's working again.

**Comment by aptalca** [comment]
It seems alpine updated the nginx package in the repo and broke a bunch of nginx modules. Bug reported upstream. Nothing we can do. 

You can either pull the previous version, or disable modules at the top of nginx.conf

**Comment by glassbase** [comment]
Same thing happening to me too

**Comment by aptalca** [comment]
figured out the issue, fix is on the way
there will be a new build shortly

**Comment by aptalca** [comment]
new build is up. Please test and let us know

**Comment by juan11perez** [comment]
pulled the new image.
```
docker inspect -f '{{ index .Config.Labels "build_version" }}' letsencrypt
Linuxserver.io version:- 182 Build-date:- November-08-2018-21:54:46-UTC
```
working well, no errors.

thank  you very much
