### ISSUE TITLE
Cannot switch to duckdns certificate after restarting container using other validation method

### ISSUE THREAD

**Issue by pumbaasdad** [linuxserver/docker-letsencrypt#240]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

At some point after the duckdns validation was released, I pulled and restarted my container that was configured to use http validation.  Today, I updated my docker-compose configuration to use duckdns validation, but, the post to duckdns to update the TXT record failed.  The logs suggested that my `DUCKDNSTOKEN` was incorrect.

I was sure I was doing something wrong, so, I dug through the code.  What I eventually realized was that my `donoteditthisfile.conf` had `DUCKDNSTOKEN` set to `""` (because the last time that file was updated I was using HTTP validation).  Even though `DUCKDNSTOKEN` was correctly set in my environment, when `duckdns-txt` sourced `donoteditthisfile.conf`, it was clearing the token, and as a result, I couldn't update my TXT record.

I worked around by deleting that variable from `donoteeditthisfile.conf`.  After doing that, I was able to successfully validate.  Although this workaround works, this still seems like a bug.  I *think* the solution may be as simple as not sourcing `donoteditthisconfig.conf` in `duckdns-txt`, but, I feel like it must be in there for some reason that I'm not seeing.

**Comment by aptalca** [comment]
Ah, yup, that was a senior moment on my part. That file should contain `ORIGDUCKDNSTOKEN` just like the others for that reason.

We'll get it fixed. 

Thanks for the report.

**Comment by aptalca** [comment]
After merge and new build, the first start will fix the conf file but the variable will still be reset, after second start, it won't be reset anymore.
