### ISSUE TITLE
Run nginx ommands

### ISSUE THREAD

**Issue by digitalap3** [linuxserver/docker-letsencrypt#243]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Thank you for this excellent software.  I am wondering how to run nginx commands inside the container?  I would like to `docker exec -it letsecrypt-container /bin/bash` and then run `nginx -s reload`.

Thank you

**Comment by nemchik** [comment]
You can simply `docker restart letsencrypt`

**Comment by digitalap3** [comment]
True but the command I mentioned requires no restart and simply reloads the configs which is far more convenient and less time consuming when trying to figure out proxy issues.  Also there may be other nginx commands that others find necessary.

**Comment by LBegnaud** [comment]
for what it's worth, when i have to reload configs i check syntax with 

` docker exec <containerName> sh -c "nginx -t -c /config/nginx/nginx.conf"`

Then reload the config via this

`docker exec -it <containerName> s6-svc -h /var/run/s6/services/nginx`

**Comment by digitalap3** [comment]
Thank you that is very helpful.  s6 is an alpine thing if I remember correctly?  I found an executable in /usr/sbin and I had to copy the nginx.pid file from run into run/nginx (after making that directory) and it seems to be working but I haven't fully tested it.

**Comment by Laazarus** [comment]
having the same issue here would be really nice having the possibility to run the normal nginx commands

**Comment by j0nnymoe** [comment]
Commands are above if you want to do this. This isn't something we plan to support.

**Comment by Laazarus** [comment]
Thanks
