### ISSUE TITLE
memcached is constantly incurring disk IO

### ISSUE THREAD

**Issue by jamorin** [linuxserver/docker-letsencrypt#245]
The memcached process is constantly writing to disk, is this supposed to happen?
I noticed this with running `htop` on the host machine and sort by `IO_WRITE_RATE`.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Synology

I don't know too much about memcached but I wish there was a way to disable it.
My ugly fix is to mount an empty directory at /etc/services.d/memcached so the process doesn't start

**Comment by aptalca** [comment]
Hmm, I'll look into it. I thought memcached was supposed to be ram only, so there shouldn't be any write operations. Weird.

**Comment by aptalca** [comment]
Just checked a couple of letsencrypt instances I got and both memcached processes are sitting at 0

**Comment by jamorin** [comment]
> Just checked a couple of letsencrypt instances I got and both memcached processes are sitting at 0

Interesting.

I think the culprit to #190 is Synology + memcached.

memcached is causing the flood of "Failed to set a seccomp profile on a worker thread".

I tested this by running memcached adhoc:

```bash
$ memcached -l 127.0.0.1 -p 51234 -u abc
Failed to set a seccomp profile on a worker thread
```

s6-supervise is probably constantly restarting memcached?

I will close this issue in favor of #190. Thanks for looking into this!
