### ISSUE TITLE
Urbackup-server proxy

### ISSUE THREAD

**Issue by Akruidenberg** [linuxserver/docker-letsencrypt#247]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

It would be nice to access Urbackup with ssl connection. Tried to edit the sonnar examples, but it won't work. Urbackup uses FastCgi. How to get it working?

Urbackup is using 545414 for the web interface, but 41413 for FastCGI.

See the following manual for documentation:

https://www.urbackup.org/administration_manual.html#x1-200004.2

I've used this docker container:

https://hub.docker.com/r/uroni/urbackup-server/

**Comment by azinchen** [comment]
By default, linuxserver/letsencrypt acts as Proxy server for standard web server. So, you need to config linuxserver/letsencrypt to proxy requests to 55414 web interface port (I used this method). As template of proxy config file I used nextcloud.subdomain.conf.sample.

If you would like to use FastCGI, you have to additional web server above 55413 port. As example of web server you may look at https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm

**Comment by Akruidenberg** [comment]
I've pasted the following, but it won't work:

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name backup.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        proxy_max_temp_file_size 2048m;
        proxy_pass http://127.0.0.1:55414;
    }
}

**Comment by j0nnymoe** [comment]
use the container ip or host ip, not 127.0.0.1.

**Comment by Akruidenberg** [comment]
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name backup.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        proxy_max_temp_file_size 2048m;
        proxy_pass https://192.168.77.100:55414;
    }
}

Same problem

**Comment by azinchen** [comment]
> Same problem. I always get "welcome to our server message".
> UPDATE: no progress with proxy_pass http

I prefer to use the same port, 55414.

My docker-compose.yml file
`version: '3'

services:
  urbackup:
    image: uroni/urbackup-server:latest
    restart: always
    ports:
      - 55415:55415/tcp
      - 35623:35623/udp
    volumes:
      - ./volumes/config:/var/urbackup
      - ./volumes/backup:/backups

  letsencrypt:
    image: linuxserver/letsencrypt:latest
    restart: always
    ports:
      - 55414:55414/tcp
    cap_add:
      - net_admin
    environment:
      - EMAIL=***
      - URL=***
      - SUBDOMAINS=urbackup
      - ONLY_SUBDOMAINS=true
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./volumes/letsencrypt:/config
    depends_on:
      - urbackup`

./volumes/letsencrypt/nginx/proxy-confs/urbackup.subdomain.conf file
`server {
    listen 55414 ssl;
    error_page 497 https://$host:$server_port$request_uri;

    server_name urbackup.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_urbackup urbackup;
        proxy_pass http://$upstream_urbackup:55414;
    }
}`

Works Ok on my server.

Do you really need to open urbackup web ui on 443 port? Try to remove "main server block" in ./volumes/letsencrypt/nginx/site-confs/default file or map port in compose file above.

`  letsencrypt:
    ports:
      - 443:55414/tcp`

**Comment by j0nnymoe** [comment]
letsencrypt shouldn't run on anything other than 443. The point of a reverse proxy is to take away the need to use dedicated ports for services.

**Comment by azinchen** [comment]
It works in case of single letsencrypt or when using *.subfolder.conf configs. But how to reuse single 443 port in several letsencrypt instances?

**Comment by azinchen** [comment]
Why I can't use several letsencrypt containers? It works Ok on my server. If you look on my config, I use dns verification method and I don't create certificate for domain root.

Also, the idea of compose file is to create complete application without references to containers outside of compose file.

**Comment by j0nnymoe** [comment]
Because you can't put multiple containers on the same port? Unless you want them on different ports then kinda defeats the purpose of reverse proxying and you might as well punch a hole in the firewall to access your application.

If you already have 1 container running on 443, you can use that to reverse proxy urbackup

**Comment by azinchen** [comment]
Because I prefer to start/stop the whole application by one command, without editing configs and restarting other containers.

**Comment by Akruidenberg** [comment]
I profer my orginal subdomain file. Would like to get Urbackup runnning on port 55414. 
urbackup.x.com
Trief al lot of configurations, but get "welcome"again and again. Other apps works very well. More people that would share an subdomain example?

**Comment by Akruidenberg** [comment]
> 
> 
> > Same problem. I always get "welcome to our server message".
> > UPDATE: no progress with proxy_pass http
> 
> I prefer to use the same port, 55414.
> 
> My docker-compose.yml file
> 
> ```
> version: '3'
> 
> services:
>   urbackup:
>     image: uroni/urbackup-server:latest
>     restart: always
>     ports:
>       - 55415:55415/tcp
>       - 35623:35623/udp
>     volumes:
>       - ./volumes/config:/var/urbackup
>       - ./volumes/backup:/backups
> 
>   letsencrypt:
>     image: linuxserver/letsencrypt:latest
>     restart: always
>     ports:
>       - 55414:55414/tcp
>     cap_add:
>       - net_admin
>     environment:
>       - EMAIL=***
>       - URL=***
>       - SUBDOMAINS=urbackup
>       - ONLY_SUBDOMAINS=true
>       - VALIDATION=dns
>       - DNSPLUGIN=cloudflare
>     volumes:
>       - ./volumes/letsencrypt:/config
>     depends_on:
>       - urbackup
> ```
> 
> /volumes/letsencrypt/nginx/proxy-confs/urbackup.subdomain.conf file
> 
> ```
> server {
>     listen 55414 ssl;
>     error_page 497 https://$host:$server_port$request_uri;
> 
>     server_name urbackup.*;
> 
>     include /config/nginx/ssl.conf;
> 
>     client_max_body_size 0;
> 
>     location / {
>         include /config/nginx/proxy.conf;
>         resolver 127.0.0.11 valid=30s;
>         set $upstream_urbackup urbackup;
>         proxy_pass http://$upstream_urbackup:55414;
>     }
> }
> ```
> 
> Works Ok on my server.
> 
> Do you really need to open urbackup web ui on 443 port? Try to remove "main server block" in ./volumes/letsencrypt/nginx/site-confs/default file or map port in compose file above.
> 
> ```
> letsencrypt:
>   ports:
>     - 443:55414/tcp
> ```

Port 443 is allreally running with my letsencrypt container. How to get it working with anaother port. Urbackup is not running at 55414, thats the the reason why i get al welcome screen.
This is my currect config file:

server {
    listen 443 ssl;
    error_page 497 https://$host:$server_port$request_uri;

    server_name urbackup.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_urbackup urbackup;
        proxy_pass http://$upstream_urbackup:55414;
    }
}

**Comment by Akruidenberg** [comment]
Nobody can helps me?

**Comment by homerr** [comment]
I think you're not getting the idea of reverse proxy. You run the application, it binds to an internal IP (lets say 172.16.1.18) and listens on the documented port.

You then configure letsencrypt to pass traffic through to that internal host. As an example you configure an A record of urbackup.domain.tld and point it to your external IP address. You then access this address from outside of your network (as a test) on port 443, if you have configured letsencrypt container properly (which you should be able to do, with the provided sample confs and the documentation) it will recognise you've hit that host and it will then proxy the request through to the container as you've configured. 

If this is not helpful enough, combined with the advice you've previously received, I would suggest jumping into Discord where live support from any available team members and the community may be of better use to you.
