### ISSUE TITLE
Renewal not happening

### ISSUE THREAD

**Issue by a10kiloham** [linuxserver/docker-letsencrypt#249]
I can see there was a change so the renew no longer happens automatically (https://github.com/linuxserver/docker-letsencrypt/pull/244/commits/69f5181089bc2f9b8a1ebd83bb5ab2310060f4d5). However I left it an hour and nothing ever happened to renew. What's the intended use of this now if renewal isn't possible? Am I meant to add a cron to manually certbot renew?

**Comment by aptalca** [comment]
Renewal attempt happens at 2am every night. That was always the case.

You can force one via `docker exec -it letsencrypt /app/le-renew.sh`

**Comment by a10kiloham** [comment]
Clarifying https://github.com/linuxserver/docker-letsencrypt/pull/251
