### ISSUE TITLE
Move proxy samples to sub-folder

### ISSUE THREAD

**Issue by fonix232** [linuxserver/docker-letsencrypt#252]
Right now editing proxy samples, especially after a container restart, is a massive hassle. Most services will have two sample definitions besides the actually used ones, and editing them from terminal, or even through a remote connection (FTP, SMB, you name it) is not easy.

I'd like to recommend to move all sample files to `/conf/nginx/proxy-confs/samples/` instead of the current `/conf/nginx/proxy-confs/` folder - or at least make it so that if any files exist in that specific folder, the startup copy is skipped (otherwise even if the user manually moves the files to someplace else, the moment the container is restarted the folder is filled with unused stuff again).

**Comment by nemchik** [comment]
The reason the sample files are recreated is if you mess up and delete the files or save bad changes you can simply restart the container to get them back. It's pretty simple on a desktop file browser or FTP client to sort by file type which should simplify the view for you, in command line you can use `ls *.conf` to only show the active configs or `ls *.sample` to see the samples.

If none of that is good enough you can edit `/config/nginx/site-confs/default` and;

- locate `include /config/nginx/proxy-confs/*.subdomain.conf;` and change it to something like `include /config/nginx/proxy-confs/live/*.subdomain.conf;`
- locate `include /config/nginx/proxy-confs/*.subfolder.conf;` and change it to something like `include /config/nginx/proxy-confs/live/*.subfolder.conf;`

And from there you can create that folder and move the configs you wish to actually use into the subfolder and also rename them. You could also relocate this anywhere you like, it does not have to be a subfolder of the proxy-confs folder.

**Comment by aptalca** [comment]
Also, we constantly update existing ones and add new sample configs. That's why they are always copied into that folder, to make sure you always have the most up to date samples (for your convenience).
