### ISSUE TITLE
Add configuration file for ubooquity?

### ISSUE THREAD

**Issue by dmz94** [linuxserver/docker-letsencrypt#261]
Appreciate the work on this container and all your other containers. 

There is not currently a config file for Ubooquity. I searched for one and noticed others are trying to find it as well. I have one that seems to work (if you want to review and use) or probably trivial for you to add one. 

Thanks!

**Comment by CHBMB** [comment]
Closing this as there are now configs for ubooquity.

https://github.com/linuxserver/reverse-proxy-confs/blob/master/ubooquity.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/ubooquity.subdomain.conf.sample
