### ISSUE TITLE
Feature proposal: Additional security configuration

### ISSUE THREAD

**Issue by SloCompTech** [linuxserver/docker-letsencrypt#267]
Would it be possible to create file e.g. `donttrack.proxy.conf` for proxy configuration where would be specifed for robots to not track this site ? And another file e.g. `secure.proxy.conf` to have security hardening configuration to remove headers (X-Powered-by ...), version giveaway ... ?

Thanks

**Comment by aptalca** [comment]
proxy.conf is user editable (under `/config/nginx/`). We provide one with a lowest common denominator set of options that should work for most people and services to get you up and running. Feel free to edit it or create alternate versions and reference them in the location blocks.

For robot tracking, the readme has some basic info under reverse proxy: 
```
If you wish to hide your site from search engine crawlers, you may find it useful to add this configuration line to your site config, 
within the server block, above the line where ssl.conf is included add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive"; 
This will ask Google et al not to index and list your site. 
Be careful with this, as you will eventually be de-listed if you leave this line in on a site you wish to be present on search engines
```

**Comment by SloCompTech** [comment]
Thanks
