### ISSUE TITLE
Dovecot problems, how does /etc/letsencrypt/archive works ?

### ISSUE THREAD

**Issue by SloCompTech** [linuxserver/docker-letsencrypt#268]
Hello,
I have some problems with dovecot, which doesn't like symlinks to certificate files, but wants real files. In this container symlinks link files to real files in archive folder ? Does number on certificate get incremented each time certbot renews cert (cert1.pem -> cert2.pem) ? If thats the case, how could I make simple bash script to just copy those files to fixed location ?

Thanks

**Comment by aptalca** [comment]
Number gets incremented with each renewal, but resets when params are changed and a new cert is retrieved.

Best bet is to look at the symlink and grep the target

**Comment by SloCompTech** [comment]
Thanks
