### ISSUE TITLE
lua not supported on AArch64

### ISSUE THREAD

**Issue by w0ndersp00n** [linuxserver/docker-letsencrypt#269]
I've setup the letsencrypt docker image on my Aarch64 system. After successfully generating the the keys for my system, it's impossible to start nginx due to lua:

`PANIC: unprotected error in call to Lua API (bad light userdata pointer)`

After Googling around, I've learnt that LUA isn't supported (very well at least) on AArch64. Is there any way to disable LUA on this architecture?

I manually deleted the packages `nginx-mod-http-lua` and `nginx-mod-http-lua-upstream` for this image to work on Aarch64.

**Comment by aptalca** [comment]
For now you can map a file to `/etc/cont-init.d/90-config` with the contents:

```
#!/usr/bin/with-contenv bash
apk del nginx-mod-http-lua nginx-mod-http-lua-upstream
```
while we investigate

**Comment by aptalca** [comment]
I just fired up a new letsencrypt instance on aarch64 and after cert generation, nginx started up fine

What is your host environment? OS? Docker version?

**Comment by w0ndersp00n** [comment]
I'm using an Odroid C2 with Amlogic S905 SoC, Armdroid Stretch and Docker 18.09.2

**Comment by aptalca** [comment]
What's the kernel?

**Comment by w0ndersp00n** [comment]
```Linux odroidc2 4.19.20-meson64```

**Comment by aptalca** [comment]
I don't know what to tell you. I tested on a chromebook with debian stretch and kernel 4.19, as well as an s905x with libreelec 9 and kernel 3.14 and they both start up just fine.

Are you using a brand new install? If not try it. You may have some config that is trying to use lua.

**Comment by w0ndersp00n** [comment]
Well, that's interesting. I actually reinstalled it yesterday since I couldn't get it working earlier on ubuntu with kernel 3.14. Maybe it's a difference between the S905 and S905x? 

The workaround with the additional init script works fine, so maybe it should be added to the instructions in case any others would have the same issues?

**Comment by aptalca** [comment]
Alright, I finally have a device with the same error. But unfortunately the evidence doesn't prove conclusive

I have an odroid c2 same as you, but with `Linux odroid 3.16.63-37 #1 SMP PREEMPT Thu Feb 21 14:25:30 -03 2019 aarch64 aarch64 aarch64 GNU/Linux` and Ubuntu bionic and it works just fine.

I also have a pine64 with `Linux pine64 4.19.20-sunxi64 #5.75 SMP Fri Feb 8 10:29:25 CET 2019 aarch64 GNU/Linux` and Armbian Stretch and it has the PANIC

Also, I realize that the s905x I mentioned earlier with Libreelec 9, in fact runs a 32 bit OS even though the device is arm64 so we can scratch that.

So we have 4 devices:

Works:
Odroid C2 (amlogic s905), Bionic, 3.16
Chromebook Plus v1 (Rockchip), Stretch, 4.19

Doesn't work:
Odroid C2 (amlogic s905), Stretch, 4.19
Pine64 (allwinner), Stretch, 4.19

**Comment by XtracT** [comment]
I have the same problem, RK3999 board (rockpro64) :

`Linux rockpro64 5.0.0-1101-ayufan-g41eeb7cd789e #ayufan SMP PREEMPT Fri Mar 8 22:14:59 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
`

I do not know if this info helps though. This issue was also pointed out in the old repo:

https://github.com/linuxserver-archive/docker-letsencrypt-arm64/issues/24

/Xtract

**Comment by iJaffa** [comment]
Also seeing the issue on the Raspberry Pi 3 Model B+ running Ubuntu 19.04 with the latest Docker from the Disco repo.

`Linux rpi3plus 5.0.0-1006-raspi2 #6-Ubuntu SMP Thu Apr 11 18:04:26 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by mrsufgi** [comment]
same on rockpi 4A (aarch64)

**Comment by XtracT** [comment]
This could be closed now. The Lua module has been updated, and now I get this error instead:
https://github.com/linuxserver/docker-letsencrypt/issues/303

But the nginx starts and seems to work normally, unlike this issue, which is good!

BR;

/Xtract

**Comment by CHBMB** [comment]
Thanks @XtracT for updating us.

@w0ndersp00n & @mrsufgi are you guys/girls able to confirm?

**Comment by w0ndersp00n** [comment]
I haven't had the issue regarding lua anymore. I don't know if I have #303, since I do have a VPN connection.

**Comment by aptalca** [comment]
nginx lua mod is having all sorts of issues on alpine 3.9+
I suspect there will be a new lua package. Closing this issue for now.
