### ISSUE TITLE
Add GnuPG to Image 

### ISSUE THREAD

**Issue by tstraus13** [linuxserver/docker-letsencrypt#271]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Hello LinuxServer.io Team,

I was wondering if it would be possible to add the gnupg package to this letsencrypt image. I run roundcube webmail inside this container and there is a plugin for round cube that utilizes the gnupg program to encrypt/decrypt emails. Thanks for your time.

**Comment by aptalca** [comment]
@tstraus13 
First of all, let's confirm that just adding the package works for what you're trying to do.

While the container is running, do the following on your docker host's console:
`docker exec -it letsencrypt apk add --no-cache gnupg`

See if the roundcube plugin works and let us know.

**Comment by tstraus13** [comment]
Sorry I should have stated that I had already tested installing the package and it works when it is installed. The plugin for roundcube that uses it is enigma. Thanks.
