### ISSUE TITLE
GeoIP database discontinued, update to GeoIP2 ?

### ISSUE THREAD

**Issue by SloCompTech** [linuxserver/docker-letsencrypt#273]
Legacy GeoIP databases were discontinued (https://support.maxmind.com/geolite-legacy-discontinuation-notice/). Would it be possible to add `nginx-http-geoip2` module to this image or I need to for this and add to my image ? If I need to create my own image do you have any tips (do I only install module or need to put file in `/etc/nignx/modules`)?

Here are some usefull links:
- https://docs.nginx.com/nginx/admin-guide/dynamic-modules/geoip2/
- https://github.com/leev/ngx_http_geoip2_module
- https://dev.iachieved.it/iachievedit/geoip2-and-nginx/
- https://tech.david-cheong.com/country-blocking-using-nginx-with-geoip2-in-ubuntu-16-04/
- https://medium.com/@karljohnson/geoip-discontinuation-upgrade-to-geoip2-with-nginxon-centos-c2a3dbcf8fd

Thanks

**Comment by nemchik** [comment]
Duplicate of https://github.com/linuxserver/docker-letsencrypt/issues/176

**Comment by SloCompTech** [comment]
Thanks, will close this issue since #176 is closed

**Comment by aptalca** [comment]
Nginx would have to be compiled with that module. It's not a simple addition of a file.

We just have to wait until alpine adds a module for v2 and compiles nginx with it.

**Comment by SloCompTech** [comment]
Thanks for info
