### ISSUE TITLE
Add configuration file for Ghost?

### ISSUE THREAD

**Issue by piraces** [linuxserver/docker-letsencrypt#281]
Awesome work on this container and all your other containers. I'm really happy with them!

There is not currently a config file for [Ghost](https://ghost.org). I searched for one but they don't work well.

Is there a possibility to add a configuration file for this service?

Thanks!

**Comment by aptalca** [comment]
Please open an issue in this repo and we'll track it there: https://github.com/linuxserver/reverse-proxy-confs

Thanks
