### ISSUE TITLE
Place actual keys into the /config/keys folder.

### ISSUE THREAD

**Issue by Ryonez** [linuxserver/docker-letsencrypt#282]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

I'm trying to share the keys folder to a gitlab docker instance. After two weeks of them not working (Issue can be found [here](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/4143)), I've discovered the most of the files in your docker image's keys folder are symlinked. Which means, sharing that folder to other images to keep them up to date just doesn't work, they can't read the files.

Could you please correct this on your end, maybe by keeping proper copies of the files in that folder and updating them as needed? Else I'm having to link each file individually, and then having to change them when they update anyway.

**Comment by aptalca** [comment]
Detailed instructions for sharing keys are in the readme
