### ISSUE TITLE
New Module Request - http_stub_status_module

### ISSUE THREAD

**Issue by xthursdayx** [linuxserver/docker-letsencrypt#284]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Hi folks, just wondering if you could add the http_stub_status_module to this container?

https://nginx.org/en/docs/http/ngx_http_stub_status_module.html

I'm hoping to add some nginx monitoring to my grafana dashboard and this seems like it will be helpful. Thanks!

**Comment by aptalca** [comment]
It seems it's already enabled in our build: https://git.alpinelinux.org/aports/tree/main/nginx/APKBUILD?h=3.9-stable#n187

**Comment by xthursdayx** [comment]
Ah, okay, awesome. Thanks! I didn't see it in the Dockerfile as an installed package so I just assumed it wasn't there.
