### ISSUE TITLE
Subfolder config domain.com/plex/web redirects back to root

### ISSUE THREAD

**Issue by Darkstylo** [linuxserver/docker-letsencrypt#299]
I'm using the default plex.subfolder.conf, and followed the instructions at the top for HOST mode.
The configuration works fine if you access domain.com/plex, which redirects to domain.com/plex/web/index.html

The next time you enter the URL, browsers like Chrome autofills the url to domain.com/plex/web which somehow redirects back to domain.com/web.

Trying the direct approach, I get the follow results:
WORKS: https://domain.com/plex
WORKS: https://domain.com/plex/web/index.html
DOESNT WORK: https://domain.com/plex/web -> rewrites to https://domain.com/web

All other containers provided by LS are working fine behind the Letsencrypt container.

**Comment by tobbenb** [comment]
With chrome filling in the address automatically, you mean that as you start typing, it autofill with domain.com/plex/web and you hit enter?

**Comment by Darkstylo** [comment]
Correct, however the questions remains why this redirection occurs.

**Comment by tobbenb** [comment]
Oh, you are using subfolder.
Have you followed the directions given in the top of the plex.subfolder.conf?
in plex server settings, under network, fill in "Custom server access URLs" with your domain (ie. "https://yourdomain.url/plex:443")

You are not supposed to use domain.com/plex/web as using domain.com/plex redirects to the correct address in the proxy conf.

**Comment by Darkstylo** [comment]
Hi @tobbenb 

> Oh, you are using subfolder.
Have you followed the directions given in the top of the plex.subfolder.conf?
in plex server settings, under network, fill in "Custom server access URLs" with your domain (ie. "https://yourdomain.url/plex:443")

I'm fully aware of the top part in the subfolder.conf, hence why I mentioned it when I raised this issue (see first line). 

> You are not supposed to use domain.com/plex/web as using domain.com/plex redirects to the correct address in the proxy conf.

I understand, however browsers like Chrome will autocomplete once you enter domain.com/plex to domain.com/plex/web

**Comment by tobbenb** [comment]
They will not auto complete unless you have already visited that address before.

**Comment by Darkstylo** [comment]
> They will not auto complete unless you have already visited that address before.

Correct, forgot to mention that.

**Comment by tobbenb** [comment]
So the issue is not with letsencrypt or the proxy-conf, but you having typed in that address before and not removing it from auto complete. This is easily avoided by either deleting the entry in chrome or just not use the suggested address by chrome.
