### ISSUE TITLE
DNS error with proxy to LAN host

### ISSUE THREAD

**Issue by a-jackson** [linuxserver/docker-letsencrypt#301]
Just set this up and it gets the certificates correctly and my subdomain displays the default Welcome to the server page.

I then removed the .sample from the Ombi subdomain config and changed the proxy_pass to be the name of another host on my LAN where it is running.
On restarting the container the page no longer loads at all and if I check the nginx error log inside the container it reports unable to resolve 127.0.0.11:53 

Port 53 suggests a DNS error but the nameserver in the containers resolv.conf is 192.168.1.2 which is my networks DNS server so that is correct.

I am able to curl ombi from inside the container so I'm not sure what the problem is.

This is running on unraid

**Comment by aptalca** [comment]
Post your ombi proxy conf

**Comment by a-jackson** [comment]
```
# make sure that your dns has a cname set for ombi and that your ombi container is n
ot using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name requests.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_ombi triton-dl;
        proxy_pass http://$upstream_ombi:3579;
    }

    # This allows access to the actual api
    location ~ (/ombi)?/api {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_ombi triton-dl;
        proxy_pass http://$upstream_ombi:3579;
   }

    # This allows access to the documentation for the api
    location ~ (/ombi)?/swagger {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_ombi triton-dl;
        proxy_pass http://$upstream_ombi:3579;
   }
   if ($http_referer ~* /ombi) {
       rewrite ^/swagger/(.*) /ombi/swagger/$1? redirect;
   }
}
```

**Comment by nemchik** [comment]
Delete the config you've renamed and modified. The sample will be recreated. Rename the sample again (remove `.sample` from the file name). Find the lines that say `set $upstream_ombi ombi;` (there should be 3 of them) and replace them with `set $upstream_ombi 192.168.1.x;` where `x` at the end is the actual IP of the system where your run ombi. This should also be the IP that you're using to curl.

If you're running letsencrypt and ombi both in containers on the same host then you do not need to modify the proxy config at all after renaming it, just make sure both containers are on the same user defined docker bridge network (the default built in bridge will not work).

**Comment by a-jackson** [comment]
Thanks both. Using IP is working.
