### ISSUE TITLE
Separate certs for each domain

### ISSUE THREAD

**Issue by elforesto** [linuxserver/docker-letsencrypt#302]
The current behavior of the container is to request a certificate for the base URL and append each domain listed in EXTRA_DOMAINS as a Subject Alternative Name in the same cert. This has the unfortunate side effect of linking all of the domains you're proxying together into a single cert which may compromise privacy.
	
The suggested fix would be to separate each domain into a separate request to Let's Encrypt and store them in separate certs. There could be an option to group all subdomains into a single cert to reduce the number of total cert requests.

**Comment by nemchik** [comment]
The nginx config would need to be dynamically adjusted for each cert that would be generated. At the moment all nginx configs use the same cert.

This could be a bit of a chore to maintain.

**Comment by aptalca** [comment]
Duplicate #117

**Comment by adam1010** [comment]
I switched to CaddyServer2 and it works great -- you can setup multiple domains with reverse proxy and Caddy automatically obtains separate certificates for each domain and keeps them up to date.
