### ISSUE TITLE
Reload command looks at missing .pid file

### ISSUE THREAD

**Issue by ericfrederich** [linuxserver/docker-letsencrypt#305]
Running `nginx -s reload` yields the following error.
```
nginx: [error] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
```

It seems there is a file `/run/nginx.pid` (directly in /run, not within another directory).

**Comment by sparklyballs** [comment]
don't reload nginx inside the container. 

restart the docker container itself.

**Comment by ericfrederich** [comment]
Restarting container causes downtime doesn't it?

**Comment by nemchik** [comment]
Not any more than reload would from a practical perspective.

**Comment by troy-virtusense** [comment]
I added `RUN mkdir -p /run/nginx && ln -s /run/nginx.pid /run/nginx/nginx.pid` to my Dockerfile (after FROM linuxserver/letsencrypt and COPY config /config) to fix this warning.

I needed to use `nginx -t` to prevent restarting the container if the config is broken. (I know I probably shouldn't be touching the config myself but I haven't fixed that yet)

The image also doesn't use the default config path, so the full command looks like this:

     docker exec -it my_nginx /usr/sbin/nginx -t -c /config/nginx/nginx.conf && docker restart my_nginx

If the config check fails, it won't restart.

**Comment by troy-virtusense** [comment]
Probably the better declarative way is to rebuild the image, with the config check put inside the Dockerfile or something, and then if it builds successfully, stop the container and recreate it on the new image.

But unfortunately my config and my Let's Encrypt state are in the same volume, so right now recreating the container doesn't recreate my config, and wiping the volume causes me to run up against LE's rate limiting. I'll have to fix that later too.

**Comment by muniter** [comment]
Hello, I really like this container, since allows me to configure nginx any way I want. But I would argue that It would be a simple easy fix to implement this, that way functionality won't be broken.

**Comment by aptalca** [comment]
What functionality? We do not support running manual commands inside the container unless we ask/tell you to.

**Comment by WoLpH** [comment]
> Not any more than reload would from a practical perspective.

That's not true unfortunately.

Using the reload command instead of restarting the docker would actually be useful. With a reload command your websockets remain open and active connections such as downloads won't get killed.

**Comment by Sammus187** [comment]
I also think it would be useful to restart nginx internally. Restarting the container to test different configurations lead to hitting letsencrypt limits, as it requests a new certificate each time.

**Comment by tobbenb** [comment]
The certificate are not renewed on every restart. Only if you change a variable is the certificate renewed, which does not happen if you restart the container.

And if you want to test you can use the STAGING variable and will not hit any limits.
