### ISSUE TITLE
How to I access the _readme file in /config/nginx/proxy_confs

### ISSUE THREAD

**Issue by tlaanemaa** [linuxserver/docker-letsencrypt#306]
In you'r readme you mention a readme about reverse proxy config

> Preset reverse proxy config files are added for popular apps. See the _readme file under /config/nginx/proxy_confs for instructions on how to enable them

I would really like to read that file but after trying everything, I can't figure out a way to get access to it inside the container without spinning up an instance of that container. The reason I don't want to run the container is that it seems to try to get a certificate for me right away, which is is exactly what I want in production but in my development env I don't even have my public port 80 forwarded to me so that fails.

In any case, I think I'm just doing something wrong here. All I want is to read the readme about reverse proxies at `/config/nginx/proxy_confs/_readme` 😄 

Any help is appreciated
Thanks!

**Comment by whithajess** [comment]
@tlaanemaa Seems from the version `20.11.18` they have been moved here: https://github.com/linuxserver/reverse-proxy-confs you could also get there by opening on a started `docker-letsencrypt` container. I will possibly update readme once i figure out what it should be.

**Comment by whithajess** [comment]
Also it has a non standard readme: https://github.com/linuxserver/reverse-proxy-confs/blob/master/_readme

**Comment by aptalca** [comment]
The file @whithajess linked to is the correct one.

Why not set up the container first? You really should set up the letsencrypt part first, get the certs, make sure you can access the placeholder homepage, and then try to set up reverse proxies. Do not try to do it all in one step.

Also, you can do duckdns validation that is free and doesn't require port 80 mapping.

Once the container is set up, all those referenced files will be in the config folder you mapped

**Comment by tlaanemaa** [comment]
Thanks guys. The readme was very helpful in understanding what to do.

Why I don't want to set the container up yet is because I already have the same webpage running in an ubuntu box and Im trying to dockerise it. I don't want to go requesting for new certificates just to get access for the readme.

In general I think it would be helpful if the project's readme referenced to the readme linked here so people could have a peek without having to spin up the container.
