### ISSUE TITLE
 certs could not be renewed

### ISSUE THREAD

**Issue by taobyebye** [linuxserver/docker-letsencrypt#307]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 unRAID

Attempting to renew cert (wiki.banana.de) from /etc/letsencrypt/renewal/wiki.banana.de.conf produced an unexpected error: Problem binding to port 80: Could not bind to IPv4 or IPv6.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/wiki.banana.de/fullchain.pem (failure)

i have changed the real hostname for my secure.
 I didn't change anything on the container. Problem came overnight

**Comment by aptalca** [comment]
Check your port 80 mapping. It's seems like it's not going through to the container

**Comment by aptalca** [comment]
No response
