### ISSUE TITLE
Compatibility with CloudFlare

### ISSUE THREAD

**Issue by scoopydude2002** [linuxserver/docker-letsencrypt#31]
Currently you cannot renew or obtain certicates from LetsEncrypt if you have CloudFlare DNS proxy/CDN enabled. This can be done using the web root method:

https://community.letsencrypt.org/t/how-to-get-a-lets-encrypt-certificate-while-using-cloudflare/6338

Please consider adding this as a fallback after a fail attempt at obtain certicates.

**Comment by aptalca** [comment]
Unfortunately the webroot method doesn't work through port 443
