### ISSUE TITLE
/log/nginx/access.log fills out the hdd

### ISSUE THREAD

**Issue by MnM001** [linuxserver/docker-letsencrypt#311]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 18.04.2 LTS

Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

I have letsencrypt working fine. Same with fail2ban
however it seems there is no logrotate happening.
As I am using NGINX doing lots of reverse proxying the most obvious is /log/nginx/access.log
I have a 6GB hdd for my virtual server and it gets fille in 5 or 6 days by the above log.
Never changed any crontab setting or anything like that.

Can anyone look at this and fix?

Thanks guys.

**Comment by aptalca** [comment]
Log rotate happens weekly: https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/logrotate.d/nginx#L2

You can either modify your nginx.conf to disable logging or put the file elsewhere, or you can map a custom logrotate config file where the rotation is daily or hourly

you can map a custom logrotate conf via `-v /path/to/logrotate/conf:/etc/logrotate.d/nginx` in your docker create
