### ISSUE TITLE
Add brotli support.

### ISSUE THREAD

**Issue by adamradocz** [linuxserver/docker-letsencrypt#319]
Please add bortli support besides gzip.

**Comment by aptalca** [comment]
no brotli module in alpine repo, feel free to PR upstream

**Comment by adamradocz** [comment]
Here is an example: [Brotli added to Official NGINX Alpine Dockerfiles](https://github.com/abevoelker/docker-nginx-alpine-brotli)

**Comment by aptalca** [comment]
We don't compile nginx or any of its modules

**Comment by gilbN** [comment]
@adamradocz there is a pr https://github.com/alpinelinux/aports/pull/6603

**Comment by moranbw** [comment]
Any chance of this happening?

**Comment by aptalca** [comment]
@moranbw https://github.com/linuxserver/docker-letsencrypt/issues/319#issuecomment-497856340
