### ISSUE TITLE
Create password for privkey.pfx

### ISSUE THREAD

**Issue by adamradocz** [linuxserver/docker-letsencrypt#321]
In ASP.NET Core the `ASPNETCORE_Kestrel__Certificates__Default__Password` environment variable can't be an empty string, otherwise, it throws an error. This variable should hold the cryptographic password for the `privkey.pfx`.

I'd like an environment option, where I can pass the password to use as the cryptographic password for generating the key. So we can use the `privkey.pfx` without any issue in ASP.NET Core.

**Comment by aptalca** [comment]
As far as I know, empty string password is different than no password. Do you have documentation showing that .net core cannot handle pfx with no password?

**Comment by adamradocz** [comment]
I tested it.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-letsencrypt/pull/323#issuecomment-512573310
