### ISSUE TITLE
LuaJIT error - cannot refresh

### ISSUE THREAD

**Issue by aram535** [linuxserver/docker-letsencrypt#322]
Related to #303 

# docker run --rm \
  --name=letsencrypt \
  --cap-add=NET_ADMIN \
  -e PUID=1005 \
  -e PGID=1005 \
  -e TZ=America/New_York \
  -e URL=xxx.duckdns.org \
  -e VALIDATION=duckdns \
  -e DUCKDNSTOKEN=xxxx \ 
  -p 443:443 \
  -v /home/homeassist/config/lets_encrypt:/config \
  linuxserver/letsencrypt

New certificate generated; starting nginx
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Server ready
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/5.1/resty/core.lua'
        no file '/usr/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/common/resty/core.lua'
        no file '/usr/share/lua/common/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

The server hangs, have to kill it to get the prompt back.
The "lua" errors are actually NOT showing up in the /var/log/letsencrypt/letsencrypt.log ...  let me know if you need any more logs.

**Comment by aptalca** [comment]
The log just shows that you started the container and some time later you stopped it. No indication of hanging out any other errors (other than the lua ones) in what you posted.

Provide more info like your nginx or proxy configs (whatever you modified) and what you expect vs observe

**Comment by aram535** [comment]
The server simply hangs after "Server ready"... until I stop the container.  Not sure how else to show that.  I left it for about 2 hours and was still sitting there when I checked.  Below are the only files I could find on the container, let me know if I"m missing one.

The only error in nginx.log is that lua error: 
```
root@df3006d772d6:/var/log/nginx# cat error.log 
2019/06/04 01:56:30 [alert] 336#336: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2019/06/04 01:56:30 [error] 336#336: lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/5.1/resty/core.lua'
        no file '/usr/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/common/resty/core.lua'
        no file '/usr/share/lua/common/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')

./config/log/nginx/access.log: Empty
./config/log/nginx/error.log: Empty
./config/log/php/error.log:
[04-Jun-2019 05:56:32] NOTICE: fpm is running, pid 337
[04-Jun-2019 05:56:32] NOTICE: ready to handle connections

**Comment by tobbenb** [comment]
Which hardware are you running this on? Looking at your home folder it looks like an RPI running home assistant.
I think I understand it better now. You are running the container interactively and not the way its described in the Readme. Read the Readme and use the supplied examples to get it running correctly.

**Comment by aram535** [comment]
Linux CentOS host (7.6? latest release, yum updated). 
Docker version 18.09.5, build e8ff056

Home Assistant and letsencrypt are both docker containers, volumes for Home Assistant are mounted on the host.

**Comment by tobbenb** [comment]
The issue is the way you start the container. You clearly haven't read the Readme looking at the docker run command. When you use docker run --rm you will attach to the container and nothing will happen after the lua error, which is harmless. That is why you think the letsencrypt container hung and have to ctrl + c out of it to get back to the command prompt. This is not the way you run a container.

You use the docker create command or compose examples we supply in the Readme and that will create the container and you can start it with `docker run letsencrypt` or the compose command to start the container (Don't know compose).

As a side note, if you installed docker-ce from the centos repos you should remove it and install it using the instructions on [https://docs.docker.com/install/linux/docker-ce/centos/](https://docs.docker.com/install/linux/docker-ce/centos/)

**Comment by aram535** [comment]
Thank you for that, however that isn't how I start the container and it's simply a "demo" to provide a MVP for debugging.  The letsencrypt container is part of the home assistant docker-compose which is a lot more complicated and has a lot of dependencies and such.  There was no point in complicating matters with a complicated compose file.  AFAIK, --rm automatically clean up the container and remove the file system when the container exits and has nothing to do with the running of the container.  The real "issue" here is not that the container hangs, frankly I don't think anyone cares if it stopped or hung.  _The real issue is that the cert is not renewed._ 

Link is appreciated, the docker version on centos is much older, the one installed as the latest version from docker's repo.

**Comment by aram535** [comment]
Ummm why was this closed??

**Comment by j0nnymoe** [comment]
` however that isn't how I start the container` How do you start the container then?

Also, nothing more is supposed to show after it hits `Server ready` so I'm not sure how you've come to the conclusion of this container hanging.

**Comment by aptalca** [comment]
@aram535 are you using "-d" when you start them? If not the container will run in the foreground, which will make you think it's hanging
