### ISSUE TITLE
prestashop.subdomain.conf

### ISSUE THREAD

**Issue by moarf56** [linuxserver/docker-letsencrypt#326]
Hi !!

OS : Debian 8.11
Docker-letsencrypt : Last Version

I try to make a "prestashop.subdomain.conf" for an instance of the CMS Prestashop.
I make this : 

`server {
    listen 443 ssl;
    server_name monsite.*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;
    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_presta monsite;
		proxy_pass http://$upstream_presta:80;
    }
}
`

But I have ths message : 
502 Bad Gateway

The subdomain is : monsite
Container name is : presta
The port inside the presta's container is : 80
The presta container ip is : 172.18.0.5/16
The letsencrypt ip is : 172.18.0.6/16

Anyone have an idee ?

Thx !

**Comment by nemchik** [comment]
Change `set $upstream_presta monsite;` to `set $upstream_presta presta;` and make sure the containers are on the same docker bridge network.

**Comment by moarf56** [comment]
> 
> 
> Change `set $upstream_presta monsite;` to `set $upstream_presta presta;` and make sure the containers are on the same docker bridge network.

Hi :d

I make the change, and new message : 

SSL_ERROR_RX_RECORD_TOO_LONG 

And the adress change with the ip of the server I use whitout letsencrypt : 
https://x.x.x.x:8085

And for the moment I go to prestashop with this adress : 
http://x.x.x.x:8085

**Comment by moarf56** [comment]
Hi !

After lot off test !

Prestashop, speak about a beug when using docker for mac (it's not my case, but...) and I follow the fix, and tha work...
I just add this :

-e
PS_DOMAIN 
PS_SHOP_URL 


So thank you for your help @nemchik
