### ISSUE TITLE
Server address is no longer available

### ISSUE THREAD

**Issue by Rondal895** [linuxserver/docker-letsencrypt#327]
Hallo,
I use linux server / docker-letsencrypt in openmediavault. I use it to run Nextcloud.
I did the same for the installation, as shown in the following videos:

https://www.youtube.com/watch?v=TkjAcp8q0W0

The installation worked so well so far.
For some time, however, the certificate is not renewed.
I then started again a complete reinstall, as shown in the video.

When executing the command "docker logs -f letsencrypt", I got the following result:

Certificate exists; parameters unchanged; starting nginx
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimiza           tions will be disabled and performance will be compromised (see https://github.c           om/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the            OpenResty releases from https://openresty.org/en/download.html)
[services.d] done.
nginx: [error] lua_load_resty_core failed to load the resty.core module from htt           ps://github.com/openresty/lua-resty-core; ensure you are using an OpenResty rele           ase from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.co           re' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/5.1/resty/core.lua'
        no file '/usr/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/common/resty/core.lua'
        no file '/usr/share/lua/common/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
Server ready

**The problem: I can not reach the cloud anymore. If I enter the server address in the web browser, the following result appears:**

Welcome to our server
The website is currently being setup under this address.
For help and support, please contact: me@example.com

**How can I reach my server again?**
I desperately need access to the cloud again.

Thanks in advance for the help

**Comment by aptalca** [comment]
You are reaching the container. It works. That page is the placeholder homepage.

If you need assistance with reverse proxying nextcloud, you can either
1) read the readme
2) read our blog post: https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/
3) or join our discord
