### ISSUE TITLE
Using certs in other containers

### ISSUE THREAD

**Issue by adirgan** [linuxserver/docker-letsencrypt#328]
I have problems wanting to use the certificates in another container, to seem the certificates that are in the / config / keys folder are a direct access to the actual files that are in the container, and the other containers can not open the files when the config directory is mounted in other containers.

**Comment by aptalca** [comment]
They are relative symlinks to the files and the actual files are also under /config

See here for more info: https://github.com/linuxserver/docker-letsencrypt/blob/master/README.md#using-certs-in-other-containers

**Comment by adirgan** [comment]
Unfortunately it does not work, the other containers do not know where the file is and they can not access it according to the instructions of that link

**Comment by aptalca** [comment]
Like I said, they are relatively symlinks so if you do it right, as explained, they are accessible
