### ISSUE TITLE
Allow disabling nginx

### ISSUE THREAD

**Issue by marklagendijk** [linuxserver/docker-letsencrypt#337]
A common use case for this image is to create Letsencrypt certificates which are to be used by a different container.
When `dns` or `duckdns` validation is used in such cases, the nginx server is not needed. However, there is no way to disable it in such cases.

**Comment by nemchik** [comment]
Why not just ignore nginx running? With the default config it takes hardly any resources.

**Comment by marklagendijk** [comment]
If it indeed barely consumes any resources, it should be fine.
