### ISSUE TITLE
Live folder uses symlinks

### ISSUE THREAD

**Issue by marklagendijk** [linuxserver/docker-letsencrypt#338]
Currently the certificates are stored under `/etc/letsencrypt/live/DOMAIN/*.pem`.
However, they are not actually stored there, but symlink to `/etc/letsencrypt/archive/DOMAIN/*1.pem`.
The issue with this is that you need to use a volume for the whole `/etc/letsencrypt`, instead of being able to just mount `/etc/letsencrypt/live/DOMAIN/`. 

Would it be possible to copy the certificates into the `live` folder, instead of symlinking them?

**Comment by marklagendijk** [comment]
Also the documentation is wrong on this point:

> Easier) Mount the letsencrypt config folder in other containers (ie. -v /path-to-le-config:/le-ssl) and in the other containers, use the cert location /le-ssl/keys/letsencrypt/
(More secure) Mount the letsencrypt folder etc/letsencrypt that resides under /config in other containers (ie. -v /path-to-le-config/etc/letsencrypt:/le-ssl) and in the other containers, use the cert location /le-ssl/live/<your.domain.url>/ (This is more secure because the first method shares the entire letsencrypt config folder with other containers, including the www files, whereas the second method only shares the ssl certs)

The `More secure` option will only be possible when the certs are copied, instead of symlinked.

**Comment by aptalca** [comment]
Symlinks are relative, not absolute. Documentation is correct

**Comment by marklagendijk** [comment]
@aptalca thanks for your response. I indeed misread the documentation.
However, my initial question still stands.
In the container that is using the certs, you only need the certs. Therefore it is weird that you have to mount extra things.

**Comment by aptalca** [comment]
The certs and their symlinks are all handled by certbot. We don't create them. The actual certs have specific names that are versioned. If you reference the actual certs in your nginx config, you have to change that reference every time the certs are renewed. Certbot makes sure that the symlinks point to the latest version cert so you can use the symlink without having to update the reference.

**Comment by marklagendijk** [comment]
I understand.
I think I read somewhere that cerbot has a command to export the certifictates.
Would it be an idea to use that? Or would it be relatively too much work?

**Comment by nemchik** [comment]
It already "exports" them, but they are saved to the default location.

You the symlinks point to other files in the letsencrypt config folder, so if you follow the link you will find the true location of the cert and you can't map that folder as a volume in any container you like.

**Comment by 5dao** [comment]
why use symlinks,,,docker not volume

**Comment by 5dao** [comment]
`-v /etc/letsencrypt:/etc/letsencrypt`,,,symlinks ok,aha
or
`/etc/letsencrypt/live/domain/pem.key:/etc/letsencrypt/live/domain/pem.key`

**Comment by aptalca** [comment]
no, that's all wrong

**Comment by 5dao** [comment]
> no, that's all wrong

?,

**Comment by aptalca** [comment]
It's hard to tell what exactly you're trying to do since you just posted a couple of snippets with no context.
However, I can say this, there is no scenario I can think of where what you posted would result in a working setup.

If those snippets are meant to be in your letsencrypt docker run, then 1) you'll be breaking our validation logic, because /etc/letsencrypt is a symlink that points to /config/etc/letsencrypt and 2) the pem file under the live/domain endpoint is itself a symlink so you'll be mapping a symlink

If they are meant to be in the other container, well, that is also not going to work because as above, etc/letsencrypt would be a subfolder of /config, so they would not be at the root of your host

**Comment by 5dao** [comment]
run certbot in host machine,but nginx run in docker,so docker run nginx -v etc/letsencrypt:etc/letsencrypt

**Comment by aptalca** [comment]
ok, well, that has absolutely nothing to do with this image or this github issue

**Comment by gittur** [comment]
perfect! Thankyou very much @5dao!

Such a simple solution!
