### ISSUE TITLE
health check

### ISSUE THREAD

**Issue by frank3427** [linuxserver/docker-letsencrypt#340]
I am looking for a means to get a health check status of the container when it's running correctly, any thoughts on this?

frank

**Comment by aptalca** [comment]
curl the domain? it is a webserver, best way is to see if it's serving the webpages

**Comment by LBegnaud** [comment]
not sure the details of docker health checks, but note that there are conditions that purposely sleep the container where the webserver will not run... Cert creation failure is definitely one of those.

**Comment by aptalca** [comment]
missing environment variables and unsuccessful cert generation will make it sleep, but that's all during container start

**Comment by aptalca** [comment]
no response in 8 days, closing

you can reopen if you want to continue discussion
