### ISSUE TITLE
Nginx PageSpeed

### ISSUE THREAD

**Issue by Kosmatik** [linuxserver/docker-letsencrypt#342]
I have a suggestion to add PageSpeed while you guys are compiling nginx. It optimizes the page server side and requires no html/css/js modification.

https://developers.google.com/speed/

**Comment by tobbenb** [comment]
We do not compile nginx. We use the alpine package repo.

**Comment by aptalca** [comment]
You can submit a request to the upstream alpine repo to add the pagespeed module as a package.

**Comment by Kosmatik** [comment]
I'm not sure these are added as packages. Even the official alpine docker that includes pagespeed compiles nginx.

https://github.com/apache/incubator-pagespeed-ngx/tree/master/docker

**Comment by aptalca** [comment]
Most nginx modules nowadays are dynamic. Meaning, the base nginx app in the alpine repo gets compiled with all possible modules, but the nginx package ships without the module files. The module files are installed as separate packages. Once the module files are added, they are activated.
https://github.com/alpinelinux/aports/blob/master/main/nginx/APKBUILD#L180-L228

**Comment by Kosmatik** [comment]
I'm not sure the main repo would want a pre-apache release in their repo just yet.

The pagespeed back install script can build the module without affecting or compiling nginx again.

I also don't see a way to request a module to be added to aports either.

**Comment by aptalca** [comment]
But it requires that nginx itself is compiled with the module, which is a no go for our image
