### ISSUE TITLE
add ftp module for php

### ISSUE THREAD

**Issue by crgarrett79** [linuxserver/docker-letsencrypt#351]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
Can you provide more info on why you need it?

**Comment by crgarrett79** [comment]
it is needed to use the ftp feature for open game panel.  i host a couple of game servers and want to use open game panel web panel to manage them using this awesome docker to host it on the web with ssl. atleast thats the plan lol

**Comment by aptalca** [comment]
added in #352
