### ISSUE TITLE
Please Update to NGinx v1.17.3 to address HTTP/2 Vulnerabilities

### ISSUE THREAD

**Issue by sydlexius** [linuxserver/docker-letsencrypt#354]
Please refer to[http://nginx.org/en/CHANGES]( http://nginx.org/en/CHANGES) for specific details.

**Comment by aptalca** [comment]
https://pkgs.alpinelinux.org/packages?name=nginx&branch=v3.10&arch=x86_64

**Comment by nemchik** [comment]
@sydlexius the Alpine repo doesn't have the update yet. If it becomes available this image will be rebuilt and include the update, otherwise we may be waiting for an update to the base image (for example Alpine 3.11).
