### ISSUE TITLE
Add cloudflare daemon support

### ISSUE THREAD

**Issue by rcdailey** [linuxserver/docker-letsencrypt#357]
It would be great to have `cloudflared` support in the container. This would allow me to tunnel my sites through Cloudflare, which enables me to use some of their products, such as [Access](https://www.cloudflare.com/products/cloudflare-access/).

It also would enable me to provide outside access to my reverse proxy through their tunnel without exposing port 80/443 outside of the container, and subsequently through my firewall.

Any interest in adding this? Architecturally, I'm assuming it would be running in the same container as NGINX, since it establishes a tunnel to my sites, effectively.

**Comment by aptalca** [comment]
I'm not too familiar with cloudflared. At first glance, it looks like it belongs in a separate container, but I'll give it some thought.

**Comment by lucasff** [comment]
Maybe publish another tag with the support? Maybe not everyone needs it but would be a nice opt-in.

**Comment by rcdailey** [comment]
Since I reported this bug, I learned that Cloudflare's Access service actually doesn't require this daemon. Turns out that all you have to do is enable proxy support for your subdomain, and the Cloudflare servers take care of it.

I'm sure there are still some use-cases for having `cloudflared` along with your reverse proxy, but I can't think of any (Only time I've ever used `cloudflared` was to enable DNS over TLS).

So if you would like, I can close this issue, or we can continue to explore ways that having the cloudflare daemon would be good for other use cases. Up to you. Thanks again for being involved.

**Comment by aptalca** [comment]
Yeah, please go ahead and close it. No plans currently to add that functionality due to:
No aarch64 bins and no alpine packages. Requires too much effort at the moment.
