### ISSUE TITLE
renewal-hooks are not persistent

### ISSUE THREAD

**Issue by jackyaz** [linuxserver/docker-letsencrypt#359]
I'm looking to copy the generated certs to a folder running on the docker host, which needs to be accessed by a non-root user.

I had been looking to use renewal-hooks, but they are lost on container restart.

Can someone suggest a better way to achieve this?

**Comment by nemchik** [comment]
The certs are stored in the `/config` volume which you can store anywhere you want on your host. From there I would make a symlink for your other app to see the certs.

**Comment by CHBMB** [comment]
Either cron or setup symlinks.  Going to close this as we reserve Github for bugs/issues rather than support.  If you want to discuss further ideas then pop by our Discord server or Discourse forum.

**Comment by jackyaz** [comment]
Thanks, will do. It'd be nice if we can make use of certbot's hooks in this container though :)
