### ISSUE TITLE
Webserver doesn't start

### ISSUE THREAD

**Issue by proofrock** [linuxserver/docker-letsencrypt#364]
Hi,
  first thing, thanks for all your work! I am trying to run the container, using the following commandline (under Ubuntu 1910 beta).

`docker create --name=letsencrypt -e PUID=1000 -e PGID=1000 -e TZ=Europe/Rome -e URL=mydomain.com -e VALIDATION=http -e EMAIL=myemail@gmail.com -p 443:443 -p 80:80 -v /home/mano/dockerEnv/letsencrypt:/config --restart unless-stopped linuxserver/letsencrypt`

nothing is running on 443 and 80; the domain resolves to the IP address, and they are forwarded on the proxy. The container installs and when I start it I notice two things:

1. the files in the config dir are property of root (is this normal?)
1. ports 443 and80 are still not responding

So, the server fails with:

```
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: mydomain.com
   Type:   connection
   Detail: Fetching
   http://mydomain.com/.well-known/acme-challenge/pIJ6eBcrPmNC3GJrK5Yelm3po1YiJTuDXSYwN2kkqJM:
   Timeout during connect (likely firewall problem)
```

But to me it doesn't seem a firewall problem, because the ports are closed so that seems to me the reason. If I connect via bash, it seems that nginx is not running:

```
root@1e8be574370e:/# ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   30 root      0:00 foreground  if   /etc/s6/init/init-stage2-redirfd   foreground    if     if      s6-echo      -n      --      [s6-init] making user provided files available at /var/run/s6/etc...          foreground      ba
   31 root      0:00 s6-supervise s6-fdholderd
   44 root      0:00 if  /etc/s6/init/init-stage2-redirfd  foreground   if    if     s6-echo     -n     --     [s6-init] making user provided files available at /var/run/s6/etc...        foreground     backtick     -n     S6_RU
   45 root      0:00 foreground  if   if    s6-echo    -n    --    [s6-init] making user provided files available at /var/run/s6/etc...      foreground    backtick    -n    S6_RUNTIME_PROFILE     printcontenv     S6_RUNTIME_PRO
   51 root      0:00 if  if  -t   s6-test   -d   /var/run/s6/etc/cont-init.d    if   s6-echo   [cont-init.d] executing container initialization scripts...    if   pipeline    s6-ls    -0    --    /var/run/s6/etc/cont-init.d
  208 root      0:00 if  pipeline   s6-ls   -0   --   /var/run/s6/etc/cont-init.d    pipeline   s6-sort   -0   --    forstdin  -o  0  -0  --  i  importas  -u  i  i  if   s6-echo   --   [cont-init.d] ${i}: executing...     foreg
  211 root      0:00 forstdin -o 0 -0 -- i importas -u i i if  s6-echo  --  [cont-init.d] ${i}: executing...   foreground  /var/run/s6/etc/cont-init.d/${i}  importas -u ? ? if  s6-echo  --  [cont-init.d] ${i}: exited ${?}.  ife
  212 root      0:00 [s6-ls]
  213 root      0:00 [s6-sort]
  251 root      0:00 foreground  /var/run/s6/etc/cont-init.d/50-config  importas -u ? ? if  s6-echo  --  [cont-init.d] 50-config: exited ${?}.  ifelse  s6-test  2  -eq  0   exit  0  exit ${?}
  253 root      0:00 bash /var/run/s6/etc/cont-init.d/50-config
  302 root      0:00 sleep infinity
  353 root      0:00 /bin/bash
  365 root      0:00 ps aux
```

And in the config directory, there aren't log files

```
mano@arale3:~/dockerEnv/letsencrypt/log$ tree
.
|--- fail2ban
|--- letsencrypt
|--- nginx
\--- php

4 directories, 0 files
```

What could be happening? Is there something else I could check?

**Comment by aptalca** [comment]
Your validation failed. You need to fix that.

Nginx doesn't start until certs are generated successfully.

**Comment by proofrock** [comment]
Thanks for answering. Can you point to a resource that explains how to perform validation, or which validation should I use? I thought that I need to use `http` validation, as per your documentation...

```
For http validation, port 80 on the internet side of the router should be forwarded to this container's port 80
```

...but if nginx doesn't start, this is not possible. What should I use? Is there, like, a tutorial? I'm using a domain that I actually bought, not duckdns or cloudflare.

Thanks again!

**Comment by j0nnymoe** [comment]
To me, it seems like your firewall hasn't got the ports open correctly which is causing the timeout issue when the validation is happening.

**Comment by proofrock** [comment]
Yes, it was the first thing I checked, but from behind the firewall (the same machine as the docker container) a telnet to those ports fails, and nginx seems not started (see the `ps` logs above).

**Comment by j0nnymoe** [comment]
nginx doesn't need to be started for the validation to work. Certbot within the container deals with that.

We have a tutorial here on how to use the container: https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/ but seeing you're having a timeout error, I would say you've got a network issue.

**Comment by proofrock** [comment]
Thanks! I'll try to verify everything all over again and let you know.

**Comment by proofrock** [comment]
Thank you for the tutorial. running `docker network create lsio` as reported there, and then adding `--net=lsio` did the trick. Can I close the issue?
