### ISSUE TITLE
Add RADIUS authentification

### ISSUE THREAD

**Issue by caillou** [linuxserver/docker-letsencrypt#367]
My Docker host currently runs behind a Unifi USG router.

The USG router offers a Radius authentication server, which is used by the VPN server and exposed to the LAN.

It would make user management much easier, if I could enable Radius auth within a proxy conf file the way it is currently possible with `ldap`.

I found the following `nginx` module: https://github.com/qudreams/nginx-http-radius-module

These would be the necessary steps to get the module running:

1. Compile the [`libmyradclient`](https://github.com/qudreams/libmyradclient) firstly. 
2. Compile nginx-http-radius-module into nginx:
   ` ./configure --add-module=src/nginx-http-radius-module`
   `make`
    `make install`
3. Modify the configuration files.

This leaves one question open: Do you consider Radius authentication to be in the scope of this Docker image?

If not, what would be a viable alternative?

**Comment by aptalca** [comment]
We don't compile nginx. If there is no packaged module for it in alpine, we won't add it.

**Comment by caillou** [comment]
@aptalca thanks for your quick reply. I am closing this issue and will try to figure out how to get such a package made available.

Could you maybe pin point me to a direction? I am I developer with little understanding of the dev-ops world.

I see the following options:

* Try to get the needed packages into Alpine.
* Find another reverse-proxy and put it behind (or in front?) of the `letsencrypt` reverse-proxy.

**Comment by aptalca** [comment]
@caillou 
The most straightforward way is to get it added to alpine repo. Here's a list of nginx and its package modules for the stable repo: https://pkgs.alpinelinux.org/packages?name=nginx*&branch=v3.10&arch=x86_64

Here's the APKBUILD of nginx and its modules: https://git.alpinelinux.org/aports/tree/main/nginx/APKBUILD?h=3.10-stable

As you can see, the same APKBUILD is responsible for the nginx compile and all its dynamic modules. 

The first PR would add it to the master branch, which would be the edge repo. Then you can do a backport into the 3.10 branch to get it into the latest stable, which our image pulls from.

Our ldap implementation was a little different, it didn't need an nginx module compiled. Instead, it uses an external translator python daemon which we run in a separate image.

**Comment by LBegnaud** [comment]
I would highly suggest using an oauth provider with the `auth_request` directive. We use [oauth2_proxy](https://github.com/pusher/oauth2_proxy) but it looks like this [vouch-proxy](https://github.com/vouch/vouch-proxy) might be a bit more mature/user friendly. We run the docker container on the same docker network as this project and the `auth_request` directive points directly to the oauth container.

AFAIK ldap and radius prompt via http basic auth and if you use multiple FQDNs behind your revproxy that'll get tiring real fast. These oauth methods are essentially SSO and the workflow is so smooth.
