### ISSUE TITLE
Dev mode for running image locally?

### ISSUE THREAD

**Issue by Stickerpants** [linuxserver/docker-letsencrypt#381]
Ideally, I'd like to be able to test that my container setup works on my local machine before I push it to the server, without having to actually complete the letsencrypt challenge, for these reasons:

* My prod domain doesn't point to my local IP
* My local IP will change depending on where I'm working
* Often, I'm behind networks that can't expose the right ports for the challenge to pass, even if I point my DNS records at my current IP address.

Maybe this already exists, but I'd love to an environment variable that allows NGINX to start even if letsencrypt fails. Alternatively, maybe it can avoid running the letsencrypt portion at all.

**Note:** I'm aware of the `STAGING` flag, but it's not what I'm looking for.

If this doesn't currently exist, could I suggest it be added as a feature? Thank you!

**Comment by tobbenb** [comment]
If it's the nginx setup you want to test, why not test it using our nginx container?
As far as I know, it's this container without the letsencrypt part.

**Comment by Stickerpants** [comment]
That's a good idea, I'll have a look at that.

I try to change as little as possible between prod and dev, but given that
it's the same base image it might be sufficient for my needs.

Thanks!

**Comment by aptalca** [comment]
The only differences between letsencrypt and nginx are the letsencrypt bits, reverse proxy confs and fail2ban. Everything else should be the same.

For my dev environment, I use a duckdns domain with duckdns validation. It doesn't require any port forwards as it does dns auth, and you can easily set the hosts file for it on your dev machine that points to the internal IP.

**Comment by Stickerpants** [comment]
I took a look at the nginx base image, and it doesn't seem like it'll be an easy drop-in replacement for my use-case, as I'm using this image as the reverse proxy for an express backend.

**Comment by aptalca** [comment]
Starting nginx without certs is not simple because certs (symlinks to certs) are defined in the confs and without them, nginx refuses to start.

Your best bet is to use some form of dns validation (duckdns being the easiest one) to just get the certs. Then you can access your test server via local IP (browser will complain about insecurity but it will still access).

Alternatively, you can set your hosts file or your local dns to set the local IP to the domain the cert is for, and you'll be testing it without any browser warnings.

All server names used in the proxy confs are wildcard and it shouldn't make a difference whether your production and test servers use different domains as long as the subdomains are the same

**Comment by adabru** [comment]
I added my domain and subdomains to /etc/hosts and created a self-signed certificate:

```bash
DOMAIN=example.com
VOLUME=/path/to/my/letsencrypt/volume
sudo mkdir -p $VOLUME/etc/letsencrypt/live/$DOMAIN
sudo openssl req -x509 -newkey rsa:4096 \
  -keyout $VOLUME/etc/letsencrypt/live/$DOMAIN/privkey.pem \
  -out $VOLUME/etc/letsencrypt/live/$DOMAIN/fullchain.pem \
  -nodes -days 30 -subj "/C=DE/CN=$DOMAIN;www.$DOMAIN/O=LUG"
```

After that the letsencrypt can be started as on production. It will detect the existing certificate and not recreate it. Of course you will get the browser warning but that is not a problem for me. In my opinion it would still be nice to have a flag that will make the letsencrypt container handle a local dev setup.

**Comment by aptalca** [comment]
Just use the nginx image since the main difference in the lack of cert generation

**Comment by adabru** [comment]
Thanks for the suggestion, for most use cases the nginx image will probably be fine. But my setup includes overwriting the default `/home/www-letsencrypt/nginx/site-confs/default` from the letsencrypt container. And this file is not compatible with the default nginx image configuration.
Furthermore I use a docker-compose.yml and I don't know how I would incorporate the nginx image without loosing the possibility to run the same `sudo -E docker-compose up -d` command on both production and dev. The setup should be as simple as possible.
