### ISSUE TITLE
Cannot configure LetsEncyrpt - Multiple Errors Occur 

### ISSUE THREAD

**Issue by RFBomb** [linuxserver/docker-letsencrypt#388]
#Expected Behavior
Certificate is made  and everything functions fine

## Current Behavior

 - Container errors out when attempting to renew certificate.
 - Unable to use subdomains due to DH Parameter fault
- Logs are saved to "/var/log/letsencrypt/letsencrypt.log" - Not /config/log/letsencrypt, making them unable to be viewed. 
 -- Mapping "      - /sharedfolders/DockerConfigs/LetsEncrypt/log/letsencrypt:/var/log/letsencrypt/" to a volume allows this to actually get the log. This could be solved with a symlink within the dockerfile though.

## Steps to Reproduce

I have included my compose text that I am using within portainer. 
 - The DH parameter error faults when no subdomains are used, and is only using the 'nextcloud' subfolder. 
 - I have modified the 'proxy_max_temp_file_size' line to go from 2048m to 1024m, because when having it set to 2048m I was getting errors noted in the error file '2048' (see attached).
[NextCloud_Subfolder_2048-Error.txt](https://github.com/linuxserver/docker-letsencrypt/files/3998704/NextCloud_Subfolder_2048-Error.txt)

 - Setting it to 1024m cleared that error, but results in the error log noted in the 'DH-Error' file.
[LetsEncrypt_DH-Error.txt](https://github.com/linuxserver/docker-letsencrypt/files/3998685/LetsEncrypt_DH-Error.txt)

Changing the configuration (such as 'URL' results in a log like this, filled with python errors.
[ChangeConfigError.txt](https://github.com/linuxserver/docker-letsencrypt/files/3998701/ChangeConfigError.txt)

I am attaching another stack running nextcloud to this stack's network. Thus far, I have been unable to connect to nextcloud using the subdomain or the subfolder options, and following the instructions provided. 

## Environment
OS - Raspian W/ OMV 5 + Portainer
CPU - Raspberry Pi 4
Docker was installed using OMV 5's GUI. Other containers run fine, it is an issue with this container.

## Command used to create docker container (run/create/compose/screenshot)
See attached compose file.  Note: I have some stuff commented out in the file due to experimenting with it to try and get it to work, but nothing has proved successful. 
[LetsEncyrpt-Compose.txt](https://github.com/linuxserver/docker-letsencrypt/files/3998687/LetsEncyrpt-Compose.txt)

## Docker logs
See attached logs.

**Comment by tobbenb** [comment]
Use only a comma in the subdomain variable instead of not including it and see if that fixes things.

**Comment by RFBomb** [comment]
> 
> 
> Use only a comma in the subdomain variable instead of not including it and see if that fixes things.

That results in this error:
`
An unexpected error occurred:
There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: rfbomb.mynetgear.com: see https://letsencrypt.org/docs/rate-limits/
`
as well as all  the python errors >> /usr/lib/python3.8/site-packages/CloudFlare/cloudflare.py:89: SyntaxWarning

**Comment by RFBomb** [comment]
Ok so after a bunch of attempts at restarting the container, apparently I created too many certificates (none of which resulted in a working container). That promped the error log to tell me to check out this site: https://letsencrypt.org/docs/rate-limits/

So, per the website I set 'Staging = true' because this is effectively my test environment.  Then this was the last few lines of the startup log, but the subfolders worked!
```
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Server Ready
```

Something is wrong and I don't think it is anything that I am doing. Something is different from production vs staging on the LetsEncrypt side of things is the only thing I can think of, based on this result.

**Comment by aptalca** [comment]
DH param error is because you stopped/killed the container while it was generating the DH params file. It can take a very long time on slow hw like the pi. In your case, you ended up with an empty file that nginx doesn't like. Delete that and restart the container, let it generate it before you kill it.

No idea about the proxy max file size error

See here for the syntax warnings: https://github.com/linuxserver/docker-letsencrypt/issues/400

**Comment by aptalca** [comment]
Been a while. Closing this. Feel free to reopen if still having issues
