### ISSUE TITLE
Error getting php file through reverse proxy

### ISSUE THREAD

**Issue by Hughlander** [linuxserver/docker-letsencrypt#39]
I'm using this instance for some reverse proxies.  One of them is a PHP page (The Linuxserver's COPS docker container.)  However the location was redirected to the PHP support on the local server.

My location:
<pre>        location /books {
                rewrite ^/books(/.*)$ $1 break;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://192.168.86.100:9000;
        }</pre>

Included fpm support
<pre>        location ~ \.php$ {
               fastcgi_split_path_info ^(.+\.php)(/.+)$;
               # With php7-cgi alone:
               fastcgi_pass 127.0.0.1:9000;
               # With php7-fpm:
               #fastcgi_pass unix:/var/run/php7-fpm.sock;
               fastcgi_index index.php;
               include /etc/nginx/fastcgi_params;
        }</pre>

Commenting out that location allows COPS to work.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 14.04.5

docker run --restart=always -d --privileged --name=nginx -v nginx_config:/config -v htpasswd:/htpasswd -e EMAIL=**email**t -e URL=**domain** -e SUBDOMAINS=**hostlist** -p 443:443 -e TZ=PST8PDT7  linuxserver/letsencrypt

nginx's error.log:
2017/03/18 22:04:57 [error] 323#323: *1037 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.86.1, server: _, request: "GET /books/getJSON.php?complete=1&_=1489899896685 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "**hostname**", referrer: "https://**hostname**/books/"

**Comment by aptalca** [comment]
Change the location to `^ /books` otherwise all php files will be sent to the internal php processor rather than to the cops container because the `~ \.php$` location is a more exact match

**Comment by Hughlander** [comment]
Thank you can close as me being too inexperienced with the matching engine then.
