### ISSUE TITLE
Request more API providers for DNS verification.

### ISSUE THREAD

**Issue by GitJamz** [linuxserver/docker-letsencrypt#395]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hi,
I would love to be able to use other DNS verification providers like what acme.sh does. Is it possible to add? Or can you maybe fix this yourself someway using the resources from acme.sh ?
Thanks!

**Comment by aptalca** [comment]
We use the official client certbot and its dns plugins. Some folks have been PR'ing 3rd party plugins lately. Feel free to submit a PR.
