### ISSUE TITLE
Problems with Nextcloud as subfolder

### ISSUE THREAD

**Issue by blackerking** [linuxserver/docker-letsencrypt#396]
After following your Guide on your Blog I've succesfully hosted a server.
Suddenly nextcloud doesn't work as aspected.
I've tried to install it into a subfolder but the page is not complete loaded.
Firefox console told me the error:

All files and scripts stored inside some subfolder are not loaded.
DOMAINNAME.NET/CORE/js/files/....

Expected:
DOMAINNAME.NET/nextcloud/core/js/files/....

**Comment by aptalca** [comment]
GitHub issues is only for bugs. For support requests, please use discord or the forum
