### ISSUE TITLE
Include Domainnameshop DNS Authenticator Plugin

### ISSUE THREAD

**Issue by norsemanGrey** [linuxserver/docker-letsencrypt#399]
The domain registrar [Domainnameshop / Domeneshop](https://domainname.shop/) Domeneshop has made a DNS authentication plugin for Certbot (https://github.com/domeneshop/certbot-dns-domeneshop). It would be great if support for this could be included in your build.

**Comment by aptalca** [comment]
@norsemanGrey we have a PR for it. Can you please test and let us know that it works?
In unraid container settings, just replace the repository field with the following: `lspipepr/letsencrypt:1.0.0-pkg-7fd52048-pr-401` and it should pull the test image.

Then you can put in `domeneshop` as the DNS plugin. After first start, you'll have to edit the file `/config/dns-conf/domeneshop.ini` to input your credentials and restart the container.

Once you confirm it works, we'll merge the PR.

Thanks

**Comment by norsemanGrey** [comment]
That was fast! I'll try to test it. Could I ask what you mean by "unraid container settings"?

**Comment by aptalca** [comment]
@norsemanGrey click on edit container in unraid gui
