### ISSUE TITLE
Large reverse proxy files truncated

### ISSUE THREAD

**Issue by Hughlander** [linuxserver/docker-letsencrypt#40]
If you have a large response such as a huge JSON file coming over a reverse proxy, it will be truncated unless you modify the proxy_max_temp_file_size such as disabling it completely:

proxy_max_temp_file_size 0;

The error indicated in the logs would be along the lines of:
2017/03/19 18:42:56 [crit] 322#322: *919 open() "/var/lib/nginx/tmp/proxy/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 192.168.86.1, server: _, request: "GET /gui/js/lib/jquery-ui.js HTTP/1.1", upstream: "http://192.168.86.100:8888/gui/js/lib/jquery-ui.js", host: "edge.thebigwave.net", referrer: "https://**hostname**/gui/"

**Comment by aptalca** [comment]
All the proxy buffer options can be set through modifying the config files
