### ISSUE TITLE
Adding new certbot plugin

### ISSUE THREAD

**Issue by stefanelul2000** [linuxserver/docker-letsencrypt#404]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I would like to know if it is possible to add a new certbot plugin, in this case the cpanel plugin.
You can find it at the following links:
https://pypi.org/project/certbot-dns-cpanel/
https://github.com/badjware/certbot-dns-cpanel

Thanks in advance

**Comment by aptalca** [comment]
@stefanelul2000 we have a test build for this. Can you test it and let us know?
Use the same variables as listed in the readme, set `DNSPLUGIN` to `cpanel` and use the following image: `lspipepr/letsencrypt:1.1.0-pkg-00500869-pr-405` instead of `linuxserver/letsencrypt`
