### ISSUE TITLE
certbot upgrade?

### ISSUE THREAD

**Issue by altano** [linuxserver/docker-letsencrypt#407]
Can this image be rebuilt with the latest version of certbot? I'm using Cloudflare which released support for granular tokens. Support was [merged into certbot:master](https://github.com/certbot/certbot/pull/7583) 4 days ago and I'd like to have this functionality :)

I know it isn't there yet because specifying `dns_cloudflare_api_token` instead of `dns_cloudflare_api_key` in cloudflare.ini results in this error:

> Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API key?),
Missing property in credentials configuration file /config/dns-conf/cloudflare.ini:,
>
> Property "dns_cloudflare_api_key" not found (should be API key for Cloudflare account, obtained from https://dash.cloudflare.com/profile/api-tokens).,
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.

Thanks for the excellent image!

EDIT: I may have jumped the gun. It looks like this won't be released until [cerbot 1.2.0](https://github.com/certbot/certbot/milestone/81) is released, currently slated for Feb 4th. I'm not sure I'm reading this correctly though.

**Comment by j0nnymoe** [comment]
Once they push the updated version to pip then our container will get updated.

**Comment by jmooo** [comment]
https://launchpad.net/~certbot/+archive/ubuntu/certbot

It also appears the latest version of certbot on the official certbot PPA is 0.3.1? For ubuntu should we be using a different method to update the app/plugins than the official certbot docs recommend to get these latest updates?

**Comment by aptalca** [comment]
?? I don't follow. The latest certbot is 1.2.0 and our latest image has that

**Comment by jmooo** [comment]
sorry @aptalca posted this to the wrong place, deleted my comment above and feel free to delete this one :)
