### ISSUE TITLE
Option to disable nginx and other services

### ISSUE THREAD

**Issue by Dima-Dim** [linuxserver/docker-letsencrypt#409]
Why start services and keep them turned on all the time if the container is used only for obtaining certificates and the method of validation using DNS?

**Comment by aptalca** [comment]
I suggest you start with the readme :wink:

**Comment by Dima-Dim** [comment]
@aptalca  Yes, I disabled port forwarding and replaced nginx.conf, but is this the right way to solve such a problem?

**Comment by aptalca** [comment]
What problem? I was trying to say that you are confused about the purpose of this image.

From the readme: `sets up an Nginx webserver and reverse proxy with php support and a built-in letsencrypt client that automates free SSL server certificate generation and renewal processes. It also contains fail2ban for intrusion prevention.`

This is a full fledged web server with all of that built-in. It's not just a cert generator. Nginx isn't even used for validating certs. Nginx is the web server for user content.

**Comment by Dima-Dim** [comment]
Sorry! Apparently I took the name of the container too literally docker-letsencrypt :)

**Comment by aptalca** [comment]
No worries 👍
