### ISSUE TITLE
php-zip 

### ISSUE THREAD

**Issue by richowen** [linuxserver/docker-letsencrypt#41]
any chance we can get php-zip added to the containter, im using this with organizr and auto update itsnt working, thanks

**Comment by sparklyballs** [comment]
we have an organizr image

https://github.com/linuxserver/docker-organizr

**Comment by richowen** [comment]
yeh but I already have letsencrypt running on 443 and I want everything to go through there, can i install php-zip manually to letsencrypt?

**Comment by sparklyballs** [comment]
it doesn't matter what port it runs on, map to any available port and reverse proxy it through the letsencrypt container.
