### ISSUE TITLE
PHP mod request

### ISSUE THREAD

**Issue by sgt-spike** [linuxserver/docker-letsencrypt#410]
I would like to request the php mod getID3 (http://getid3.sourceforge.net/).  This allows the viewing of media files'(eg mp4) metadata.  I would use it to update a database with the names of my media files stored on my server

Thanks in advance

**Comment by aptalca** [comment]
It looks like this is just a collection of php scripts you host on your server, and not a php module (correct me if I'm wrong).

**Comment by sgt-spike** [comment]
Yes, I asked before really looking into it.  My apologies, I assumed prematurely.

**Comment by aptalca** [comment]
No worries, you should be able to pull those files and put them under the config folder, perhaps something like `/config/www-getid3/` and then create a new server block based on the example in the site config, and point the root directive to that folder
