### ISSUE TITLE
How to fix proxy_headers_hash_max_size?

### ISSUE THREAD

**Issue by C8opmBM** [linuxserver/docker-letsencrypt#415]
How do I fix this warning?

Using latest stable Openmediavault 4.1.34 Arrakis with 4.19.0 linux kernel.

Here are the warn/error logs

> New certificate generated; starting nginx
> [cont-init.d] 50-config: exited 0.
> [cont-init.d] 99-custom-files: executing...
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size

No entry in the proxy.config with proxy_headers_hash_max_size. Should I add it myself?

Also this error referenced here: https://github.com/linuxserver/docker-letsencrypt/issues/303
But for this I understand it will be addressed when the upstream fixes it.

> nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
> nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
> 	no field package.preload['resty.core']
> 	no file './resty/core.lua'
> 	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
> 	no file '/usr/local/share/lua/5.1/resty/core.lua'
> 	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
> 	no file '/usr/share/lua/5.1/resty/core.lua'
> 	no file '/usr/share/lua/5.1/resty/core/init.lua'
> 	no file '/usr/share/lua/common/resty/core.lua'
> 	no file '/usr/share/lua/common/resty/core/init.lua'
> 	no file './resty/core.so'
> 	no file '/usr/local/lib/lua/5.1/resty/core.so'
> 	no file '/usr/lib/lua/5.1/resty/core.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'
> 	no file './resty.so'
> 	no file '/usr/local/lib/lua/5.1/resty.so'
> 	no file '/usr/lib/lua/5.1/resty.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so')
> Server ready

Thanks!

**Comment by aptalca** [comment]
You're likely using old nginx confs. If you haven't modified them, delete `proxy.conf` and `nginx.conf` in your config folder and restart the container
