### ISSUE TITLE
How to force renewal?

### ISSUE THREAD

**Issue by jwillmer** [linuxserver/docker-letsencrypt#416]
Since some certificates get invalidated today I would like to force a renewal.

**Comment by jwillmer** [comment]
- Login: ` docker exec -it letsencrypt /bin/bash`
- Renew: `certbot renew --force-renewal`
- Exit: `exit`

**Comment by aptalca** [comment]
FYI, we do not support running commands manually inside the container

**Comment by LBegnaud** [comment]
I suspect the accepted method of forcing a renewal is to manually edit the `donotedit.conf` file, then reboot the container which would see a change in the file and trigger a renewal?

**Comment by aptalca** [comment]
No.
The file is literally called donotedit.conf
Do not edit that file.

Just make a change to the vars used, like setting staging to true (which is a good idea to do so anyway, whenever you make changes). Once it works, remove it and recreate.

**Comment by LBegnaud** [comment]
Fair enough.
