### ISSUE TITLE
Docker failing to issue certs on restart.

### ISSUE THREAD

**Issue by Daedilus** [linuxserver/docker-letsencrypt#417]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
After the subdomain config is set to (null) in the UNRAID GUI. 
Docker is started in Unraid GUI, docker should start normally and issue certification for root domain.

## Current Behavior
Docker inserts 'www' as subdomain instead of (null) due to `<Config Name="Subdomain(s)" Target="SUBDOMAINS" Default="www," Mode="" Description="Subdomains you'd like the cert to cover (comma separated, no spaces) ie. www,ftp,cloud," Type="Variable" Display="always" Required="false" Mask="false"></Config>` in the default xml script.
## Steps to Reproduce

1. Use domain with no/inactive www subdomain.
2. Edit config and remove default value of `www,`
3. Start docker. Docker will fail to issue certs to www.example.com

## Environment
**OS:** Unraid     
**CPU architecture:** x86_64      
**How docker service was installed:** Community applications

## Command used to create docker container (run/create/compose/screenshot)

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='letsencrypt' --net='bridge' --privileged=true -e TZ="America/Denver" -e HOST_OS="Unraid" -e 'EMAIL'='myemail@example.com' -e 'URL'='example.com' -e 'SUBDOMAINS'='www' -e 'ONLY_SUBDOMAINS'='false' -e 'DHLEVEL'='2048' -e 'VALIDATION'='http' -e 'DNSPLUGIN'='' -e 'PUID'='99' -e 'PGID'='100' -p '79:80/tcp' -p '442:443/tcp' -v '/mnt/user/appdata/letsencrypt':'/config':'rw' 'linuxserver/letsencrypt' 
9984297ef864d01aeb9d25886eda43fc556dd1b6e92536d722bfadede14e0720

## Docker logs

`ErrorWarningSystemArrayLogin

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=99
PGID=100
TZ=America/Denver
URL=example.com
SUBDOMAINS=www,
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
DHLEVEL=2048
VALIDATION=http
DNSPLUGIN=
EMAIL=daedilus@example.com
STAGING=

2048 bit DH parameters present
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Sub-domains processed are: -d www.example.com
E-mail address entered: daedilus@example.com
http validation is selected
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for www.example.com
Waiting for verification...
Challenge failed for domain www.example.com

http-01 challenge for www.example.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
- The following errors were reported by the server:

Domain: www.example.com
Type: dns
Detail: DNS problem: NXDOMAIN looking up A for www.example.com -
check that a DNS record exists for this domain
ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container
`
Note: I have omitted my domain that this is actually happening to, but you will probably get the point.

I can get this to work consistently if I edit the /boot/config/plugins/dockerMan/templates-user/my-letsencrypt.xml file removing `<Config Name="Subdomain(s)" Target="SUBDOMAINS" Default="www," Mode="" Description="Subdomains you'd like the cert to cover (comma separated, no spaces) ie. www,ftp,cloud," Type="Variable" Display="always" Required="false" Mask="false"></Config>` from the xml file or by removing the www, from that line.

**Comment by aptalca** [comment]
set subdomains to a single comma `,`
it's an unraid quirk

**Comment by Daedilus** [comment]
Well that was easy. Thank you.
