### ISSUE TITLE
permanent CPU load 1-2% from fail2ban-server

### ISSUE THREAD

**Issue by firex2** [linuxserver/docker-letsencrypt#42]
on my docker i have a permanent CPU load of 1-2%, even without any connections. the fail2ban-server is the issuse

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     ZEIT+ BEFEHL
 5920 root      20   0   73692  10896   2388 S   2,0  0,1  18:23.69 fail2ban-server

a log file is attached.
[fail2ban.txt](https://github.com/linuxserver/docker-letsencrypt/files/874891/fail2ban.txt)

**Comment by JigSawFr** [comment]
@firex2 i've seen the same problem on my server

**Comment by firex2** [comment]
host OS Ubuntu 16.04 (Linux hs 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

Docker version 17.03.0-ce, build 60ccb22

docker command: docker create --privileged --name=webserver -v /container/webserver/config:/config -e PGID=1001 -e PUID=1000 -e EMAIL=techadmin@xxx.bz -e URL=xxx.bz -e SUBDOMAINS=fb,cp,sr,pp,pms,sab,hydra -p 443:443 -e TZ=Europe/Berlin -e DHLEVEL=2048 linuxserver/letsencrypt

xxx=my domain :)

**Comment by aptalca** [comment]
I don't see what the problem is. Fail2ban is always active, monitoring the logs non stop. It's only natural that it is utilizing the cpu. 1-2% utilization is not high by any means.

**Comment by firex2** [comment]
more than any other container when idle doing nothing

**Comment by sparklyballs** [comment]
as @aptalca already said "Fail2ban is always active" , and being more than any other container is still irrelevant when the usage is so low.

**Comment by aptalca** [comment]
It's not doing nothing. It is constantly "processing"  multiple logs. Fail2ban does not listen for connections. It's a log parser. 

In any case it's not an issue with the container. That's how fail2ban behaves in non docker situations as well. You can take it up with fail2ban.
