### ISSUE TITLE
Error in the log

### ISSUE THREAD

**Issue by snoopy86** [linuxserver/docker-letsencrypt#423]
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)

Possible fix?:
https://www.bonneville.be/post/nginx-alert-detected-a-luajit-version-which-is-not-openrestys-many-optimizations-will-be-disabled-and-performance-will-be-compromised-see-httpsgithub-comopenrestyluajit2-for-openres/

**Comment by nemchik** [comment]
This message can be ignored. We are not compiling nginx (as the link you posted suggests). We're simply using the packaged version from the alpine repos. All the message means is that you COULD see improved performance with lua if you were to compile nginx with their optimizations. Even if you do not, you can still run lua, and there will not be a performance issue, just a lack of a potential performance gain that would have come from their optimizations.
