### ISSUE TITLE
How to use multiple domains with openmediavault?

### ISSUE THREAD

**Issue by FlyingEagle** [linuxserver/docker-letsencrypt#424]
Hi,

How to use multiple domains with multiple - but not wildcard - subdomains per domain using docker and reverse proxy in openmediavault?

regards

**Comment by aptalca** [comment]
Use extradomains like `-e EXTRA_DOMAINS="mywebsite.url,blah.mywebsite.url"`

**Comment by FlyingEagle** [comment]
thanks, it worked.
