### ISSUE TITLE
abuseipdb.conf action.d doesn't work

### ISSUE THREAD

**Issue by jcolson** [linuxserver/docker-letsencrypt#425]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
post should be successful:

curl --fail --tlsv1.1 --data "key=xxx" --data-urlencode "comment=$lgm" --data "ip=xxx" --data "category=18,21" "https://www.abuseipdb.com/report/json"

## Current Behavior
Failed to execute ban jail 'wordpress' action 'abuseipdb' info 'ActionInfo({'ip': 'xxx, 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7efd00199040>, 'matches': 'xxx - - [29/Mar/2020:10:05:41 +0000] "POST /wp-login.php HTTP/1.1" 200 2552 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\nxxx- - [29/Mar/2020:10:05:41 +0000] "POST /xmlrpc.php HTTP/1.1" 200 403 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"', 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7efd001995e0>})': Error banning xxx
2020-03-29 02:12:46,518 fail2ban.utils          [379]: ERROR   7efcfff57900 -- stderr: '  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current'
2020-03-29 02:12:46,518 fail2ban.utils          [379]: ERROR   7efcfff57900 -- stderr: '                                 Dload  Upload   Total   Spent    Left  Speed'
2020-03-29 02:12:46,519 fail2ban.utils          [379]: ERROR   7efcfff57900 -- stderr: ''
2020-03-29 02:12:46,519 fail2ban.utils          [379]: ERROR   7efcfff57900 -- stderr: '  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0'
2020-03-29 02:12:46,519 fail2ban.utils          [379]: ERROR   7efcfff57900 -- stderr: '100   793    0     0  100   793      0   4108 --:--:-- --:--:-- --:--:--  4087'
2020-03-29 02:12:46,519 fail2ban.utils          [379]: ERROR   7efcfff57900 -- stderr: 'curl: (22) The requested URL returned error: 429 '
2020-03-29 02:12:46,519 fail2ban.utils          [379]: ERROR   7efcfff57900 -- returned 22

## Steps to Reproduce

1. try to use the abuseipdb action type
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
via:
docker run -d  \
  --name letsencrypt \
  --cap-add NET_ADMIN \
  --network xxx \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=UTC \
  -e URL=xxx \
  -e SUBDOMAINS=wildcard \
  -e VALIDATION=dns \
  -e DNSPLUGIN=route53 `#optional` \
  -e EMAIL=xxx `#optional` \
  -e DHLEVEL=2048 `#optional` \
  -e ONLY_SUBDOMAINS=false `#optional` \
  -e EXTRA_DOMAINS=xxx `#optional` \
  -e STAGING=false `#optional` \
  -p 443:443 \
  -p 80:80 `#optional` \
  -v ${VOLUME}:/config \
  --restart always \
  linuxserver/letsencrypt:latest

## Docker logs
logs provided above

## I have been using an abuseipdb.conf file on another system with the actionban set to below:

actionban = lgm=$(printf '%%.1000s\n...' "<matches>"); curl -sSf "https://api.abuseipdb.com/api/v2/report" -H "Accept: application/json" -H "Key: <abuseipdb_apikey>" --data-urlencode "comment=$lgm" --data-ur
lencode "ip=<ip>" --data "categories=<abuseipdb_category>"

**Comment by aptalca** [comment]
This isn't really about this container specifically, but about fail2ban and the user customization of it. Fail2ban has been tested and shown it works in this container. I'd recommend starting with a simple test like enabling http auth for the domain and getting the pass wrong a few times. Then you can try and troubleshoot your custom action.

**Comment by jcolson** [comment]
the point is that the abuseipdb.conf in the container is stale and doesn't work.

**Comment by aptalca** [comment]
That's a default one that comes with the fail2ban install, not something we maintain. Please report it upstream to fail2ban.
