### ISSUE TITLE
NGINX Error

### ISSUE THREAD

**Issue by ich423** [linuxserver/docker-letsencrypt#429]
Hello,

I get the following error from nginx:
`nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
`
Does anyone know a solution to fix the problem?

------------------------------

## Environment
**OS:** Ubuntu server 18.04     
**CPU architecture:** x86
**How docker service was installed:**   https://github.com/docker/docker-install   

## Docker logs
`nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ndk_http_module.so" failed (Error loading shared library /var/lib/nginx/modules/ndk_http_module.so: No such file or directory) in /etc/nginx/modules/devel_kit.conf:1
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
`

**Comment by aptalca** [comment]
You didn't fill out the rest of the template so we have no idea
