### ISSUE TITLE
Request: Add ability to update geoiplite with license

### ISSUE THREAD

**Issue by blademckain** [linuxserver/docker-letsencrypt#431]
It is possibile to download the geoiplite with token

`# Database URL
https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY&suffix=tar.gz`

It is possibile to insert the ability to update with token in your package?

**Comment by aptalca** [comment]
You can curl it in a cron script either on host or inside the container
