### ISSUE TITLE
Openmediavault via Reverse Proxy

### ISSUE THREAD

**Issue by iamklaus** [linuxserver/docker-letsencrypt#432]
I use your docker image within an Openmediavault Server. I have installed it via Portainer. A couple of docker applications are connected to the internet via linuxserver/letsencrpyt very smoothly (eg my Nextcloud Docker environment or Zoneminder). The only problem I have is to populate the OMV webinterface via reverse proxy:

http://myserver:80 --> https://my.duckdns.org/open

I see the login page from OMV, but the login doesn't work. Is there any working nginx reverse proxy configuration for OMV?

**Comment by aptalca** [comment]
Please use [our discord](https://discord.gg/YWrKVTn) or forum for support requests, and post the proxy conf you tried.

Closing this as it is not a bug.
