### ISSUE TITLE
Unable to test nginx config file without killing webserver

### ISSUE THREAD

**Issue by WoLpH** [linuxserver/docker-letsencrypt#434]
## Expected Behavior

I expected this command:
`docker exec nginx nginx -t`

To test my nginx config and tell me if it's valid.

## Current Behavior

```
docker exec nginx nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
nginx: configuration file /etc/nginx/nginx.conf test failed
```

## Steps to Reproduce

1. Run the command above

This was previously discussed with regards to the reload command: https://github.com/linuxserver/docker-letsencrypt/issues/305

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** `apt install docker.io`

## Command used to create docker container (run/create/compose/screenshot)

Fairly stock run install HTTP verification. Not relevant for the issue

## Docker logs

Not relevant

**Comment by aptalca** [comment]
`docker exec -it letsencrypt nginx -c /config/nginx/nginx.conf -t`
