### ISSUE TITLE
error creating certificate

### ISSUE THREAD

**Issue by dony71** [linuxserver/docker-letsencrypt#436]
My docker config like below, but fail to create certificate.
I have forward port 80 and 443 in my router
Anybody can help me why?

docker create \
  --name=letsencrypt \
  --cap-add=NET_ADMIN \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=US/Los_Angeles \
  -e URL=xxx.duckdns.org \
  -e VALIDATION=http \
  -p 443:443 \
  -p 80:80 \
  -v /opt/letsencrypt/config:/config \
  --restart unless-stopped \
  linuxserver/letsencrypt:arm64v8-latest

....
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Registering without email!
An unexpected error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xffffb86c6eb0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb86c6eb0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffb86c6eb0>: Failed to establish a new connection: [Errno -3] Try again'))
Please see the logfiles in /var/log/letsencrypt for more details.
ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container

**Comment by aptalca** [comment]
Looks like you're having networking issues as the container cannot reach the letsencrypt servers.

Make sure you don't have something like pihole blocking it

**Comment by dony71** [comment]
I don't have any idea who blocking it?
Any way to verify? maybe like ping letsencrypt server?
What is letsencrypt server address?
I try duckdns validation but give same error also

**Comment by dony71** [comment]
i check open port and it shows port 80 and 443 open
so why still fails?

ubuntu@ubuntu:/opt/letsencrypt$ sudo nmap -sT -O localhost
Starting Nmap 7.60 ( https://nmap.org ) at 2020-04-15 15:42 PDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00074s latency).
Not shown: 994 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
443/tcp  open  https
3306/tcp open  mysql
8082/tcp open  blackice-alerts
8083/tcp open  us-srv

**Comment by dony71** [comment]
To check whether this is really true port 80 and port 443 blocking issue, I decided to install certbot and run in linux 
certbot certonly --standalone --preferred-challenges http-01 --email xxx@gmail -d xxx.duckdns.org
Certificate is generated successfully
@aptalca this confirm there is some issue with docker image
can you take a look on this?

**Comment by aptalca** [comment]
It's not an issue with your ports. It's an issue with your docker system and outgoing connections. Nothing I can look into or fix. It's specific to your system.

**Comment by dony71** [comment]
@aptalca can give me some hints what to look for? maybe if i provide some debug log will help you?
