### ISSUE TITLE
Link to blog post

### ISSUE THREAD

**Issue by alias86** [linuxserver/docker-letsencrypt#437]
Hey guys,
Could you add a link to this blog here?
https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/

Great blog, had some additional info which helped me a lot
Thanks for your hard work

**Comment by aptalca** [comment]
I prefer not to, simply because blog articles are static and go out of date. The readme is a living document and is the most accurate and up to date source of information about the image.
