### ISSUE TITLE
Coludflare DNS security, ZONE read only API token

### ISSUE THREAD

**Issue by walle89** [linuxserver/docker-letsencrypt#438]
First of all, I'm happy to see you have implemented scoped API tokens for Cloudflare. It's really big step in the right direction to increase the security of Cloudflare accounts. However, I think we can take an other step to make it a bit more secure.Currently the token generated for `dns_cloudflare_api_token` needs to get read _and_ edit DNS access to _all_ zones in order to function. 

My suggestion to make this more secure is to implement a DNS edit only token, like Traefik have done it (https://docs.traefik.io/https/acme/#providers , more details: https://go-acme.github.io/lego/dns/cloudflare/). In other words, we can add a new optional setting called something like `dns_cloudflare_api_edit_token` and let it use a token that only requires DNS edit permissions.

## Example CF permissions

`dns_cloudflare_api_edit_token` token settings:

**Permissions**
Zone - DNS - Edit

**Zone Resources**
Include - Specific zone - example.com
Include - Specific zone - my-server.example

`dns_cloudflare_api_token` token settings:

**Permissions**
Zone - Zone - Read

**Zone Resources**
Include - All zones

## Fallback
If `dns_cloudflare_api_edit_token` setting is not specified, it call fallback to use `dns_cloudflare_api_token` and let it work in the same way how it's currently implemented.

**Comment by aptalca** [comment]
What you're asking for is not supported by certbot: https://certbot-dns-cloudflare.readthedocs.io/en/stable/
