### ISSUE TITLE
Struggling to get Grocy working

### ISSUE THREAD

**Issue by Dinth** [linuxserver/docker-letsencrypt#439]
## Expected Behavior

https://grocery.xxx.uk should open Grocy. 

## Current Behavior

https://grocery.xxx.uk shows 502 error. Letsencrypt nginx is complaining 
`2020/04/22 06:43:22 [error] 407#407: 24 connect() failed (110: Operation timed out) while connecting to upstream, client: 10.10.0.1, server: grocery., request: "GET / HTTP/2.0", upstream: "http://10.10.1.12:9283/", host: "grocery.xxx.uk", referrer: "https://grocery.xxx.uk/`
in error.log.
http://10.10.1.12:9283 opens grocy without a hesitation. 

## Steps to Reproduce
1. Configure letencrypt: 
```
# make sure that your dns has a cname set for grocy

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name grocery.*;
    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app 10.10.1.12;
        set $upstream_port 9283;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

}
```
Filling $upstream_app with IP or docker name doesnt change anything.
2. Spin up linuxserver/letsencrypt
3. spin up linuxserver/grocy

## Environment
**OS: VMWare Photon**      
**CPU architecture:** x86_64
**How docker service was installed:**      
package manager
## Docker logs
```
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Let's Encrypt: https://letsencrypt.org/donate/
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
Variables set:
PUID=
PGID=
TZ=Europe/London
URL=xxx.uk
SUBDOMAINS=home,grocery
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=true
DHLEVEL=2048
VALIDATION=http
DNSPLUGIN=google
EMAIL=michal@xxx.uk
STAGING=false
2048 bit DH parameters present
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are:  -d home.xxx.uk -d grocery.xxx.uk 
E-mail address entered: michal@xxx.uk
http validation is selected
Certificate exists; parameters unchanged; starting nginx
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing... 
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Server ready


```

**Comment by aptalca** [comment]
Is grocy running with macvlan?

Post the command you used to create the grocy container

**Comment by Dinth** [comment]
> Is grocy running with macvlan?
> 
> Post the command you used to create the grocy container

I have used portainer.
![Screenshot from 2020-04-22 14-47-30](https://user-images.githubusercontent.com/313674/79991324-1895d200-84aa-11ea-80f4-91ce89077a0d.png)
![Screenshot from 2020-04-22 14-47-54](https://user-images.githubusercontent.com/313674/79991328-1af82c00-84aa-11ea-975e-740c8dee7a56.png)

**Comment by aptalca** [comment]
Is letsencrypt on macvlan?

**Comment by Dinth** [comment]
Im not 100% sure but its default setup of docker. Here's my network configuration:

![Screenshot from 2020-04-22 18-37-34](https://user-images.githubusercontent.com/313674/80014661-8224d900-84c8-11ea-8da2-e210a5f0c2bd.png)

**Comment by Dinth** [comment]
Just wanted to add that ive got literally the same problem with Calibre-web.
I have tried replacing the supplied configs with different configs found on the web and still having same issue
But my Home Assistant works fine.

**Comment by Dinth** [comment]
Also i found out that when i exec /bin/bash inside of letsencrypt container i cannot ping the servers ip address.

**Comment by aptalca** [comment]
Sounds like you have some networking issue with docker service

**Comment by jpmeijers** [comment]
This sounds very similar to https://github.com/linuxserver/docker-letsencrypt/issues/459

**Comment by j0nnymoe** [comment]
@jpmeijers looks like you're using the default docker network. You need to create a custom docker bridge network for the container names to resolve correctly. HomeAssistant is likely working because it runs as host networking.

**Comment by Dinth** [comment]
I have actually changed the underlying OS from VMWare Proton to Debian and it all works flawlessly out of the box.

**Comment by j0nnymoe** [comment]
Closing as this issue was due to something with PhotonOS, not an issue with the container itself.
