### ISSUE TITLE
Whois can't handle IP Addresses

### ISSUE THREAD

**Issue by pdobrien3** [linuxserver/docker-letsencrypt#442]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

sudo docker exec -it letsencrypt /usr/bin/whois 107.33.23.17 should produce Whois information both on the command line and in notifications

## Current Behavior

sudo docker exec -it letsencrypt /usr/bin whois 107.33.23.17 produces:
[Querying whois.iana.org:43 '107.33.23.17']
[Querying whois.iana.org:43 'domain 107.33.23.17 ']
[whois.iana.org]
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
%
% Error: Invalid query domain 107.33.23.17 
but sudo docker exec -it letsencrypt /usr/bin whois google.com produces expected results

Also, on my system, /usr/bin/whois 107.33.23.17 produces the expected results

It seems that the whois client on my docker host supports querying by ip-address, but the whois binary inside the 'letsencrypt' docker container doesn't.  It seems as if the whois client inside the docker only queries domains even though the action.d is setup to query IP addresses.

## Steps to Reproduce

1. sudo docker exec -it letsencrypt /usr/bin whois 107.33.23.17
2.
3.
4.

## Environment
**OS:**      
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)

**CPU architecture:** x86_64/arm32/arm64
x86_64      
**How docker service was installed:**
      

version: "2" 
services:
  letsencrypt: # https://github.com/linuxserver/docker-letsencrypt
    container_name: letsencrypt
    image: linuxserver/letsencrypt:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/user/docker/letsencrypt/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=xxxx
      - PUID=xxxx
      - EMAIL=my_email@gmail.com
      - URL=myduckdns.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - TZ=America/New_york
      - DUCKDNSTOKEN=myxxxxxduckdnsxxxxxtoken
    ports:
      - "80:80"
      - "443:443"

## Command used to create docker container (run/create/compose/screenshot)

Docker Compose

**Comment by aptalca** [comment]
yeah, it seems the `whois` that's in there is the busybox version (minimal features) that comes default with alpine.

We'll add the repo package of whois, which has full features

**Comment by pdobrien3** [comment]
Thank you very much, I have pulling my hair out for a couple days over this one. Thanks again.
