### ISSUE TITLE
[Feature Request] Add acme-dns DNSPLUGIN

### ISSUE THREAD

**Issue by n-i-x** [linuxserver/docker-letsencrypt#448]
Currently, wildcard DNS is only supported via dns validation. Users of Google Domains don't have a method of adding wildcard certificates as there is no proper API for updating TXT records. acme-dns was created for this very scenario.

https://github.com/joohoi/acme-dns
https://github.com/joohoi/acme-dns-certbot-joohoi

**Comment by IronicBadger** [comment]
This container is now deprecated in favour of [https://github.com/linuxserver/docker-swag](https://github.com/linuxserver/docker-swag).

If this issue is still important to you please open a new issue over there. Thanks!
