### ISSUE TITLE
Grafana fails with htaccess (fix included)

### ISSUE THREAD

**Issue by bigmak40** [linuxserver/docker-letsencrypt#450]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
When `http auth` is enabled, the default configurations for Grafana in `grafana.subdomain.conf.sample` allows for the user to authenticate and then allow access to the site.

## Current Behavior
A correct username/password results in a failure to authenticate, looping to the pop up log in screen. After several attempts it redirects to a webpage that says `**{"message":"Invalid username or password"}**`.

## Steps to Reproduce

1. Install Grafana
2. Verify login page is accessible
3. Configure NGINX/LetsEncrypt to encrypt connection to Grafana
4. Verify login page is accessible
5. Enable http auth by uncommenting the two lines in the conf
6. Verify login page is no longer accessible

## Step to fix
I believe that the only change required to add a third line to the http auth set of commented lines:
`proxy_set_header Authorization "";`
I found this work around at the [following page](https://github.com/grafana/grafana/issues/8314) and verified that it works on my grafana instance.

## Environment
**OS:**      Unraid
**CPU architecture:** x86_64    
**How docker service was installed:**      Via Community Apps

**Comment by tobbenb** [comment]
A little bit unsure what you mean. 
Are you saying that just enabling reverse proxy, you can't log in, or do you activate the the authentication commented out in the reverse proxy conf?

If it's the latter, you can't normally use double authentication.
