### ISSUE TITLE
proxy_pass to containername impossible

### ISSUE THREAD

**Issue by Thijxx** [linuxserver/docker-letsencrypt#451]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Nginx should forward traffic to my other container based on the hostname known to docker and working fine when I ping from the containers command line.

## Current Behavior
502 Bad Gateway
But I can ping the hostname/containername (calibreweb) fine when I open a terminal to the letsencrypt container.

## Steps to Reproduce
Create container with website
Create letsencrypt container
Create new bridge
proxy_pass to container name like: `proxy_pass http://mywebserver:8083;`

```
## Environment
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

## Command used to create docker container (run/create/compose/screenshot)
portainer with default settings

**some warnings**
```
mei 11 21:55:14 durban 4c78aef5fc6d[27474]: nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
mei 11 21:55:19 durban 4c78aef5fc6d[27474]: nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"
```

**config file**
It's not in the readme and the comments in `default` are only warning me and giving no clear direction or solution but I made a new file next to `default` named `calibreweb.conf` containing this config. If I use the IP of the calibreweb it works fine, but not on containername and docker seems to be switching up IP's every reboot so..
```
server {
       listen 443 ssl http2;
       listen [::]:443 ssl http2;

       root /config/www;
       index index.html index.htm index.php;

       server_name boeken.*;

       include /config/nginx/ssl.conf;

       client_max_body_size 0;

       location / {
		include /config/nginx/proxy.conf;
		resolver 127.0.0.11 valid=30s;
                set $upstream_docs calibreweb;
		proxy_pass http://$upstream_docs:80;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Forwarded-Proto $scheme;
       }
}
```

**Comment by nemchik** [comment]
Would you give the new proxy sample a try? if your container is up to date you should have a newer sample included. If not you can copy it from here https://github.com/linuxserver/reverse-proxy-confs/blob/14eb015b45fca3c83155e5c572a24a8dd9d87579/calibre-web.subdomain.conf.sample

**Comment by Thijxx** [comment]
Thanks, the result is the same.

**Comment by Thijxx** [comment]
This is my bridge configuration
```
[
    {
        "Name": "webservices",
        "Id": "25714e223433649ca838764ca14cd357f41e172a13",
        "Created": "2020-05-11T22:38:38.385096372+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "IPRange": "172.18.0.100/25",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

```

**Comment by nemchik** [comment]
Sorry I should have read closer when you said

> I made a new file next to `default` named `calibreweb.conf` containing this config.

Please check out https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/
Please read the whole guide, but particularly the section `Preset proxy confs` has relevant info about how to use the sample proxy files.

**Comment by Thijxx** [comment]
Ok that's a lot of information. I've read the proxy confs part and nothing new there, the last line is:

`If the proxied container is not in the same user defined bridge network as letsencrypt (could be on a remote host, could be using host networking or macvlan), we can change the proxy_pass directive to use an IP address instead: proxy_pass https://192.168.1.10:443;`

But this is the opposite of what user defined bridge networks are for, right? I've read in almost all documentation up till now that you can use container/host -names if you use a user defined bridge.

**Comment by nemchik** [comment]
You are correct that the proxy conf should allow you to use the hostname of the container being proxied as long as the proxy container and the container to be proxied are on the same user defined bridge network. Testing `docker exec letsencrypt ping calibreweb -c2` should show an IP address. The proxy config sample I linked has a dash in the container name, so be sure to account for that.

The part in the article it seems you have missed is:

> Our letsencrypt image comes with a list of preset reverse proxy confs for popular apps and services. They are [hosted on github](https://github.com/linuxserver/reverse-proxy-confs) and are pulled into the `/config/nginx/proxy-confs` folder as inactive sample files. To activate, one must rename a conf file to remove `.sample` from the filename and restart the letsencrypt container. Any proxy conf file in that folder with a name that matches `*.subdomain.conf` or `*.subfolder.conf` will be loaded in nginx during container start.

Specifically you should just be renaming the files in the folder you found them, not relocating them or creating new files in the site confs.

**Comment by Thijxx** [comment]
I'm back to the default bridge now and I followed the part I missed indeed. I use the right config.
On an IP it works, when using a containername it still fails. Ping works fine on containername.

**Comment by nemchik** [comment]
Just to confirm, are you restarting the letsencrypt container when you make changes to the configs?

**Comment by Thijxx** [comment]
Yes to be sure I restart letsencrypt and the target (calibreweb) container after every change, I also restarted docker a few times and I'll now reboot the host system just to rule out the reboot magic.

**Comment by nemchik** [comment]
Do you have any other proxies working?

**Comment by Thijxx** [comment]
No, I'll try a random other container.

**Comment by Thijxx** [comment]
It also fails. I'm wiping my disk and will do another try all the way from OS installation the upcoming days.

**Comment by nemchik** [comment]
I'm going to close this issue for now, but if you try again on the fresh install and still have troubles please comment here (no need to open a new issue) and we can reopen this issue. Otherwise please visit our discord for support.

**Comment by vald-phoenix** [comment]
Why this warning happens?
> nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/config/keys/letsencrypt/fullchain.pem"

**Comment by tobbenb** [comment]
@vald-phoenix Why are you posting on a close issue that doesn't seem o have anything to do with your issue?
