### ISSUE TITLE
[Feature Request] Add support for multiple certificates

### ISSUE THREAD

**Issue by n-i-x** [linuxserver/docker-letsencrypt#458]
This is a request for allowing certbot to generate multiple certificates instead of one certificate with multiple SANs. Even if this was only the case for EXTRA_DOMAINS it would be a huge improvement.

Right now, anyone who knows one of the domains hosted by this container can easily look at the certificate to find all the domains and subdomains hosted by the container.

Extra points if you can specify different challenge methods for each domain. For example, I'd like to generate a wildcard certificate for my primary domain so I can proxy all my services. But for my EXTRA_DOMAINS, I host other websites and would like to use standard http challenges for them.

**Comment by aptalca** [comment]
That's well beyond the scope of this image and not something we have plans for
