### ISSUE TITLE
Creating ECDSA certificaties

### ISSUE THREAD

**Issue by rix1337** [linuxserver/docker-letsencrypt#46]
There is currently no official, automatic way to receive ECDSA certificates from letsencrypt.

ECDSA certs can drastically increase HTTPS performance and are up for an official "release" by September 1, 2017: https://letsencrypt.org/upcoming-features/

This is just a suggestion to prepare for deploying these new certificates through this container.

Just an example how to manually get an ECDSA cert right now:
https://boops.me/how-to-get-a-signed-ecdsa-ecc-cert-from-letsencrypt/

**Comment by aptalca** [comment]
Those instructions are too complicated (create a csr as an intermediary, etc.) and thus more trouble than it's worth. However, if when released, it is as easy as including a switch like we do for the rsa bit part, and that it's compatible with most systems, we'll implement it.

**Comment by rix1337** [comment]
Sounds reasonable!

Thanks

**Comment by sparklyballs** [comment]
closing this..

**Comment by redflag237** [comment]
https://community.letsencrypt.org/t/howto-obtain-ecdsa-cert-in-addition-to-rsa-with-certbot/61687
ECDSA has become so important, is it possible to support it in near future?

**Comment by CHBMB** [comment]
https://community.letsencrypt.org/t/howto-obtain-ecdsa-cert-in-addition-to-rsa-with-certbot/61687/4
