### ISSUE TITLE
Does environment variable EXTRA_DOMAINS work ?

### ISSUE THREAD

**Issue by mattfaraday** [linuxserver/docker-letsencrypt#462]
I use cloudflare, and I have docker-letsencrypt set to use dns validation and give me a wildcard cert for my main domain. That works 100% fine. 

In the readme, it says you can give the environment variable EXTRA_DOMAINS ..quote.. 

_Additional fully qualified domain names (comma separated, no spaces) ie. extradomain.com,subdomain.anotherdomain.org_

but after specifying another domain, which is also DNS hosted on cloudflare and accessible via the same account/password/token as the first domain, it does not issue any certificate for the extra domain. 

I'm quite happy to configure nginx myself, to do the proxy parts, but I seem to be unable to get the container to issue a cert for my extra domain by simply passing it this environment variable. Is there something i'm missing ?

**Comment by aptalca** [comment]
It's the same cert that covers all domains and subdomains as SANs.

Post a log if cert creation is unsuccessful

**Comment by mattfaraday** [comment]
It's a totall different domain, and the first and only letencrypt request for the extra domain so no the primary cert won't cover all of them. 

Doing a docker logs <container> on the container shows that EXTRA_DOMAINS= is blank actually, which is odd because docker inspect shows it running with that variable set. 

Docker logs <container>

[(url) [cont-init.d] 50-config: executing...
Variables set:
PUID=1000
PGID=
TZ=Europe/London
URL=primary.domain.com
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
DHLEVEL=2048
VALIDATION=dns
DNSPLUGIN=cloudflare
EMAIL=
STAGING=

2048 bit DH parameters present
SUBDOMAINS entered, processing
Wildcard cert for faraday.at will be requested
No e-mail address entered or address invalid
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please retrieve a free license key from MaxMind,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing...
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Server ready]


docker inspect <container> relevant parts 

["Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PUID=1000",
                "GUID=1000",
                "TZ=Europe/London",
                "URL=primary.domain.com",
                "SUBDOMAINS=wildcard",
                "VALIDATION=dns",
                "DNSPLUGIN=cloudflare",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PS1=$(whoami)@$(hostname):$(pwd)\\$ ",
                "HOME=/root",
                "TERM=xterm",
                "DHLEVEL=2048",
                "ONLY_SUBDOMAINS=false",
                "AWS_CONFIG_FILE=/config/dns-conf/route53.ini",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=2",
                "EXTRADOMAINS=secondary.domain.com
            ],
]



Note I substituted my real domain with "primary.domain.com". The extra domain i substituted "secondary.domain.com". 

Docker inspect sees the variable fine, but docker logs on the container show the variable to be empty ? odd.

**Comment by tobbenb** [comment]
You haven't set the extra domains variable correctly. You are missing the _

**Comment by mattfaraday** [comment]
god i can't believe this was a typo. i'm so embarrassed ,,,

**Comment by CHBMB** [comment]
We've all been there.  Gonna close this if that's ok then?

**Comment by mattfaraday** [comment]
Yes please close. My apologies.
