### ISSUE TITLE
reverse proxy examples do not seem to work

### ISSUE THREAD

**Issue by molnarti** [linuxserver/docker-letsencrypt#463]
I am trying to enable some of the reverse proxy sample files in nginx/proxy-conf. 

i have followed the instructions of the readme.md file, set up a separate bridge network, attached all my containers to it and attempted to run the container.

enabling adminer.subfolder.conf  without any changes (the file claims none are necessery) gives me this error:
nginx: [emerg] "location" directive is not allowed here in /config/nginx/proxy-confs/adminer.subfolder.conf:3,

enabling jacket.subdomain.conf gives this:
nginx: [warn] conflicting server name "jackett.*" on 0.0.0.0:443, ignored,
nginx: [warn] conflicting server name "jackett.*" on [::]:443, ignored

the conflicting server name error is what I get on all subdomain proxys i have tried.

all my services are set up in a single docker-compose file, this is the section for letsencrypt:

image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - URL=$DOMAINNAME
      - SUBDOMAINS=www,omv,ilo,transmission,jackett,portainer,dashmachine,plex
      - VALIDATION=http
      - EMAIL=$EMAIL_TO
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=false #optional
     volumes:
      - $DOCKERCONFIG/letsencrypt:/config
      - $USERDATA/www:/config/www
    ports:
      - 10443:443
      - 1080:80 #optional
    restart: unless-stopped

**Comment by aptalca** [comment]
Looks like you edited/customized/overrode one of the default nginx confs and broke it. I assure you they work with the defaults

**Comment by j0nnymoe** [comment]
Closing due to no response.
