### ISSUE TITLE
SUBDOMAINS

### ISSUE THREAD

**Issue by niipjack** [linuxserver/docker-letsencrypt#47]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

if you set the 'SUBDOMAINS' like that
 -e SUBDOMAINS=a,b,c,d
and then run the container,it will cause erros.
does  linuxserver/docker-letsencrypt only support 3 subdomains?

> An unexpected error occurred:
There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for exact set of domains:

**Comment by aptalca** [comment]
don't leave spaces around the "=" and use quotation marks around the subdomains

**Comment by niipjack** [comment]
i try to use
-e SUBDOMAINS="a,b,c,d"
but the error is still there

**Comment by aptalca** [comment]
You were throttled by letsencrypt. It seems you made too many changes too quickly.

**Comment by niipjack** [comment]
if i just use -e SUBDOMAINS=a,b,c 
it will be success.

**Comment by sparklyballs** [comment]
you can only make so many requests (5 i believe) to letsencrypt for the same set of subdomains in a 7 day period.

if you try a,b,c,d 5 times in 7 days it will give that error, but a,b,c is a different set of subdomains and you get a new set of 5 again.

this is a feature of letsencrypt.

**Comment by niipjack** [comment]
so i just need to wait for 7 days?
and then try  -e SUBDOMAINS=a,b,c,d  again,it should be work?

**Comment by niipjack** [comment]
ok,i have idea to fix this issue
just try to use -e SUBDOMAINS=a,b,c,d,e

**Comment by niipjack** [comment]
try just try to use -e SUBDOMAINS=a,b,c,d,e 
still get this error:

> An unexpected error occurred:
There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for:

**Comment by aptalca** [comment]
You should contact letsencrypt. That is not something we control

**Comment by niipjack** [comment]
ok
i will try to contact them

**Comment by niipjack** [comment]
thanks
