### ISSUE TITLE
Use cron inside docker-letsencrypt

### ISSUE THREAD

**Issue by MykolaKovrizhnykh** [linuxserver/docker-letsencrypt#470]
Hi. I need to run 

```php artisan tenancy:run schedule:run```

in cron every minute, how can I use cron that used for auto-renew certs?

**Comment by MykolaKovrizhnykh** [comment]
I tried to 
add 

- ./crontab:/etc/crontabs/root

to volumes

and crontab file file contains this:

# do daily/weekly/monthly maintenance
# min	hour	day	month	weekday	command
* * * * * cd /config/www && php artisan tenancy:run schedule:run
*/15	*	*	*	*	run-parts /etc/periodic/15min
0	*	*	*	*	run-parts /etc/periodic/hourly
0	2	*	*	*	run-parts /etc/periodic/daily
0	3	*	*	6	run-parts /etc/periodic/weekly
0	5	1	*	*	run-parts /etc/periodic/monthly

But it is not work :(

**Comment by aptalca** [comment]
crontab is in the config folder, you can edit that

**Comment by MykolaKovrizhnykh** [comment]
I edited /config/crontabs/root

> # do daily/weekly/monthly maintenance
> # min   hour    day     month   weekday command
> */15    *       *       *       *       run-parts /etc/periodic/15min
> 0       *       *       *       *       run-parts /etc/periodic/hourly
> 0       2       *       *       *       run-parts /etc/periodic/daily
> 0       3       *       *       6       run-parts /etc/periodic/weekly
> 0       5       1       *       *       run-parts /etc/periodic/monthly
> # renew letsencrypt certs
> 8       2       *       *       *       /app/le-renew.sh >> /config/log/letsencrypt/letsencrypt.log$
> # laravel scheduler
> * * * * * cd /config/www && php artisan tenancy:run schedule:run


But when I use crontab -e inside container still have this: 

> # do daily/weekly/monthly maintenance
> # min   hour    day     month   weekday command
> */15    *       *       *       *       run-parts /etc/periodic/15min
> 0       *       *       *       *       run-parts /etc/periodic/hourly
> 0       2       *       *       *       run-parts /etc/periodic/daily
> 0       3       *       *       6       run-parts /etc/periodic/weekly
> 0       5       1       *       *       run-parts /etc/periodic/monthly

**Comment by aptalca** [comment]
Please wrap them in triple backticks, it's very hard to read (or post on pastebin).

Did you restart the container?

**Comment by MykolaKovrizhnykh** [comment]
> Please wrap them in triple backticks, it's very hard to read (or post on pastebin).
> 
> Did you restart the container?

Yes, I restarted container.

**Comment by MykolaKovrizhnykh** [comment]
@aptalca , can you reopen issue, please? Cause I still have problem with this task.

**Comment by aptalca** [comment]
Don't know what to tell you, it works fine here.
```
aptalca@lsio-le-test:~/letsencrypt$ cat crontabs/root 
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
# renew letsencrypt certs
8       2       *       *       *       /app/le-renew.sh >> /config/log/letsencrypt/letsencrypt.log 2>&1
aptalca@lsio-le-test:~/letsencrypt$ echo "#testing" >> crontabs/root 
aptalca@lsio-le-test:~/letsencrypt$ docker restart letsencrypt 
letsencrypt
aptalca@lsio-le-test:~/letsencrypt$ docker exec -it letsencrypt cat /etc/crontabs/root
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
# renew letsencrypt certs
8       2       *       *       *       /app/le-renew.sh >> /config/log/letsencrypt/letsencrypt.log 2>&1
#testing
```

I closed the ticket because it was not a bug report. Feel free to drop into discourse or discord for support.
