### ISSUE TITLE
[Feature request] add healthchecks.io monitoring

### ISSUE THREAD

**Issue by l4t3b0** [linuxserver/docker-letsencrypt#472]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

### From the healthchecks.io website:
[Healthchecks.io](https://healthchecks.io) is a service for monitoring cron jobs and similar periodic processes

Healthchecks.io works as a dead man's switch for processes that need to run continuously or on regular, known schedule. For example:

- filesystem backups, database backups
- task queues
- database replication status
- report generation scripts
- periodic data import and sync jobs
- periodic antivirus scans
- DDNS updater scripts
- _**SSL renewal scripts**_

### API
It has a very straightforward [HTTP API](https://healthchecks.io/docs/http_api/) that can be used from the [shell](https://healthchecks.io/docs/bash/) also.

**Please consider implementing it.**
Thank you

**Comment by j0nnymoe** [comment]
We already have this : https://github.com/linuxserver/docker-healthchecks

**Comment by l4t3b0** [comment]
hi j0nnymoe

I think we are not on the same track here.

Im not suggesting to run the **server side** healtcheck.
Im suggesting to implement the **client side** healtcheck in the letsencrypt container.

I just want to be notified by healthchecks if letencrypt has problems for some reason.

**Comment by nemchik** [comment]
@l4t3b0 you can check out the conversation at https://github.com/linuxserver/docker-letsencrypt/pull/276

**Comment by l4t3b0** [comment]
hi nemchik

I dont think that thread is relevant from my point of view.
Im not suggesting to implement general healtcheck funtions monitoring continous process states.

let me explain what healthcheck.io is about.

With the healthchecks.io client side we can send events to the server side about the execution of the programs/scripts.
These events are STARTED, FINISHED, FAILED.
These are events we should send and not statuses that we should evaluate.

Healthchecks.io on the server side is listening for these events and sends notification to the end user. (email, slack, pushover ... etc)

The wonderful thing about healthchecks.io server side is, that if everything goes well periodically, than the user is not unnecessarily notified.
If something goes wrong, than the user is notified immediately.
If the server side does not get any events within an preconfigured interval, than the user also gets notified.

Therefore it makes it a perfect tool to be notified about malfunctioning periodic tasks.

What im suggesting is, that everytime the letencrypt script is executed it should send a STARTED event.
The return value of the processes should be evaluated on the fly in the script and it should return a corresponding FINISHED or FAILED events. No continous or periodic monitoring.

Do we have a common understanding this time?
