### ISSUE TITLE
[Feature Request] Please add goaccess revers conf

### ISSUE THREAD

**Issue by karkaaa** [linuxserver/docker-letsencrypt#475]
Hello,

Please add goaccess nginx revers conf.

Thank you.

**Comment by CHBMB** [comment]
This isn't the repository for reverse proxy configs.

https://github.com/linuxserver/reverse-proxy-confs

As a rule we encourage people to submit configs rather than request them.

It's quite labour intensive to install an application we don't use to make a reverse proxy config.
