### ISSUE TITLE
Question: Is there a hook to pickup custom cron jobs?

### ISSUE THREAD

**Issue by 2devnull** [linuxserver/docker-letsencrypt#48]
Would like to be able to automate sending the periodically renewed certificate to the host systems running the applications that need them. How do I get this docker to pickup my custom script to run after a renewal?

**Comment by sparklyballs** [comment]
there is no such hook in the image

**Comment by aptalca** [comment]
The certs are stored in the config folder residing on the host. You can always share that location with other apps. The cert symlink is always the same so nothing changes when it is refreshed. 

For instance the folder with the keys are mapped in my emby container and emby uses the same certs for remote access.

**Comment by sparklyballs** [comment]
with the clarification from @aptalca i'm going to go ahead and close this

**Comment by 2devnull** [comment]
@aptalca. Yes, on the same host, sharing the same folder is perfectly fine. My main issue is that I have to scp this to other systems, e.g. pydio etc. 

My main goal is to be able to have this initiated only when a cert is truly renewed, something I was hoping the certbot can do an run all scripts in a particular folder (one being mine to scp out the newly acquired certs). Right now, I will try to use a daily cron job.

**Comment by aptalca** [comment]
A couple of ideas for your specific case, you can probably share via smb or nfs and the like so they can access the cert directly, or

crontab for root is in the config folder, you can add your script to the config folder and add an entry to crontab so it copies the cert after each renewal attempt, which is set to 2:08 am every night

**Comment by 2devnull** [comment]
Yes, I thought about doing that, but the image doesn't have ssh/scp included. I can probably extend the image to add those but still trying to find a good solution as I run this on RancherOS which itself doesn't have a crontab installed. I found this but not sure it can handle scp to multiple hosts:
https://github.com/srvrco/getssl

**Comment by 2devnull** [comment]
@aptalca - How did you share the cert directory. Did you have to change permissions to do so?

BTW - This is how the files created by the image in my config folder looks:
d????????? ? ? ? ?            ? crontabs
-????????? ? ? ? ?            ? donoteditthisfile.conf
d????????? ? ? ? ?            ? etc
d????????? ? ? ? ?            ? fail2ban
d????????? ? ? ? ?            ? keys
d????????? ? ? ? ?            ? log
d????????? ? ? ? ?            ? nginx
d????????? ? ? ? ?            ? php
d????????? ? ? ? ?            ? www
`

`

**Comment by aptalca** [comment]
What did you set the PUID and PGID to? The same (non-root) user running RancherOS?

I'm not familiar with RancherOS but on other platforms I use docker on (ubuntu, debian, unraid, libreelec), you set the user and group id the same as the host user (1000 on ubuntu, 99:100 on unraid, etc.) so the files in the config folder are owned by the same uid in and out of the container.

**Comment by aptalca** [comment]
And for other docker container based services (like emby), I just map that same folder as another volume

**Comment by 2devnull** [comment]
I do this:
```
	-e PUID=$(id -u) 
	-e PGID=$(id -g) 
```

**Comment by aptalca** [comment]
docker log will show you what uid and gid it is running with

**Comment by 2devnull** [comment]
```
4/18/2017 3:48:58 PMUser uid:    1100
4/18/2017 3:48:58 PMUser gid:    1100
```
1100 is the rancher user id on RancherOS.

**Comment by 2devnull** [comment]
OK, I ended up creating a crontab container, shared the letsencrypt/config/etc/letsencrypt so that a script within the crontab container can then get the certs (optionally combine them, e.g. chain/intermediate, rename them) and distribute them to the appropriate hosts. I set this up for daily run.
