### ISSUE TITLE
[Feature Request] Netcup dns plugin

### ISSUE THREAD

**Issue by LivingWithHippos** [linuxserver/docker-letsencrypt#480]
Hello guys,
I'd like to request an implementation of the [netcup](netcup.eu) dns plugin for generating wildcard certificates. I know about [this one.](https://github.com/coldfix/certbot-dns-netcup) 
Thanks

**Comment by IronicBadger** [comment]
This container is now deprecated in favour of [https://github.com/linuxserver/docker-swag](https://github.com/linuxserver/docker-swag).

If this issue is still important to you please open a new issue over there. Thanks!
