### ISSUE TITLE
Nginx "hidden" by default?

### ISSUE THREAD

**Issue by jsbrain** [linuxserver/docker-letsencrypt#481]
Hey, this is just a conceptual question:

Is the nginx server "hidden" using the default config so one cannot see that the content is served by the reverse proxy at all?
I checked the headers etc. and I cannot find any indications that would reveal the nginx server in the response but I just wanted to make sure in case I'm missing something.

Could someone please tell me if the proxy is "invisible" by default and if not, what would I need to change to achieve that?

**Comment by aptalca** [comment]
I don't know what your end goal is, but the 404 page would give it away (among probably other ways)

**Comment by jsbrain** [comment]
My goal is to make the nginx absolutely invisible to the client. Thanks for the hint of the 404. Do you know of some edge cases of requests, that might set some headers that would definitely expose the nginx to the client?

**Comment by LBegnaud** [comment]
really not the forum for this kind of request. Cursory search shows you'll need a module which i believe is installed with this container:

https://stackoverflow.com/questions/24594971/how-to-changehide-the-nginx-server-signature

```
http {
    ...
    more_set_headers "Server: Your_New_Server_Name";
    server_tokens off; 
    ...
}
```

**Comment by jsbrain** [comment]
Ok thank you guys, that already helped a lot!
