### ISSUE TITLE
Ombi v4 Config File (subfolders)

### ISSUE THREAD

**Issue by thejamescarter** [linuxserver/docker-letsencrypt#483]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

The new version of ombi does not work with the provided config files. Does anyone have a config file for v4 or is there something im missing.

------------------------------

## Expected Behavior
It should just work as it works perfectly with the v3 version of ombi.

## Current Behavior
Simply does not work. Gives an NGINX error.

## Steps to Reproduce
1. Upgrade to v4 ombi
2. Set base url /ombi
3. Try using RP

## Environment
**OS:**      Unraid V6.8.3
**CPU architecture:** AMD 3900X
**How docker service was installed:**      
From community apps

**Comment by tobbenb** [comment]
It probably helps to include the error messages.
