### ISSUE TITLE
Creating Certificates for Multiple DuckDNS subdomains

### ISSUE THREAD

**Issue by martinpetrov1096** [linuxserver/docker-letsencrypt#484]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

So I'm wondering how I can create multiple certificates for each of my duck dns subdomains. What should the environemnt variable URL be set to?
------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by tobbenb** [comment]
This is for bugs and not support. Please use our discourse forum or join our discord to get support.

**Comment by nemchik** [comment]
Further info: this container is not setup in a way that supports maintaining multiple individual certificates. You can create one certificate that covers all of your domains and subdomains. If you have for example a.duckdns.org and b.duckdns.org you would add b.duckdns.org to your EXTRA_DOMAINS variable. Both domains would appear on the same certificate. If you have a.a.duckdns.org and b.a.duckdns.org you would just use the URL and SUBDOMAINS variables. Our readme has some basic information on these topics, and out blog covers more information as well https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/
