### ISSUE TITLE
Can we support DNSPod？

### ISSUE THREAD

**Issue by darlexlin** [linuxserver/docker-letsencrypt#487]
## Request

DNSPod is very popular in China. Many people are using DNSPod, including me. Can we support DNSPod？
So we can use letsencrypt easily.

I found this. https://github.com/tengattack/certbot-dns-dnspod
So, I think we can support DNSPod easily.

**Comment by drizuid** [comment]
I would suggest adding it to your container for now with

pip3 install -U certbot-dns-dnspod

https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

I'll submit a PR for evaluation.

**Comment by IronicBadger** [comment]
This container is now deprecated in favour of [https://github.com/linuxserver/docker-swag](https://github.com/linuxserver/docker-swag).

If this issue is still important to you please open a new issue over there. Thanks!
