### ISSUE TITLE
php7-sockets package

### ISSUE THREAD

**Issue by demonspork** [linuxserver/docker-letsencrypt#49]
Could you add the `php7-sockets` package to this docker or your alpine base? I have a php app I am trying to run from my www folder that is requiring it to be added and don't want to lose it next update.

**Comment by JigSawFr** [comment]
@demonspork you need to create or run another container for this,
this image is limited only to let'x encrypt.
just edit your nginx config to proxy your container app ;)

**Comment by aptalca** [comment]
Actually, we do provide php support in the letsencrypt container, but we only add php modules as requested. Many php modules are very rarely used and we would rather not increase the image size unnecessarily.

We'll go ahead and add php-sockets to the letsencrypt and nginx containers.
