### ISSUE TITLE
Separate directory for certs from config

### ISSUE THREAD

**Issue by pkuehne** [linuxserver/docker-letsencrypt#493]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Desired Behavior
It would be useful if the certs could be put into folder/mount other than `/config`, something like `/certs`.

## Rationale
* This way the config can be versioned in a git repository or backed up to storage without including the live certificates with all their private keys, etc
* It's useful to be able to provide the certificates in a central location via a NAS mount without having to expose the entire container configuration. For example when running a mail server on another host.
* Config and data should be separated (like they are on the nextcloud image for example)

**Comment by nemchik** [comment]
You can initialize the git repo in `/config` and then add a `.gitignore` file containing
```gitignore
etc/
keys/
```
and honestly I would also recommend
```gitignore
log/
fail2ban/fail2ban.sqlite*
```
And you may find more that you would not want in your repo as well.

**Comment by nemchik** [comment]
With regards to config and data separation, you can also just include additional volumes. If using compose you would have
```yaml
- /path/on/host/config:/config
- /path/on/host/certs-keys:/config/keys
- /path/on/host/certs-etc:/config/etc
```
or something of that nature.

**Comment by pkuehne** [comment]
I didn't know that multiple nested volumes work, thanks!
