### ISSUE TITLE
Incorrect permissions after renewal

### ISSUE THREAD

**Issue by ThinkChaos** [linuxserver/docker-letsencrypt#495]
## Expected Behavior
After renewal the new certificates should be owned by the ids specified in `PUID` and `PGID`.

## Current Behavior
The certificates are owned by root.
This caused errors in other containers that could no longer use the certificates.

## Steps to Reproduce
Let the container run long enough for a renewal to happen.

## Workaround
My workaround was to restart the container, triggering `/etc/cont-init.d/50-config` which does a `chown -R /config`.

**Comment by aptalca** [comment]
yup, because certbot runs as root, they will be owned by root after renewal until a restart during which the whole folder is chowned. We'll fix that, but since this image is currently going through a transition to a new repo and name, it will likely have to wait until after the switch

**Comment by aptalca** [comment]
This is fixed in SWAG
