### ISSUE TITLE
Authelia doc

### ISSUE THREAD

**Issue by jakobkukla** [linuxserver/docker-letsencrypt#496]
Is there any guide on how to set up Authelia with the letsencrypt container? I'm pretty lost tbh. Maybe add a section in the documentation?

**Comment by lordraiden** [comment]
Probably is would be easy cosidering that the configuration files are commented but I think the community will appreciate a lot a detailed guide for noobs :)

**Comment by aptalca** [comment]
A blog post about setting up authelia is in the works

**Comment by aptalca** [comment]
https://blog.linuxserver.io/2020/08/26/setting-up-authelia/
