### ISSUE TITLE
Certificate issue w/ Amazon Alexa

### ISSUE THREAD

**Issue by mguinness** [linuxserver/docker-letsencrypt#499]
I developed a custom Alexa skill, but when I tried to use against an endpoint proxied by this container I get error "Cannot establish SSL connection to your skill endpoint".  I was able to locate the cause of the problem which was the `ssl_ciphers` entry in the ssl.conf file.

https://github.com/linuxserver/docker-letsencrypt/blob/7f1b7f791f7d8394fea89629f0235a68477eb80d/root/defaults/ssl.conf#L13

I can see this is using the [Intermediate Security](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29) setting.  There is a similar [issue](https://github.com/nginx-proxy/nginx-proxy/issues/1440) raised on the nginx-proxy repo where it mentions CBC ciphers as being needed.  Unfortunately that's as far as I got, I'm hoping someone who sees this issue can help determine what modifications are needed to make this work with the Amazon servers.

**Comment by nemchik** [comment]
You can feel free to edit the ciphers to set them however you like. We provide defaults using the mozilla recommendation you linked, but if you change the config your preferences will be kept.

I don't have specific information or experience with your use case, so I can't offer much of a recommendation on the exact change you need to make.

**Comment by mguinness** [comment]
I've changed the configuration for my application so I'm good.  I just wanted to flag it in case others encounter this issue.  I wonder if noting this in README or the below blog might help others trying to use Alexa skills with the container.

https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/
