### ISSUE TITLE
Support for multiple domains

### ISSUE THREAD

**Issue by pindab0ter** [linuxserver/docker-letsencrypt#50]
This container currently offers no (easy) support for multi-domain setups. When configuring, only one single domain can be specified. Please support the option of setting up Lets Encrypt for multiple domains.

**Comment by aptalca** [comment]
Due to the automation in this container, adding multi-domain setup would significantly complicate things.

**Comment by ethanopp** [comment]
Is there any way to run separate containers for each of the domains?

**Comment by pindab0ter** [comment]
Should be possible, but then how do you separate the traffic for different domains all coming in on port 443? This would require a separate server/Docker image to be set up.

**Comment by CHBMB** [comment]
@ethanopp I told you this in IRC

**Comment by ethanopp** [comment]
pindab0ter, that is the route I am trying to go with but experiencing some issues. 

CHBMB, saw your note but wanted to post here so I could provide more details and also get some advice on how to accomplish the  "Fancy routing". Here are my current issues:

1: The first docker create works perfect, all the domain and subdomains go thorough fine....But the 2nd docker create starts up fine, and then when certbot checks to make the cert for domain 2, it returns the error that my WAN IP:443 already has been set up - Yes I have verified that the new domain points to my WAN:
```
Failed authorization procedure. domain2.com (tls-sni-01): urn:acme:error:unauthorized :: 
The client lacks sufficient authorization :: 
Incorrect validation certificate for tls-sni-01 challenge. 
Requested 061d4bb7f204af743ca17e79265c4cb5.984823c59c4ccde1bc6f7e7b949e0072.acme.invalid from XX.XXX.XXX.XX:443. 
Received 2 certificate(s), first certificate had names "collabora.domain1.com, domain1.com, nextcloud.domain1.com, plex.domain1.com, www.domain1.com"   
```

2. In terms of "fancy routing", what did you have in mind? Is it possible to just point the DNS for domain2 to Port 449, so every time someone goes to domain2.com it hits the 2nd letsencrypt docker, and then i route it internally to the proper docker (wordpress in this scenario)?

```
docker create \
--privileged --name=LetsEncrypt-domain1 \
--net='bridge' \
-v "/share/CACHEDEV1_DATA/Container/LetsEncrypt-domain1":/config \
-e PUID=1001 -e PGID=100 \
-e EMAIL=email1@gmail.com \
-e URL=domain1.com \
-e SUBDOMAINS=nextcloud,collabora,www,plex\
-e TZ=America/New_York \
-p 80:80 -p 443:443 \
linuxserver/letsencrypt

docker create \
--privileged --name=LetsEncrypt-domain2\
--net='bridge' \
-v "/share/CACHEDEV1_DATA/Container/LetsEncrypt-domain2":/config \
-e PUID=1001 -e PGID=100 \
-e EMAIL=email2@gmail.com \
-e URL=domain2.com \
-e TZ=America/New_York \
-p 89:80 -p 449:443 \
linuxserver/letsencrypt
```

Also, should I be using different email addresses in the separate docker creates above?

Thanks!

**Comment by CHBMB** [comment]
First of all, you'll need to give the containers different IP addresses.  Look into macvlan for that.  Then you got to work out how you're going to get incoming traffic routed to one ip or the other based on which domain it's going to.  Probably going to need something like pfsense for that and an incoming rule.

**Comment by evanrich** [comment]
@pindab0ter you could easily do this with haproxy, then just add backends for each server pointing to different letsencrypt containers.

**Comment by aptalca** [comment]
This image now supports multiple domains

**Comment by NathanTheGr8** [comment]
Awesome feature, but I have a question. Where do I include the additional site conf files? Can I include them at the bottom of the default but in a new server block? Something like

`
# main server block
server {
	listen 443 ssl default_server;

	root /config/www;
	index index.html index.htm index.php;

	server_name mydomain.com;

	ssl_certificate /config/keys/letsencrypt/fullchain.pem;
	ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
	ssl_dhparam /config/nginx/dhparams.pem;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;

	client_max_body_size 0;

	location / {
		try_files $uri $uri/ /index.html /index.php?$args =404;
	}

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		# With php7-cgi alone:
		fastcgi_pass 127.0.0.1:9000;
		# With php7-fpm:
		#fastcgi_pass unix:/var/run/php7-fpm.sock;
		fastcgi_index index.php;
		include /etc/nginx/fastcgi_params;
	}
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    root /config/www/myotherdomain.com;
    index index.html index.htm index.php;

    server_name myotherdomain.com;

    ssl_certificate /config/keys/letsencrypt/fullchain.pem;
	ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
	ssl_dhparam /config/nginx/dhparams.pem;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;
	
    location / {
        proxy_pass        http://127.0.0.1:8321;
        include /config/nginx/proxy.conf;
    }

}
`
Or do I just create a new conf and then symlink it to sites-enabled? It doesn't look like sites-enable gets mapped to the host so I assume I would have to do it inside the container.

**Comment by aptalca** [comment]
You can add multiple server blocks into default, or you can add more site conf files into that folder. Either works. Just don't delete default. The container does not use sites-enabled I am conf files in that folder are automatically enabled.

**Comment by pindab0ter** [comment]
Thanks a lot for supporting this. It works like a charm!

**Comment by Xosmond** [comment]
But I got a problem, we should run a container this way:
```
docker run \
--cap-add=NET_ADMIN --name=letsencrypt -d -v ./config:/config -e PGID="1000"
-e EMAIL=mail -p 443:443 -p 80:80 -e TZ=America/New_York \
-e EXTRA_DOMAINS="alejandra.example.club, alexandra.example.club" \
linuxserver/letsencrypt
```

Without need to set an **url** or **subdomains** because we are passing the extra domains, this could be done I think with a conditional.
