### ISSUE TITLE
Additional Domain with Wildcard Subdomains Error

### ISSUE THREAD

**Issue by savager** [linuxserver/docker-letsencrypt#502]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hello, using this docker config I am unable to certify subdomains on an additional domain (*.otherduck.duckdns.org). It seems this is possible in the example with *.additionaldomain.com.

Also, this setup does work in every other way, I love the container, and thank you for it!

------------------------------

## Expected Behavior

Was hoping to both certify www.something.duckdns.org as well as any subdomain of another domain ie: *.otherduck.duckdns.org

## Current Behavior

Currently I get the error: 

Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA. You may need to use an authenticator plugin that can do challenges over DNS.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

ubuntu 18 

## Command used to create docker container (run/create/compose/screenshot)

`sudo docker run -d \
  --name=letsencrypt \
  --cap-add=NET_ADMIN \
  --network=nginx \
  -e PUID=1000 \
  -e PGID=100 \
  -e TZ=US/Central \
  -e SUBDOMAINS=www,whatever,test \
  -e URL=something.duckdns.org \
  -e VALIDATION=http \
  -e DUCKDNSTOKEN=token \
  -e EMAIL=emailioaddresstevez@example.com \
  -e DHLEVEL=2048 \
  -e ONLY_SUBDOMAINS=false \
  -e EXTRA_DOMAINS=*.otherduck.duckdns.org \
  -p 443:443 \
  -p 80:80 \
  -v /etc/nginx:/config \
  --restart unless-stopped \
  linuxserver/letsencrypt`

I also tried passing -e SUBDOMAINS=wildcard to no avail

**Comment by aptalca** [comment]
You can't do wildcard with http validation
