### ISSUE TITLE
Nginx not accepting requests due to certificate auto-renewal failure

### ISSUE THREAD

**Issue by KumarWaghmode** [linuxserver/docker-letsencrypt#507]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Nginx should listen on 443

## Current Behavior
Nginx refusing requests

## Steps to Reproduce

1. User docker-compose:
version: "2"
services:
  letsencrypt:
    depends_on:
      - another-cpntainer
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    links:
      - "another-container:another-container"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=*****.nip.io
      - SUBDOMAINS=www,demo,backend
      - VALIDATION=http
      - STAGING=false
    volumes:
      - ./config:/config
      - ./nginx:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80

  another-container:
    image: ***
    container_name: another-container
    ports:
      - 5000:5000

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Docker logs

sudo docker logs 5851ef056f78
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Let's Encrypt: https://letsencrypt.org/donate/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
Variables set:
PUID=1000
PGID=1000
TZ=Europe/London
URL=****.nip.io
SUBDOMAINS=www,demo,backend
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=http
DNSPLUGIN=
EMAIL=
STAGING=false

SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Sub-domains processed are:  -d www.******.nip.io -d demo.*****.nip.io -d backend.****.nip.io
No e-mail address entered or address invalid
http validation is selected
Certificate exists; parameters unchanged; starting nginx
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please retrieve a free license key from MaxMind,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing... 
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Server ready
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
nginx killed (pid 517)
nginx killed (pid 518)
nginx killed (pid 519)
nginx killed (pid 520)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
nginx killed (pid 2104)
nginx killed (pid 2105)
nginx killed (pid 2106)
nginx killed (pid 2107)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
nginx killed (pid 3214)
nginx killed (pid 3215)
nginx killed (pid 3216)
nginx killed (pid 3217)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
nginx killed (pid 5420)
nginx killed (pid 5421)
nginx killed (pid 5422)
nginx killed (pid 5423)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Let's Encrypt: https://letsencrypt.org/donate/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
Variables set:
PUID=1000
PGID=1000
TZ=Europe/London
URL=*****.nip.io
SUBDOMAINS=www,demo,backend
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=http
DNSPLUGIN=
EMAIL=
STAGING=false

SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Sub-domains processed are:  -d www.*****.nip.io -d demo.******.nip.io -d backend.****.nip.io
No e-mail address entered or address invalid
http validation is selected
Certificate exists; parameters unchanged; starting nginx
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please retrieve a free license key from MaxMind,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing... 
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Server ready
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
nginx killed (pid 524)
nginx killed (pid 525)
nginx killed (pid 526)
nginx killed (pid 527)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
nginx killed (pid 1327)
nginx killed (pid 1328)
nginx killed (pid 1329)
nginx killed (pid 1330)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
nginx killed (pid 3221)
nginx killed (pid 3222)
nginx killed (pid 3223)
nginx killed (pid 3224)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
nginx killed (pid 4489)
nginx killed (pid 4490)
nginx killed (pid 4491)
nginx killed (pid 4492)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address in use)

**Comment by j0nnymoe** [comment]
Don't use your own `default` file, use the one that's include as a base and merge your changes into that.

Also, you need to be using https://github.com/linuxserver/docker-swag

**Comment by KumarWaghmode** [comment]
@j0nnymoe Now I am using https://github.com/linuxserver/docker-swag. I am hoping that the issue will not occur with swag image. Please elaborate on using 'default' file.

**Comment by Roxedus** [comment]
You are incorrectly changing the default file.

**Comment by KumarWaghmode** [comment]
@Roxedus Please point incorrect things so that I can rectify it.

**Comment by j0nnymoe** [comment]
`./nginx:/config/nginx/site-confs/default` 
This line from your compose, you need to remove it
