### ISSUE TITLE
PHP config files

### ISSUE THREAD

**Issue by sethkush** [linuxserver/docker-letsencrypt#54]
Is there any way to change the php configuration? I like to put 

> `disable_functions = "show_source, system, shell_exec, passthru, exec, phpinfo, popen, proc_open, allow_url_fopen"`

 in my php.ini, but there is no php config in my etc folder.

**Comment by aptalca** [comment]
Php makes too many changes to the content and structure of their config files between version updates. Therefore, we keep them internal so we can control and update them when necessary.

If you really want to make changes to them, you can always volume map your custom files into the container in your docker create/run command
`-v /path/to/your/custom/php.ini:/etc/php7/php.ini` but keep in mind that once you do, we can't provide further support and you're on your own
