### ISSUE TITLE
Is --privileged really needed?

### ISSUE THREAD

**Issue by RichoDemus** [linuxserver/docker-letsencrypt#55]
I tried starting the container without --privileged and it seems to work fine, to my understanding running privileged containers should be avoided if possible, I think there should either be a clarification on why it's needed or it should be removed from the example

Thanks for an awesome image!

**Comment by aptalca** [comment]
Fail2ban cannot modify the iptables without privileged

**Comment by RichoDemus** [comment]
I see, thanks a lot for the swift response
