### ISSUE TITLE
Nginx breaks serving of cached assets (permission denied)

### ISSUE THREAD

**Issue by grOGH** [linuxserver/docker-letsencrypt#56]
Running Debian 8.8 with Docker version 17.03.1-ce, build c6d412e and the following run command:

 docker run -d --privileged --name=letsencrypt -v /opt/letsencrypt:/config -e PGID=1001 -e PUID=1001  -e DHLEVEL=4096 -e EMAIL=xxx -e URL=xxx -e SUBDOMAINS= -p 443:443 -e TZ=Europe/Paris linuxserver/letsencrypt 

/opt/letsencrypt has 1001:1001 as owner and is on the root filesystem.

Everything works fine after the container is created, but after a while (hours to days) nginx stops delivering random asset files (js, css) on both served content and reverse-proxied sites, breaking them.

The nginx error log then contains the following (example):

2017/05/12 09:24:57 [crit] 348#348: *4540 open() "/var/lib/nginx/tmp/proxy/7/02/0000000027" failed (13: Permission denied) while reading upstream, client: 192.168.1.1, server: xxx, request: "GET /gitea/css/semantic-2.2.1.min.css HTTP/1.1", upstream: "http://172.24.0.2:3000/css/semantic-2.2.1.min.css", host: "xxx"

The tmp file its looking for doesn't exist. Running chmod -R 777 tmp/ or recreating the container fixes it for a short while, until it happens again on another random asset.

The tmp directory is not mapped and has 1001 as owner.

Is this a cache setting issue in the image? If so, can caching of assets be disabled?

**Comment by ethanopp** [comment]
Was getting this for a while too... Try adding the following to your proxy.conf:
`client_body_temp_path /tmp 1 2;`

Also make sure in your locations you have the following so it gets passed through:
`include /config/nginx/proxy.conf;`

**Comment by joshslater** [comment]
Thanks for the tip -- I had to add the following as well:

```
fastcgi_body_temp_path /tmp 1 2
proxy_body_temp_path /tmp 1 2
```

I was having the same issue with the nextcloud nginx server, so had to add those 3 there too. I don't know if all are needed for each service, but seems to have been stable for a couple days now.

Don't think this should be closed... seems like some sort of nginx permissions issue in multiple linuxserver.io dockers...

**Comment by aptalca** [comment]
The reason it was closed is because the original poster did not respond in over a month.

In any case, the recent update for nginx changed the tmp folder from /var/lib/nginx/tmp to /var/tmp/nginx (not sure if they made any other changes to their tmp file creation code)

The permissions for both folders are set correctly in this image. So if there are permission issues with files newly created by nginx, it is an nginx issue and should be taken up with them.

**Comment by grOGH** [comment]
Sorry, I forgot to update this issue.

The body_temp_path directives had no effect for me, so I solved it by mapping the tmp directory to the host:

`  -v /tmp/nginx:/var/lib/nginx/tmp`

No issues with permissions since.

**Comment by giorgiosironi** [comment]
Google finds `proxy_body_temp_path` only on this page, which seems strange.

**Comment by giorgiosironi** [comment]
I think http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_temp_path is what we are after.
