### ISSUE TITLE
 ..

### ISSUE THREAD

**Issue by acadotte** [linuxserver/docker-letsencrypt#65]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
Forgot the details or posted by mistake?!?

**Comment by acadotte** [comment]
Must have been a mistake. I dont recall starting a thread. Sorry.


Sent from my Bell Samsung device over Canada's largest network.

-------- Original message --------
