### ISSUE TITLE
Auto-reload nginx config if config file is changed (feature)

### ISSUE THREAD

**Issue by nalt** [linuxserver/docker-letsencrypt#71]
It would be helpful if nginx automatically reloads its config once a config file is changed. This could be implemented via inotifywait and be enabled only optionally.

**Comment by sparklyballs** [comment]
edit the file(s) and restart the docker. 

we used inotify at one time in our image and it was a PITA tbh.

**Comment by 1activegeek** [comment]
Is it possible to document or add a way to allow a docker command to reload the config? While yes I can restart the container, when I'm working on a new RP config, it's a pain to have to keep restarting the container itself. I'd love to be able to send a reload command like: `nginx -s reload` but unfortunately I keep getting errors when trying.

**Comment by tobbenb** [comment]
docker restart letsencrypt is just as easy as your reload command, isn't it?

**Comment by 1activegeek** [comment]
Yes/No. Using the docker command requires extra permission - yes I know I can add myself to the group, but I'd rather not. And the bigger concern is the time it takes to be able to restart is longer/more than just reloading the config.

I'm not trying to cry like it's the biggest issue in the world here - but hey seconds matter when you're working on a config back and forth and have to keep restarting. Additionally, it takes my site offline for a longer period vs being able to reload inline could just drop current connections and restart them as soon as they come back in, whereas restarts require waiting for the service to completely recycle.

**Comment by aptalca** [comment]
This command will make nginx reload its config from inside the container:

`s6-svc -h /var/run/s6/services/nginx`

**Comment by 1activegeek** [comment]
Sweet! Thanks @aptalca

**Comment by nalt** [comment]
A simple option: `killall -HUP nginx`. Applies to all running nginx, even from outside the container, but there may be rights issues.
