### ISSUE TITLE
Varible For PHP upload size

### ISSUE THREAD

**Issue by NathanTheGr8** [linuxserver/docker-letsencrypt#77]
Feature request

Have a variable to specify php uploads size. Currently, I just mount php.ini as a volume
-v /path/to/your/custom/php.ini:/etc/php7/php.ini
but it is less than ideal if php makes a big config change.

**Comment by aptalca** [comment]
See the PR to the baseimage here: https://github.com/linuxserver/docker-baseimage-alpine-nginx/pull/33

Once merged, it will create a php-local.ini file in the config folder, and whatever you set in there will overwrite the directives in php.ini

I have no idea why that php feature is not advertised more. So much better than editing the php.ini and then having issues when updating php

**Comment by NathanTheGr8** [comment]
awesome thanks!
