### ISSUE TITLE
Issues with headers when proxying https

### ISSUE THREAD

**Issue by realies** [linuxserver/docker-letsencrypt#84]
As described [here](https://github.com/nextcloud/server/issues/7213), having the server port explicitly listed on SSL connections within the `Host` header can lead to unexpected results. Perhaps encapsulate [this](https://github.com/linuxserver/docker-letsencrypt/blob/7a5926c8322b37330bd15ef59794c1d13b40863a/root/defaults/proxy.conf#L14) in an if statement?

**Comment by aptalca** [comment]
proxy.conf is a user editable config file residing in the /config folder. What we provide is a starting point that works in most scenarios (not all). Feel free to edit it however you like when you edit your nginx and site conf's. You can also create your own proxy.conf files (named differently) and referenced in your site config.

**Comment by realies** [comment]
The point in opening this issue is to discuss modifications that will provide as transparent default proxy config as possible.
