### ISSUE TITLE
Suggestion: Option to temporarily use self-signed certificate

### ISSUE THREAD

**Issue by jgaurilo** [linuxserver/docker-letsencrypt#89]
First of all, thank you for the great container release, keep up the good work! 👍  

I think it would be great idea to add option to bypass letsencrypt certificate obtaining process temporarily and use self-signed certificate instead while setting up other containers and experimenting with subdomains and stuff.

It would also be great for the times when you are hit with rate limit error from letsencrypt because you were setting up your server just the way you like it, like I just was 😁

**Comment by aptalca** [comment]
You can use our nginx image for that. You can even flip flop between the two since the letsencrypt image is based on the nginx one
