### ISSUE TITLE
Add sleep timer for failed validation

### ISSUE THREAD

**Issue by LBegnaud** [linuxserver/docker-letsencrypt#90]
I have rolled my own slight modification of this project because I kept running into issues where things wouldn't be set up just right and the container would stop after failing to validate. I prefer to use "unless-stopped" restart action in general, and in this instance it would cause the container to continue restarting until all validation attempts are used up.

My suggestion is to add an option for the failure sleep timer. I can make a PR for what I'm suggesting if that would be preferred.

**Comment by aptalca** [comment]
I think there was a build time related reason for that container stop upon failed validation. I'll talk to the rest of the team and see if it's feasible to add a sleep. I guess more and more users are setting restart to always and getting throttled.

**Comment by LBegnaud** [comment]
Thanks. Seems like a default of a few seconds would be useful in general so you can see the log before the container stops, but I prefer to use `sleep infinity` so it waits until human intervention.
