### ISSUE TITLE
Impossible to renew or issue certificates

### ISSUE THREAD

**Issue by viruz82** [linuxserver/docker-letsencrypt#93]
At the moment it's not possible to renew or issue certificates. The following error occurs:
```Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.```

Here you can find the explanation: https://community.letsencrypt.org/t/solution-client-with-the-currently-selected-authenticator-does-not-support-any-combination-of-challenges-that-will-satisfy-the-ca/49983

Cheers 
Kai

---
Sent by mobile

**Comment by aptalca** [comment]
Check out the changelog
