### ISSUE TITLE
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA

### ISSUE THREAD

**Issue by Xosmond** [linuxserver/docker-letsencrypt#95]
A problem with cerbot need to use cerbot-auto or get:
```
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA
```

This article:
https://community.letsencrypt.org/t/solution-client-with-the-currently-selected-authenticator-does-not-support-any-combination-of-challenges-that-will-satisfy-the-ca/49983

**Comment by romancin** [comment]
Wow! I didn’t know this. I have to read a lot about this, because my port 80 is used for another application, not for letsencrypt container, and my domains are managed by OVH and it seems I cannot use dns validation because of this...

Thank you really much for your help!

**Comment by aptalca** [comment]
if ovh lets you point the nameservers elsewhere, I recommend cloudflare. It's free and easy to set up. Just set it to dns only and you'll be good

**Comment by romancin** [comment]
I think it would be difficult, because I have dynamic IP address and have a dyndns configured on my router tu update on boot the IP on OVH. I will check if I can do the same using cloudflare.

Thank you again :D
