### ISSUE TITLE
TLS-SNI has been disabled in Cetbot. Update config to default to HTTP-01

### ISSUE THREAD

**Issue by zackbcom** [linuxserver/docker-letsencrypt#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.04

standard docker run command.

When using default value to HTTPVAL environmental variable.
2018-01-21 16:17:56,603:CRITICAL:certbot.auth_handler:Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.

no symlinks.

Fix:
Set HTTPVAL defaut to true while TLS-SNI is disabled. - https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811

Yes, probably could be fixed wit a pull request.

**Comment by j0nnymoe** [comment]
Already been done.
Reference: https://github.com/linuxserver/docker-letsencrypt/commit/3d6b28aa01cc5aee65ec1f1e16aa2b9530364f8e + https://www.linuxserver.io/2018/01/11/psa-changes-to-our-lets-encrypt-container/
