### ISSUE TITLE
Upgrade Insecure Requests

### ISSUE THREAD

**Issue by LBegnaud** [linuxserver/docker-letsencrypt#98]
I suggest we add another header into the default nginx.conf file

`add_header Content-Security-Policy "upgrade-insecure-requests";`

This would solve issues with certain webservers not respecting proxy headers and embedding improper links/references.

**Comment by aptalca** [comment]
Can you elaborate on this issue? What problem is it exactly causing and is it a problem for the majority of users out of the box?

If it only affects certain users hosting certain websites, then I'm not inclined to add it, since nginx.conf is already user customizable.

**Comment by LBegnaud** [comment]
Sure. This doesn't apply to everyone of course, but AFAIK this setting is ignored if things are configured properly (I.E. the backend server presents links that are relative to the host and scheme)

More information can be found here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests 

It's a suggestion since the inclusion of HSTS in the default nginx.conf can potentially break sites if this directive isn't also set.

**Comment by aptalca** [comment]
If I understand correctly, this only tells the browser to replace http links with https while browsing in an attempt to fix the mixed content issue.

Current HSTS implementation is not properly done and I've been meaning to fix that in the default config. It sends it over http as well, which it shouldn't. And the user may not want it if they also use http links on the same domain. Anyway, I will push an update to the default config soon to fix it and make it optional, I will also keep this header in mind.

**Comment by LBegnaud** [comment]
I like the placement of an optional file with all the ssl hardening in one place. It's up to you if you want to or not, but note that the `add_header` directive clobbers any other levels, so including the new `ssl.conf` will ignore the ones you have in the default `nginx.conf`. Not sure what your stance is on hand-holding people new to nginx, but just thought it was worth mentioning.

And of course, thanks for the work.

**Comment by aptalca** [comment]
The add_header directives are removed from the default nginx.conf
For existing users, none of these updates will change anything. The container does not overwrite the configs in the config folder. This will only be in effect for the new users. Existing users can of course modify their configs manually to conform to the new standards, that's why we added the versioning with the git history links for each new default config file

**Comment by LBegnaud** [comment]
Oh they sure are, my mistake. I could have sworn i saw only the HSTS `add_header` directive removed, but you're right. Party on
